### ISSUE TITLE
Dependabot configuration: enable auto merge for patch and minor

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1002]
- related to https://github.com/jhipster/generator-jhipster/issues/12746

See documentation: https://github.com/dependabot/fetch-metadata#enabling-auto-merge

I think it's a good idea to enable auto merge for patch and minor version

**Comment by beatfreaker** [comment]
@pascalgrimaud can I work on this ?

**Comment by pascalgrimaud** [comment]
yes @beatfreaker and thanks a lot :)
