### ISSUE TITLE
Upgrade to Spring Boot v2.7.0-MX

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1007]
To try only in JHipster Lite, not in generated projects

**Comment by matthieulapatate** [comment]
Seems like the version 2.7.0 is not yet deployed on maven repositories. Witness this link : https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot/

**Comment by pascalgrimaud** [comment]
Yes it's normal. You need to add repositories and pluginRepositories for this.
See the generator-jhipster:

https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/pom.xml.ejs#L33-L61

**Comment by beatfreaker** [comment]
@pascalgrimaud working on this.
