### ISSUE TITLE
Maven: add repositories

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#101]

**Comment by DanielFran** [comment]
@pascalgrimaud Should I create a variant for snapshotRepository?

**Comment by pascalgrimaud** [comment]
@DanielFran : if you think it can be usefull in short roadmap yes. Otherwise, I'd think it's better to add new methods only when needed :)

**Comment by DanielFran** [comment]
@pascalgrimaud Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/60925

**Comment by pascalgrimaud** [comment]
@DanielFran : approved
