### ISSUE TITLE
Frontend: Add Console Logger for errors

### ISSUE THREAD

**Issue by Franceq34** [jhipster/jhipster-lite#1013]

**Comment by pascalgrimaud** [comment]
Adding a bounty on this, as it's really important to have

**Comment by pascalgrimaud** [comment]
@Franceq34 : is it fixed by https://github.com/jhipster/jhipster-lite/pull/1014 ? Can we close this ?

**Comment by Franceq34** [comment]
Yes it is !

**Comment by pascalgrimaud** [comment]
ok @Franceq34 : so you use `fix` for closing automatically the ticket in the description of PR :)

**Comment by Franceq34** [comment]
$100 bounty claimed => https://opencollective.com/generator-jhipster/expenses/74249

**Comment by pascalgrimaud** [comment]
@Franceq34 : approved
