### ISSUE TITLE
Frontend: Add router into Vue app generated

### ISSUE THREAD

**Issue by seraphinandrieux** [jhipster/jhipster-lite#1018]
As already implemented into the webapp generator, the point is to generate by default the router into a vue app

**Comment by pascalgrimaud** [comment]
Do you think we should include it by default in a generated vue app?
Or should it be a separated additional feature?

**Comment by seraphinandrieux** [comment]
We could begin by an additional feature. However I cannot imagine a front app without router.
As you prefer :)

**Comment by pascalgrimaud** [comment]
It won't change anything, I think, as it will be new method in domain, so we can compose and use it in init
Let's do this:
- new method addRouter in domain service
- use it in init too

What do you think ?

**Comment by seraphinandrieux** [comment]
Deal

**Comment by seraphinandrieux** [comment]
Deal

**Comment by pascalgrimaud** [comment]
adding a bounty as it's important to have, before working on account + jwt

**Comment by pascalgrimaud** [comment]
I reopen this to not forget to add the new API to generate.sh in CI

**Comment by pascalgrimaud** [comment]
oh I see, the router is added by default in Vue.
Sounds good, so let's close this
