### ISSUE TITLE
Sonar: question

### ISSUE THREAD

**Issue by qmonmert** [jhipster/jhipster-lite#10275]
We have 3 issues on the generated app:
https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster_jhipster-lite-sample-app

But this is strange, we have:
https://github.com/jhipster/jhipster-lite/blob/e50658a9bb737f3275c0c5a23d1d665e650b2b3b/src/main/resources/generator/server/springboot/mvc/web/test/BeanValidationErrorsHandlerTest.java.mustache#L41
whereas
https://github.com/jhipster/jhipster-lite-sample-app/blob/d5d95b18aaab4849ff8a5eb0fe8c1c66a37b235f/src/test/java/tech/jhipster/lite/sample/shared/error/infrastructure/primary/BeanValidationErrorsHandlerTest.java#L40

cc @pascalgrimaud

**Comment by pascalgrimaud** [comment]
Already fixed it this afternoon :-)
But it was after the release

**Comment by qmonmert** [comment]
@pascalgrimaud ok 👍
