### ISSUE TITLE
Core: format with prettier after generating files

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#104]

**Comment by DamnClin** [comment]
Do we add a common property to all modules to enable formatting after application? This could be done easily and will let the user choose

**Comment by pascalgrimaud** [comment]
yes, several idea:
- your one, allow formatting after each 'apply'
- a new button to launch npm install + npm run prettier -> it could be a module too, something like:
- 
![image](https://user-images.githubusercontent.com/9156882/176446899-d5f71b40-932c-4648-9ceb-a97fc31074c6.png)

**Comment by DamnClin** [comment]
Ok, will be coverred after: 

* https://github.com/jhipster/jhipster-lite/pull/2731
* https://github.com/jhipster/jhipster-lite/issues/2732

**Comment by pascalgrimaud** [comment]
Let's close this in favor of https://github.com/jhipster/jhipster-lite/issues/2732
