### ISSUE TITLE
Rename generated front test folders?

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#10414]
Should we rename generated frontend application test folders to "unit" and "component" to match the nammings used in the generator app and add some consistence to that? This is a breaking change for the generated applications

cc @murdos  @pascalgrimaud @qmonmert any advice on that?

**Comment by murdos** [comment]
I think it would be nice to do it.
Sure it might be considered a breaking change, but I'm not sure that we have a lot of users for the frontend modules.

**Comment by pascalgrimaud** [comment]
Same opinion than @murdos 
Let's do it

**Comment by murdos** [comment]
Do we all agree to also rename the `test/javascript` folder to `test/webapp`?
This is how the generator itself is structured, and that way it's coherent with the `src/main/webapp` folder
