### ISSUE TITLE
Disable virtual threads by default on generated Spring app

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#10474]
There are some edge cases where the usage of java 21 virtual threads is causing issues, so it's better to turn it off, as done by Spring Boot.

**Comment by Harsh4902** [comment]
@murdos Can I work on this issue?

**Comment by murdos** [comment]
@Harsh4902 : sure! :)

**Comment by Harsh4902** [comment]
@murdos I hope this change will work.

**Comment by dmurat** [comment]
Can you please shed some light on those issues with virtual threads? Is this something like what is described in the link below, or have you found something else? Tnx.
https://stackoverflow.com/questions/78790376/spring-boot-application-gets-stuck-when-virtual-threads-are-used-on-java-21

**Comment by murdos** [comment]
Here are a few examples:
- https://netflixtechblog.com/java-21-virtual-threads-dude-wheres-my-lock-3052540e231d
- https://github.com/spring-projects/spring-kafka/issues/3074
- https://jira.qos.ch/browse/LOGBACK-1711

It doesn't mean virtual threads should not be used, just that this is should be a careful thoughtful decision since the ecosystem is not yet mature. That's why it's wiser to disable it by default :)
