### ISSUE TITLE
Current coverage not at 100%

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#10518]
Following the last change related to Sonar, the current coverage is not at 100%

See https://sonarcloud.io/component_measures?id=jhipster_jhipster-lite&metric=coverage&view=list

**Comment by qmonmert** [comment]
<img width="314" alt="image" src="https://github.com/user-attachments/assets/f5128c26-d4e1-449f-9e8e-0fc8a4b26a88">
