### ISSUE TITLE
preset.json in spring config 

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#10553]
See https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepository.java#L29

Instead of hard coding this file, it should be nice to allow this as config in spring properties

Several use cases:
- in jhlite extension, we could use specific presets
- in spring profile vue, we could have vue instead of angular
- etc

**Comment by renanfranca** [comment]
It’s a really good enhancement. I’m going to work on this as soon as I can!

FYI, I generated a project with the jhlite-custom module, and if I create a `preset.json` file in the `src/main/resources` root, it already overrides the `preset.json` defined in the JHLite project 😃🎉

![image](https://github.com/user-attachments/assets/32a61f22-2151-4927-bdab-d14a1a24b606)

**Comment by pascalgrimaud** [comment]
Yes, it's spring mechanism :-)
