### ISSUE TITLE
Cypress/Playwright: split current module in two modules: e2e tests and component-tests

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#10613]
The current `cypress` module generates something that looks like frontend component tests (using the Martin Folwer definition, not the Cypress definition of component tests): things are generated in `src/test/webapp/component`, npm script is `test:component`, ...

We should probably improve the current module to also automatically start the frontend server, so component tests can be launched without prerequisites by launching `npm run test:component` (see current generator configuration).

And create a new one that would generate Cypress configuration for running E2E.

**Comment by murdos** [comment]
@pascalgrimaud : bounty claimed https://opencollective.com/generator-jhipster/expenses/224383

**Comment by pascalgrimaud** [comment]
@murdos : approved
