### ISSUE TITLE
Preset: modules selected and deselected

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#10660]
Strange behavior. The initial modules are selected or deselected when switching between presets

To reproduce the issue:
- go to https://lite.jhipster.tech/landscape
- select 1st preset
  - the module `application-service-hexagonal-architecture-documentation` is selected
- select the 2nd preset
  - the module `application-service-hexagonal-architecture-documentation` is not selected anymore, but in config it is

**Comment by renanfranca** [comment]
I can't fix it right now. Only on Monday or Tuesday 👍
