### ISSUE TITLE
Move husky and lintstaged setup from 'prettier' module to 'init'

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#10701]
Git hooks and actions on commit are not specific to prettier.
It would be nice if this was directly available on any initiated project.

An example of non-prettier usage: when you use the protobuf-backwards-compatibility-check module, it would be nice to check and update automatically the lock file when you change protobuf files.

**Comment by fabienpuissant** [comment]
So the init module will have an empty .husky folder and other modules will feed this with pre-commit, pre-push etc files ?

**Comment by murdos** [comment]
@fabienpuissant : the init module would have configured husky to run lint-staged, but lint-staged configuration would have no configured rules:
```
module.exports = {
};
```

**Comment by pascalgrimaud** [comment]
It seems relevant. I agree with your suggestion @murdos

**Comment by fabienpuissant** [comment]
@murdos Can I take the point ?

**Comment by murdos** [comment]
> @murdos Can I take the point ?

Sure! Go ahead! :)

**Comment by pascalgrimaud** [comment]
Adding a small bounty since it's more work than expected, and we need to be careful not to break the generation.

**Comment by fabienpuissant** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/218916. Thanks 😃

**Comment by pascalgrimaud** [comment]
@fabienpuissant : you need to change your invoice as it must be in dollars, not in euro. Can you?

**Comment by pascalgrimaud** [comment]
@fabienpuissant : you need to update the new value too, as it was converted

![image](https://github.com/user-attachments/assets/9ec45ac3-9ccb-451b-9fe9-408716927db4)

**Comment by pascalgrimaud** [comment]
it's approved, thanks for your patience and thanks for your hard work @fabienpuissant !
