### ISSUE TITLE
Handle Optional in Jackson

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#10751]
Add jdk8Module

```
@Configuration
class JacksonConfiguration {

  @Bean
  public Module jdk8Module() {
    return new Jdk8Module();
  }
}
```

And configuration:

```
spring.jackson.default-property-inclusion: non_absent
```

Updates to do in `SpringBootCoreModuleFactoryTest` and `SpringBootCoreModuleFactory`

**Comment by murdos** [comment]
@DamnClin : Out of curiosity, what is your need/use case for this?
I'm wondering if this need to be the default in our spring-boot module, or if this would be better placed in a specific new module.

**Comment by DamnClin** [comment]
> @DamnClin : Out of curiosity, what is your need/use case for this? I'm wondering if this need to be the default in our spring-boot module, or if this would be better placed in a specific new module.

I think this should be default since you wan't that to work when using `Optional` in primary model
