### ISSUE TITLE
Sonar: 3 issues related to ApprovalTests PackageSettings

### ISSUE THREAD

**Issue by qmonmert** [jhipster/jhipster-lite#10901]
![image](https://github.com/user-attachments/assets/f50c66ef-e3cd-4e21-aecf-2ebc3846a1cd)

https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&sinceLeakPeriod=true&id=jhipster_jhipster-lite

![image](https://github.com/user-attachments/assets/b6da77bc-bfe1-4093-8afb-d86ac20e3189)

@murdos it seems related to your last development

**Comment by murdos** [comment]
We'll need to add Sonar exclusions, because we don't have choice, it's how the library we use have named things: https://github.com/approvals/ApprovalTests.Java/blob/master/approvaltests/docs/Configuration.md#package-level-settings

**Comment by qmonmert** [comment]
![image](https://github.com/user-attachments/assets/02cbac1b-0ff7-46e7-92b1-5ad48218a9b0)
Fixed
