### ISSUE TITLE
Update jhipster-lite-sample-app

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#10926]
According to the recent changes, I was not able to generate correctly the sample.
I think we need to update this [file](https://github.com/jhipster/jhipster-lite-sample-app/blob/main/generate.sh)

**Comment by qmonmert** [comment]
@pascalgrimaud https://github.com/jhipster/jhipster-lite-sample-app/pull/5

**Comment by pascalgrimaud** [comment]
Thanks, I'll need to launch the generate process there.
But no computer until monday :-)

I wonder if you have permission to do it? You or @murdos ?

**Comment by renanfranca** [comment]
> But no computer until monday :-)

I'm also under this "no computer until Monday" policy 😄

**Comment by qmonmert** [comment]
@pascalgrimaud I did a PR (release 1.18.2) https://github.com/jhipster/jhipster-lite-sample-app/pull/6

**Comment by qmonmert** [comment]
@pascalgrimaud PR for release 1.19.0 🙂 https://github.com/jhipster/jhipster-lite-sample-app/pull/7

**Comment by murdos** [comment]
Done :)
