### ISSUE TITLE
Is src/test/webapp/component/**/*.ts ts configfr exlusion usefull?

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#10925]
In tsconfig for vue app there is an exclusion for "src/test/webapp/component/**/*.ts", is this still usefull?

**Comment by renanfranca** [comment]
Hello @DamnClin ,

I would like to take this opportunity in our discussion to ask how files that do not have 100% test coverage should be excluded.  

For instance, if you look at [this comment](https://github.com/jhipster/jhipster-lite/issues/1133#issuecomment-2358964937) regarding the files I will add with the `vue-oauth2-keycloak` module. What I thought was to add each file individually as an exclusion. What do you think?

**Comment by DamnClin** [comment]
> Hello @DamnClin ,
> 
> I would like to take this opportunity in our discussion to ask how files that do not have 100% test coverage should be excluded.
> 
> For instance, if you look at [this comment](https://github.com/jhipster/jhipster-lite/issues/1133#issuecomment-2358964937) regarding the files I will add with the `vue-oauth2-keycloak` module. What I thought was to add each file individually as an exclusion. What do you think?

This is not a coverage exclusion but a build exclusion :).

For coverage exclusion my take is: as long as we can't get a proper merge we should remove this metric. I think not metric is better than a wrong one

**Comment by renanfranca** [comment]
> > Hello @DamnClin ,
> > I would like to take this opportunity in our discussion to ask how files that do not have 100% test coverage should be excluded.
> > For instance, if you look at [this comment](https://github.com/jhipster/jhipster-lite/issues/1133#issuecomment-2358964937) regarding the files I will add with the `vue-oauth2-keycloak` module. What I thought was to add each file individually as an exclusion. What do you think?
> 
> This is not a coverage exclusion but a build exclusion :).

Oh, my bad! 

> 
> For coverage exclusion my take is: as long as we can't get a proper merge we should remove this metric. I think not metric is better than a wrong one

Should we remove the code coverage 100% metric from the frontend generated apps?

**Comment by renanfranca** [comment]
> For coverage exclusion my take is: as long as we can't get a proper merge we should remove this metric. I think not metric is better than a wrong one

> Should we remove the code coverage 100% metric from the frontend generated apps?

@DamnClin : as this code coverage discussion is not the main topic of this issue, I created a discussion here:
- https://github.com/jhipster/jhipster-lite/discussions/10927
