### ISSUE TITLE
Sonar: 8 issues

### ISSUE THREAD

**Issue by qmonmert** [jhipster/jhipster-lite#10995]
![image](https://github.com/user-attachments/assets/bcc7a274-e26a-44b7-8cec-ddcaf07a4eb6)

https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster_jhipster-lite

cc @pascalgrimaud

**Comment by pascalgrimaud** [comment]
Thanks a lot for fixing this and your last work too

**Comment by qmonmert** [comment]
Fixed
![image](https://github.com/user-attachments/assets/0a6b0e21-229d-476d-ad82-3d2c24d72328)

@pascalgrimaud thanks https://opencollective.com/generator-jhipster/expenses/221909

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
