### ISSUE TITLE
Update maven version to 3.8.5

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1100]
The upgrade was done here: https://github.com/jhipster/jhipster-lite/pull/1089

But I revert this PR here: https://github.com/jhipster/jhipster-lite/pull/1099

There are some problems with IntelliJ:
- https://youtrack.jetbrains.com/issue/IDEA-290419
- https://youtrack.jetbrains.com/issue/IDEA-290590
- https://youtrack.jetbrains.com/issue/IDEA-290482

**Comment by pascalgrimaud** [comment]
cc @DanielFran : it's important that you're aware of the problem with IntelliJ

**Comment by DanielFran** [comment]
@pascalgrimaud thanks for the info. Will revert it in other projects

**Comment by DanielFran** [comment]
@pascalgrimaud All 3 issues reported have been fixed

**Comment by pascalgrimaud** [comment]
@DanielFran : thanks, will have a look

**Comment by DanielFran** [comment]
@pascalgrimaud confirmed working with _IDEA 2021.3.3 Build #IU-213.7172.25 built on March 15, 2022_

**Comment by pascalgrimaud** [comment]
Ok so we can revert the revert :-)
