### ISSUE TITLE
Cloud providing JHipster-lite application

### ISSUE THREAD

**Issue by matthieulapatate** [jhipster/jhipster-lite#1107]
The idea would be to host the application on cloud in order to permit the application to be accessible everyone by everyone.

In a first hand, i would like to deploy the application on a simple Heroku server, kind of staging website in tests the new front-end fonctionnalities. The server will generate the asked files locally on the server and then when the user will ask for it, he will receive a zip file withs all the files in it.

After this will be done, we will need to think about the way to implement the application with security part because the problem coming with this method is that everyone will be able to spam the generation part and break the server.

The work will be done on the branch "CloudProviding" and the application will be available at :https://jhipsterlite.herokuapp.com/

**Comment by matthieulapatate** [comment]
State of progress :

- On backend : It is now possible to call the download API to package your application into a zip which can be use much way wilder than just in jhipster way

- For hosting, i created a buildpack that i hosted on my repository https://github.com/matthieulapatate/jhipster-lite-buildpack (not ended) that in the future will be hosted on jhipster github account

=> Soon you will be able to launch a jhipster instance application on heroku and the ability to download your project directly through it.

**Comment by pascalgrimaud** [comment]
Just created the repo: https://github.com/jhipster/jhipster-lite-heroku-buildpack

**Comment by pascalgrimaud** [comment]
closed by this last PR: https://github.com/jhipster/jhipster-lite/pull/1266
