### ISSUE TITLE
Code smells in Kipe module

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#11103]
Spotted here: https://sonarcloud.io/summary/new_code?id=jhipster_jhipster-lite-sample-app

Related to this project https://github.com/jhipster/jhipster-lite-sample-app

**Comment by qmonmert** [comment]
<img width="940" alt="image" src="https://github.com/user-attachments/assets/b5a2fdfd-da79-47d3-a21e-95a71a37981a">
fixed
