### ISSUE TITLE
[VueJS] Add Pinia into Vue generator + generated

### ISSUE THREAD

**Issue by seraphinandrieux** [jhipster/jhipster-lite#1117]
We could add an API to add Pinia which replaces VueX for state management into a Vue app

**Comment by seraphinandrieux** [comment]
Besides it's usefull for ticket #897

**Comment by pascalgrimaud** [comment]
@seraphinandrieux : which are the recommandations from Vue core team about this subject?

**Comment by pascalgrimaud** [comment]
Ok here the answer: https://vuejs.org/guide/scaling-up/state-management.html

![Screenshot_20220322-082534](https://user-images.githubusercontent.com/9156882/159429072-a281ed57-d729-4308-bfe7-e3b42c3af917.png)

**Comment by seraphinandrieux** [comment]
Yep :)
Could you assign this ticket to me ?
