### ISSUE TITLE
Allow user to download project as zip file.

### ISSUE THREAD

**Issue by matthieulapatate** [jhipster/jhipster-lite#1132]
The idea would be to allow users to upload their project as a zip by clicking a button in the webapp.

**Comment by pascalgrimaud** [comment]
Do you mean download the generated project instead ?
Because I don't understand why the user should upload the code to JHipster Lite

**Comment by matthieulapatate** [comment]
Yes dowload, it would be another option than just directly creating in their repository.

**Comment by pascalgrimaud** [comment]
So, can you update the title plz?

**Comment by pascalgrimaud** [comment]
The 1st step would be to add this to `ProjectRepository.java` :

```java
void zip(Project project);
```

Then, you need to work on the implementation

**Comment by pascalgrimaud** [comment]
@matthieulapatate : I'm waiting this 1st small PR, which should contain only:
- the method in interface
- the implem in secondary
- the unit test
- maybe the lib in pom.xml

Nothing more.

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/jhipster-lite/pull/1266
