### ISSUE TITLE
Release v1.22.0: refactoring and enhancements

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#11344]
We can see the work done here: https://github.com/jhipster/jhipster-lite/releases/tag/v1.22.0
Lot of small PR but each one is nice.

Plz claim your bounty @qmonmert

**Comment by qmonmert** [comment]
@pascalgrimaud thanks a lot https://opencollective.com/generator-jhipster/expenses/227675

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by qmonmert** [comment]
Thanks
