### ISSUE TITLE
JHLite Extension: update

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#11351]
See https://github.com/jhipster/jhipster-lite-extension

Some part needs to be regenerated

**Comment by murdos** [comment]
@pascalgrimaud : I don't understand: what issues have you encountered?

**Comment by pascalgrimaud** [comment]
I did a breaking change on properties jhlite.xxx so we need to update at least this part

**Comment by murdos** [comment]
@pascalgrimaud Oh, I see now ! Indeed, spring properties need to be updated :)

**Comment by pascalgrimaud** [comment]
I'll do it after the release of JHLite v1.23.0

**Comment by pascalgrimaud** [comment]
It's done
