### ISSUE TITLE
Tikui: inter.css brokes style

### ISSUE THREAD

**Issue by qmonmert** [jhipster/jhipster-lite#11382]
On http://localhost:9005/atom/atom.html#themebutton icons are not displayed

<img width="410" alt="image" src="https://github.com/user-attachments/assets/8148d931-1ab7-44a4-aa8e-3a29494e0e97">

If I remove this https://github.com/jhipster/jhipster-lite/blob/246067ac1a8f527be46f5a0f37b529d236ee72f5/src/main/style/layout.pug#L11 it works

`inter.css` is not loaded in https://github.com/jhipster/jhipster-lite/blob/main/src/main/webapp/index.html so no problem on http://localhost:9000/landscape

I see this PR https://github.com/jhipster/jhipster-lite/pull/10702/files#diff-e87bb40b4aac9492f70669696ae9ad0f8b2989524fd5505a1c2d777566439580
@renanfranca can you look?

**Comment by renanfranca** [comment]
@qmonmert: I can look at it later. I am sick now 🤧 👍

Thanks
