### ISSUE TITLE
Hexagonal Arch Test: forbid framework

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1147]
The current Hexagonal Arch Tests in JH Lite do not forbid the use of external framework

It's an important improvement so adding a bounty on this

**Comment by Bolo89** [comment]
Yes

**Comment by pascalgrimaud** [comment]
Yes? Do you want to work on this @Bolo89 ? I can assign it to you

The goal would be to forbid org.springframework and some other package in domain
Maybe org.*, com.*, etc
