### ISSUE TITLE
Tikui, vue & cypress headless failling

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#11642]
When using tikui on a vue application with cypress component testing `test:component:headless` fails to load styles: 

```sh
15:20:08 [vite] http proxy error: /tikui.css
Error: connect ECONNREFUSED 127.0.0.1:9005
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16)
```

This then result in errors for tests that needs css to make thinks visible.

Dunno if we should build the CSS or start tikui beforehand

@Gnuk any idea on that (I made no real investigation on my side)

For now, I'm starting Tikui with

```sh
    - '(npm run dev:tikui &) > tikui.log'
```

**Comment by pascalgrimaud** [comment]
Increasing the bounty as it's more work than initial

**Comment by qmonmert** [comment]
@pascalgrimaud thanks for the bounty, I claim https://opencollective.com/generator-jhipster/expenses/233130

**Comment by pascalgrimaud** [comment]
@qmonmert : the amount is not correct

**Comment by qmonmert** [comment]
@pascalgrimaud sorry the new one https://opencollective.com/generator-jhipster/expenses/233142

**Comment by pascalgrimaud** [comment]
@qmonmert : approved !

**Comment by qmonmert** [comment]
@pascalgrimaud thanks 🙂

**Comment by Gnuk** [comment]
CC @qmonmert and @pascalgrimaud , I've just added a feature on Tikui that may reduce possible logs on interruption and allow Preview mode from https://github.com/tikui/tikui-core/pull/263 if you want to check on Tikui core.
