### ISSUE TITLE
Spring Boot Cache: ehcache support

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#121]

**Comment by pblanchardie** [comment]
Work in progress.

**Comment by pascalgrimaud** [comment]
More work than expected, so increasing the bounty
- cache/common shared kernel
- cache/simple
- cache/ehcache

**Comment by pascalgrimaud** [comment]
Thanks a lof for all your work here @pblanchardie !

**Comment by pblanchardie** [comment]
You're welcome, thanks for your help!

**Comment by pblanchardie** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/60551

**Comment by pascalgrimaud** [comment]
@pblanchardie : approved, thanks so much for helping this project! <3
