### ISSUE TITLE
Spring Reactive/Webflux

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1223]
New context:
- `server/springboot/webflux/web`

It's similar to `springboot/mvc/web`

Need to implement, something like:

```
  void init(Project project);

  void addSpringBootWebflux(Project project);
  void addSpringBootActuator(Project project);
  void addExceptionHandler(Project project);
```

**Comment by Bolo89** [comment]
@pascalgrimaud i'm interrested, can u assign me the ticket please ?

**Comment by pascalgrimaud** [comment]
thanks @Bolo89 : it can be done in 3 separated pull request. The easiest one is addSpringBootWebflux

The hardest is ExceptionHandler :)
