### ISSUE TITLE
Quasar support

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1271]
@ctamisier will lead this part
The idea comes from this blueprint https://github.com/ctamisier/generator-jhipster-quasar

The goal here is to generate a front with [Quasar](https://quasar.dev/)
- init a project with : init, maven, java base, spring boot, tomcat
- add frontend maven plugin
- add Quasar (need to be developped)

It can be done in:
- generator/client/quasar/core

I suggest you to start a sample project, push it to GitHub, with the link here, so we can see your progress
Then, try to add Quasar, and a simple home page
Once it's good, you can start to add it to the generator part

Don't hesitate if you have any questions

**Comment by ctamisier** [comment]
Starting quasar sample project here: https://github.com/ctamisier/jhlite-sample-quasar

**Comment by pascalgrimaud** [comment]
@ctamisier : oh nice, you should add github actions so you'll have a CI

**Comment by pascalgrimaud** [comment]
@ctamisier : as soon as you consider having a good sample, ping me, so I can have a look and review the sample

**Comment by pascalgrimaud** [comment]
What is the state of this one, @ctamisier ?

**Comment by pascalgrimaud** [comment]
Last ping @ctamisier ?
If lack of interest, no problem for closing this one

**Comment by ctamisier** [comment]
Yes let's close it. I didn't take time to work on it properly.
We'll see in the future.

**Comment by pascalgrimaud** [comment]
Ok we could reopen it later
