### ISSUE TITLE
[REST-compliance] Use request body options to merge similar APIs

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-lite#1274]
Following #144

maybe try try to thing about using request bodies to specify some options like:
- `/api/servers/spring-boot/banner` with a required request body attribute of the wanted type instead of `/api/servers/spring-boot/banner/jhipster-v2` & others
- merge `/api/servers/sonar/java-backend` and `/api/servers/sonar/java-backend-and-frontend` in `/api/servers/sonar` (btw, `sonar` is not a server, this could also be changed)

This is to have a self explaining API. It's easier to list the different options allowed.

**Comment by DamnClin** [comment]
Is it still true with the modules APIs?

**Comment by pascalgrimaud** [comment]
let's close this
