### ISSUE TITLE
[REST-compliance] Create a test to be sure APIs are REST compliant

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-lite#1284]
See if there is a way to create a test to be sure all JHipster Lite's APIs are REST compliant (more details in #1273).

Could be something like a integration tests getting all the exposed APIs (not sure there is easier with Spring, to check), and checking that:
- starts with `/api/`
- n+1 terms ending with `s`
- n+2 terms not ending with `s`

Check if those rules can be applied for every URIs. If yes, keep this test and redirect to a documentation when failing.

**Comment by hdurix** [comment]
Thinking twice, not sure this is doable and correct because of exceptions like:
- `codespaces` should not be considered as a collection but as an element even if it's ending by `s`
- `feet` is the plural of `foot` (I can't find a "tech" example) so maybe not all collections should be ending by `s`

**Comment by pascalgrimaud** [comment]
@hdurix : it's like "chips" :D

**Comment by Bolo89** [comment]
Maybe to handle the exceptions, in the test, add 2 lists " en dur " : 
```java
List<String> singularEndedWithSExceptions = List.of("codespace",..);
List<String> pluralNotEndedWithSExceptions = List.of("feet", ...)
```
And if a word in the uri does not match the rule, check if it's present in corresponding list of exceptions. 
It's not very clean :/ but I've no better idea

**Comment by pascalgrimaud** [comment]
With the new module system, I think we can close this ticket
Am I correct @hdurix @DamnClin ?

**Comment by DamnClin** [comment]
Yep
