### ISSUE TITLE
[REST-compliance] Add a version in all APIs

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-lite#1285]
For now, simply add `v1/` after `/api/` for all the URIs, just to be sure that if we would eventually need to have a API with breaking change, we are ready to create a new version (`v2/`).

**Comment by DanielFran** [comment]
API versioning is always a pain, and there are at least 3 choices I would consider:
- URI path: http://www.example.com/api/v1/products
- Custom Header: Accept: version=1.0
- Vendor media type: Accept: application/vnd.example.v1+json or application/vnd.example+json;version=1.0

I used preferentially "Vendor media type," less impact on dev/client usage than the 1st option

Just my 2 cents... to be sure we choose the best approach.

**Comment by hdurix** [comment]
Thanks for your reply @DanielFran. With the "Vendor media type", is there something to do now? Or could it be done once we need a first "second" version?

**Comment by DanielFran** [comment]
@hdurix Should be done now, like define in POST the consumes/produces mediatype used like:
````
@PostMapping(
            value = "/api/toto",
            consumes = {"application/vnd.jhipster.api.v1+json"},
            produces = {"application/vnd.jhipster.api.v1+json"}
    )
````

**Comment by pascalgrimaud** [comment]
Indeed, we need to discuss if it's important to version the api because the user can still use old jar if needed, so not sure if we should maintain and keep old/new version in same app

Let's think and discuss :-)

**Comment by pascalgrimaud** [comment]
With the new module system, it can be included directly in the module, so not sure if this ticket is relevant

I'm closing this, don't hesitate to comment if you disagree, so I can reopen
