### ISSUE TITLE
Rename all `Initxxx` to `Projectxxx`

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-lite#1286]
As we now have both init and download inside `InitResource`, `InitApplicationService`, maybe it would be better to rename all to `ProjectResource`, `ProjectApplicationService` and so on.

**Comment by hdurix** [comment]
Or otherwise extract all downloading part to something new like `ProjectDownloadResource`

**Comment by pascalgrimaud** [comment]
I choose the 2nd option, to extract download part to ProjectResource

I think it's better to keep init context like this
