### ISSUE TITLE
Refactoring: Generator.component.ts

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1288]
`Generator.component.ts` can become very big.
It could be nice to split into sub component, like:
- SpringBoot.component.ts
- Angular.component.ts
- React.component.ts
- Vue.component.ts
- etc.

So SpringBoot.component.ts will call only SpringBootService for example

**Comment by Franceq34** [comment]
🔧WIP🔨

**Comment by pascalgrimaud** [comment]
Any progress on this, @Franceq34 ? If it can motivate to achieve this, I can put a bounty :)

Then, if I can have one example with 1 component, I can implement the other components.

**Comment by Franceq34** [comment]
$100 bounty claimed => https://opencollective.com/generator-jhipster/expenses/74251

**Comment by pascalgrimaud** [comment]
@Franceq34 : approved
