### ISSUE TITLE
Gradle: utils methods

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1301]
Similar to what was done for Maven, this ticket is for adding different utils methods:
https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenService.java#L11

At the same time, for each methods, we need to add the entry in https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/buildtool/generic/domain/BuildToolDomainService.java

**Comment by atomfrede** [comment]
You can assign it to me, already started something.

**Comment by lucasmippon** [comment]
Currently reading source (Maven and Gradle) to have a first insight on what has been done and see if I can start something.

**Comment by atomfrede** [comment]
I have already started small things. Hope to create a first PR during the weekend. If you find time before please go ahead.

**Comment by lucasmippon** [comment]
### To do
- [ ] Add Dependency without version
- [ ] Add Dependency with version
- [ ] Add Dependency with exclusion
- [ ] Add Test Dependency 
- [ ] Delete dependency
- [ ] Add Repository
- [ ] Add Plugin (https://docs.gradle.org/current/userguide/plugins.html)
- [ ] Add Plugin Management (https://docs.gradle.org/current/userguide/plugins.html)
- [ ] Add Plugin 
- [ ] Add Property

@pascalgrimaud, I have some question : 
- It look like the Parent relationship [doesn't exist in Gradle](https://stackoverflow.com/questions/47778100/what-is-maven-parent-in-gradle), should we throw an error for it ?
- It look like `dependencyManagement` mechanism in Maven help to have simpler child POM. Do you know if an equivalent thing exist for Gradle and do you have an hint on how it should be done ?
- It look like plugin repository declaration can't be separated from plugin declaration in Gradle, how should I handle this ? Knowing that `BuildToolService.addPluginRepository(Project project, Repository repository)` doesn't have a plugin as argument ?

**Comment by atomfrede** [comment]
I will try to answer your questions later.

**Comment by pascalgrimaud** [comment]
In fact, I'm not a user Gradle, so I don't know. It's really cool if you can help here @atomfrede , thanks :-)

**Comment by pascalgrimaud** [comment]
I'm removing the bounty and move it to https://github.com/jhipster/jhipster-lite/issues/1862
The work should be done in the module system so let's close this one in favor of https://github.com/jhipster/jhipster-lite/issues/1862
