### ISSUE TITLE
new option/endpoint to add gradle enterprise (aka build scans) to a generated application

### ISSUE THREAD

**Issue by atomfrede** [jhipster/jhipster-lite#1303]
As the build scans feature is very nice to have to get detailed analytics we should support adding it if desired. With that we could also get build scans for generated sample applications or during ci.

**Comment by pascalgrimaud** [comment]
I don't know exactly what you means, but I'm fine for adding this

**Comment by pascalgrimaud** [comment]
@atomfrede : do you plan to take this ticket?

**Comment by atomfrede** [comment]
Let's close this and integrate it into the overall gradle module https://github.com/jhipster/jhipster-lite/issues/1862
