### ISSUE TITLE
Tests: Generator.vue and Generator.spec.ts

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1372]
Currently, the `Generator.vue` + `Generator.component.ts` are covered by `Generator.spec.ts`
`Generator.spec.ts` contains some clicks + fill fields etc

But I wonder if we should use create and maintain `Generator.component.spec.ts` instead
I think about this:
- `Generator.component.spec.ts` would be used to test function in `Generator.component.ts`
- the Cypress part would be used to test click

I created this ticket, because with the current implementation, I found Cypress tests useless as it would do the clicks, like `Generator.spec.ts` already does

What do you think?
cc @seraphinandrieux @Franceq34 @nonomoho

**Comment by seraphinandrieux** [comment]
I totally agree with you.
If we can only test methods into component, go to do it into Generator.component.spec.ts.
Like that, cypress tests will only test user's interactions and displaying.

**Comment by Franceq34** [comment]
I agree with you, developping with TDD approach should lead to a `Generator.component.spec.ts` file that only tests the component. Then, cypress tests will test the html by doing the actions (clicks, forms fill..)

**Comment by pascalgrimaud** [comment]
No need it anymore as the main page will be the module one, and it's dynamic
