### ISSUE TITLE
Front: add toast

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1397]
Add toasts each time a code is generated with different status:
- success
- error

**Comment by pascalgrimaud** [comment]
thanks a lot @swarajsaaj !

**Comment by swarajsaaj** [comment]
Thanks for assigning the issue to me @pascalgrimaud .
My intuition earlier was to use bootstrap-vue but it doesn't yet support Vue 3 and Bootstrap 5, so we are left with following options:-
- Implement custom toast component in Vue using bootstrap's toast as base (https://getbootstrap.com/docs/5.1/components/toasts)
- Implement/Evaluate a supporting UI library like Quasar, VuePrime etc.
- Use a specific library (https://www.npmjs.com/package/vue-toast-notification?)

I think we can go for Option 3 for now as Option 2 seems to be an overkill. What do you suggest?

**Comment by pascalgrimaud** [comment]
The current front uses bootstrap, so why do using it directly? No need to add more lib here, I think

**Comment by pascalgrimaud** [comment]
So I would go to option 1 :-)

**Comment by pascalgrimaud** [comment]
Just to be sure @swarajsaaj

It's related to the front part of JHipster Lite:
- start with ./mvnw
- go to localhost:7471
- fill the fields
- click on init, for example
- a toast should appear

**Comment by swarajsaaj** [comment]
Yes @pascalgrimaud, as a feedback for code generation success/failure at each option 👍

**Comment by pascalgrimaud** [comment]
@swarajsaaj : don't know if you already started something, but plz hold on

I need to study accessibility so maybe the use of toast is not a good idea here

**Comment by swarajsaaj** [comment]
Hi @pascalgrimaud , I haven't started fully, I ll hold on. I was also checking the sugestion in https://github.com/jhipster/jhipster-lite/issues/1426#issuecomment-1106076302 how would that look

**Comment by pascalgrimaud** [comment]
So after thinking and discussing with @sabrinapayet and @Franceq34, using toast for displaying the result (OK/KO) when calling the API is a good idea

**Comment by Franceq34** [comment]
Hello @swarajsaaj !
Any progress on the subject ? I'm interested on the topic don't hesitate to mention ! 🤓
I think this would be a huge improvement on generator UX 📈

**Comment by swarajsaaj** [comment]
Hi @Franceq34 ,
I have made some progress here, TBH the Vue 3 structure of generator is bit new for me, will try to submit a PR soon.

**Comment by pascalgrimaud** [comment]
Adding a bounty for the work done here

**Comment by pascalgrimaud** [comment]
@swarajsaaj : don't forget your bounty here

**Comment by swarajsaaj** [comment]
@pascalgrimaud  thanks for reminding, raised here https://opencollective.com/generator-jhipster/expenses/76036

**Comment by pascalgrimaud** [comment]
@swarajsaaj : approved
