### ISSUE TITLE
Maven : Same dependency can be added twice in dependencyManagement section

### ISSUE THREAD

**Issue by MSaguer** [jhipster/jhipster-lite#1398]
**Reproduction steps**

- Run the tests-ci generation.sh script with eurekaapp parameter
- open the generated pom.xmk file

the `dependencyManagement` section contains twice the same `spring-cloud-dependencies` dependency lines.

**Analyze**

During `eurekaapp` generation, `spring-cloud-dependencies` is added 2 times but a protection is defined in MavenDomainService.addDependency() : https://github.com/jhipster/jhipster-lite/blob/e3c9ca80487dc81493b70de4884a89a95e5ad6bb/src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenDomainService.java#L98

The problem lies on the regexp definition that takes into account the identation only for the firt line and not for the following lines.

https://github.com/jhipster/jhipster-lite/blob/e3c9ca80487dc81493b70de4884a89a95e5ad6bb/src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenDomainService.java#L93-L96

**Comment by pascalgrimaud** [comment]
Yes agree, it would be important to have idempotency for all API
This part needs to be improved
