### ISSUE TITLE
Front: Generator

### ISSUE THREAD

**Issue by assimbly** [jhipster/jhipster-lite#1426]
Here is some feedback on the UI/UX of version 0.1 (in addition https://github.com/jhipster/jhipster-lite/issues/1397)

1) Sections

Make clearer sections. For example: 

- Configuration
   - Project
   - Options
- Generator.

Where project and options are subsections of Configuration. 

2) UI Elements

Currenlty several UI parts next to each other (for example Project configuration and options, or Language and Build tool. In general it's easier (like in a web shop) to put everything in a form under each other.

3) "Generator" section

- Make this section clearer separate from the configuration section
- Make it clearer what generate action can be performed (Now it has big buttons and small buttons, unclear is the difference between the two). Probably better is to put the actions in a list (the list should reflect the configuration section).
- Add generate all / generate project button below the list (to perform all actions at once)
- Give feedback when an action is completed (or failed). In issue 1397 a toast is recommended. I would avoid
  the use of popups/modals. Just give, on the button, a 'green' V when it's succesful or a 'red' X when it failed (with below an error).
- Put the download button seperate from others 

If needed I can create a mockup for this.

**Comment by pascalgrimaud** [comment]
Thanks for your suggestion @assimbly : it's just a 1st version, and indeed, it should be improved, the work is not finished. As another section should be added like Spring Boot Database, Spring Security, Spring Tools, etc. I'm waiting https://github.com/jhipster/jhipster-lite/issues/1288 to do it, because it will impact the work.

@swarajsaaj as you started the toast ticket. What do you think about green/red button instead?

> Now it has big buttons and small buttons

I don't see what you're talking about. Can you post a screen about this plz?

> Add generate all / generate project button below the list (to perform all actions at once)

For now, I don't want this. If the user want to generate all in once, just use generator-jhipster / jhipster-online to have the full big project. The idea of JH Lite is to give full control to the user, and he/she must understand each generated part.

**Comment by assimbly** [comment]
![jhipster_UI](https://user-images.githubusercontent.com/35961736/164644698-93ede170-a579-4579-9611-60e7372a96e6.JPG)

**Comment by assimbly** [comment]
It's unclear if I need to click on initialization or the other buttons. And should I click one by one? In a particular order?

**Comment by pascalgrimaud** [comment]
I totally understand your point of view.

But, I would say:
- in a real project, you start by creating an empty folder
- how can you add frontend maven plugin ? if you don't have maven in your project, it won't work

So my ideas would be (for now):
- expose all possible features in the front page, and don't care about the order
- the user will be responsible for what he/she wants to generate in his/her project

The approach of JHipster Lite is different of generator-jhipster:
- the user needs to think about what he/she wants to generate
- the user needs to understand each part

**Comment by assimbly** [comment]
Yes, the approach is different, but you can be sure that most users that will try JH Lite are still in the JH Classic mindset. That's why the UI must be extra clear that the concept/working is different.

**Comment by assimbly** [comment]
Here are some examples to give feedback on what's going when generating:

1. [Jenkins](https://www.google.nl/search?q=jenkins+ok+and+fail&hl=nl&authuser=0&tbm=isch&source=hp&biw=1696&bih=816&ei=FGliYqHfHPqV9u8PgJaGwA0&iflsig=AHkkrS4AAAAAYmJ3JPE4plpS0wu4srW8RwXXflDLYKo1&ved=0ahUKEwihuZL_oaf3AhX6iv0HHQCLAdgQ4dUDCAY&uact=5&oq=jenkins+ok+and+fail&gs_lcp=CgNpbWcQAzoICAAQgAQQsQM6BQgAEIAEOgsIABCABBCxAxCDAToICAAQsQMQgwE6BAgAEBM6BggAEAUQHjoECAAQGFAAWOgqYLkxaABwAHgAgAFTiAHUCZIBAjE5mAEAoAEBqgELZ3dzLXdpei1pbWc&sclient=img#imgrc=JmedrGp2Ts6ecM)
2. [Github](https://devcenter.heroku.com/changelog-items/1361)

This just as inspiration, but some similar UI would work for JH Lite.

**Comment by pascalgrimaud** [comment]
So don't hesitate to propose something
Once we agree, you are welcome to contribute @assimbly :)

**Comment by assimbly** [comment]
Yes, I will. This was just sharing my first impressions :)

**Comment by pascalgrimaud** [comment]
@assimbly : I'm closing this ticket in favor of https://github.com/jhipster/jhipster-lite/issues/1565

So we can discuss there
