### ISSUE TITLE
More REST compliant APIs

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-lite#144]
Rework on REST APIs to be self explaining (proposition will follow)

**Comment by fdelbrayelle** [comment]
Yep, routes should not contains any verb IMHO.

**Comment by pascalgrimaud** [comment]
any suggestions are welcome !

**Comment by pascalgrimaud** [comment]
I know our current APIs are not so nice, but without any suggestions, it can't be improved.
So your opinions are needed here, @fdelbrayelle @hdurix

**Comment by fdelbrayelle** [comment]
@hdurix Maybe we can discuss this soon?

**Comment by hdurix** [comment]
today? :)

**Comment by hdurix** [comment]
Things I have in mind:
- add `/clients` before Vue.js, React, angular... As we have `/servers/` for servers API:
  - `/api/servers/spring-boot` is compliant
  - `/api/vue` is not compliant
- try to have something like `<collection>/<id>/<collection>/<id>/.../<element>` (URL "leaf" can be either a collection, an id or an element):
  - `/api/servers/spring-boot/databases/mysql` is compliant
  - `/api/svelte/styled` is not compliant
- maybe try try to thing about using request bodies to specify some options like:
  - `/api/servers/spring-boot/banner` with a required request body attribute of the wanted type instead of `/api/servers/spring-boot/banner/jhipster-v2` & others
  - merge `/api/servers/sonar/java-backend` and `/api/servers/sonar/java-backend-and-frontend` in `/api/servers/sonar` (btw, sonar is not a server, this could also be changed)

**Comment by pascalgrimaud** [comment]
some good idea here
To ease this ticket, it's better to improve each context in separated PR, it will be easier to review and discuss

**Comment by hdurix** [comment]
OK I'm creating a ticket by topic.

**Comment by DamnClin** [comment]
I think the work on modules covers that, what do you think about closing that and keep migrating modules?
