### ISSUE TITLE
Add generation timestamp in history file

### ISSUE THREAD

**Issue by MSaguer** [jhipster/jhipster-lite#1445]
For each generatorStep executed, a new entry is created in the `.jhipster/history.json` file with the following format

```
{
    "serviceId" : "<generatorStep name>"
}
```

If the same generation is executed many times, the same serviceId will be defined many times with exactly the same data.

This history service could be improved in two different ways
- add existence check on GeneratorHistory to avoid to add twice the same line (idem potency)
- add date field to store the generation date.

What do you think of this?

**Comment by pascalgrimaud** [comment]
No it's normal, I'd like to know if the user launch again a generation
But this part can be improved by adding a timestamp, so we can know when it was generated :-)

**Comment by MSaguer** [comment]
So, a default format of java.time.Instant would do the job.

**Comment by pascalgrimaud** [comment]
can we change the scope of this ticket, to add this timestamp ?
