### ISSUE TITLE
Extract ProjectDTO from a folder

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1453]
I think it can be a good idea to have an API which will read the information in a folder, and return the ProjectDTO like this:

```json
{
  "folder": "/tmp/beer",
  "generator-jhipster": {
    "baseName": "beer",
    "projectName": "Beer Project",
    "packageName": "tech.jhipster.beer",
    "serverPort": 8080
  }
}
```

baseName : can be extracted from package.json, pom.xml, gradle file
projectName: can be extracted from package.json or pom.xml
packageName: can be extracted from pom.xml or gradle file

So with this API, it could be used in the front page:
- fill the path
- click on load button
- then the other fields are automatically filled

This 2nd part can be done in another PR

**Comment by swarajsaaj** [comment]
I can take this

**Comment by swarajsaaj** [comment]
Currently the generator does not directly store/persist "baseName" in gradle or `package.json`, rather a kebab-cased version of it is stored. Though in maven scenario, its possible to retrieve it from 'pom.xml''s `name` tag.
In #1625 I did not retrieve `baseName` in case of non-maven projects as there was no way to derive exact base name from kebab-cased field (for.e.g "cool-project" could be starting with a smaller case (coolProject) or upper case (CoolProject))

**Comment by pascalgrimaud** [comment]
Ok let me think and find a good place to use and extract baseName

**Comment by pascalgrimaud** [comment]
so I don't we have a good solution here, for Gradle
simply revert the cool-project to CoolProject would be enough I think
do you agree?

**Comment by swarajsaaj** [comment]
reverting "cool-project" to CoolProject might be bothersome in case the project's original name is starting with lowercase (coolProject).. I am afraid that can mess up the IDE imported projects due to name change.

An alternative could be to force "baseName" to be Upper camel cased always at time of initialization?

**Comment by pascalgrimaud** [comment]
Adding a bounty as it was a lot of work :-)

**Comment by swarajsaaj** [comment]
Thanks @pascalgrimaud  :).
However, the UI part is pending of pre-filling the fields, i ll raise an MR of that too soon.

**Comment by pascalgrimaud** [comment]
About the UI, yes, it's another ticket, another PR !

**Comment by swarajsaaj** [comment]
bounty claimed at https://opencollective.com/generator-jhipster/expenses/79163

**Comment by pascalgrimaud** [comment]
@swarajsaaj : approved
