### ISSUE TITLE
Discussion: client option with / without style

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1460]
Currently, when we choose a front, we have the possibility to choose:
- empty home page
- home page with minimal css

In my opinion, maintaining both option is not good to add more features.
For example, if we want to add login page (like it's done for Angular), we need to take care of 2 initial options:
- without css
- with minimal css

So I have several ideas:

1st solution:
- stay like this, I'll let the stream lead to decide and maintain future options

2nd solution:
- add front framework, with minimal home page in pure html -> the current existing API
- add a real css framework -> the API is optional
- add login page (like it's done with Angular), and there should be 2 possible login.html (1 without css, 1 with css)
- add health check page (same: 2 possible pages: without css, with css)
- etc

3rd solution:
- add front framework + css framework at the same init
- add login page (which will use component, class etc of the initial css framework)

Don't know what is the right way to do.

cc @qmonmert : what do you think? as Angular is the most advanced front in JHipster Lite

**Comment by qmonmert** [comment]
@pascalgrimaud I agree that maintaining two options is not a good idea. The third option seems to be good 🙂

**Comment by pascalgrimaud** [comment]
I think about the 3rd option too, and I'll let the stream lead to decide which css framework to use
We could use the same way than what is done in generator-jhipster:
- generate home page with bootstrap, including minimal navbar
- so it will be easier to add item in navbar, etc.

**Comment by qmonmert** [comment]
@pascalgrimaud totally agree

**Comment by pascalgrimaud** [comment]
Can I put you as the stream lead of Angular part @qmonmert ?

**Comment by qmonmert** [comment]
@pascalgrimaud yes!

**Comment by pascalgrimaud** [comment]
not sure you can maintain both: Angular and React, but I'll let you choose :)

Ok thanks, then, I'll create more ticket to improve Angular part

**Comment by pascalgrimaud** [comment]
The idea behind this is to split correctly all generation part in the DomainService
So if someone is not happy with this, he/she can code his/her own domain service, using the existing files etc

**Comment by pascalgrimaud** [comment]
There are already 2 dedicated tickets to finish this:
- already done for Angular and Vue
- needed to be done for React and Svelte

So let's close this one
