### ISSUE TITLE
Angular: improve initial generation

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1464]
To do:
- remove styled api
- keep 1 single API to init Angular part
- at the same time, add a css framework, so it will help to code the other page

Update the front part related to Angular:

![image](https://user-images.githubusercontent.com/9156882/164986392-e9a816d9-1a18-4d1d-8877-b8e87760511b.png)

**Comment by qmonmert** [comment]
@pascalgrimaud Angular Material for the CSS framework could be a good choice. What do you think?

**Comment by pascalgrimaud** [comment]
Yes, I think it's a good choice :)

**Comment by qmonmert** [comment]
@pascalgrimaud I will work on it!

**Comment by qmonmert** [comment]
@pascalgrimaud I tried a design on an example app, what do you think about that?

<img width="331" alt="image" src="https://user-images.githubusercontent.com/9989211/166107856-79b40ed7-d719-4e0f-b2dd-f2515482bc0d.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9989211/166107868-ca138191-d43b-41e7-959d-80e50711d7cf.png">

**Comment by pascalgrimaud** [comment]
The design looks good. But I wonder if we should split like generator-jhipster :
- home page, with link to login
- login page

**Comment by pascalgrimaud** [comment]
But let's keep the structure like this, and refactor the split in another PR :-)

**Comment by qmonmert** [comment]
@pascalgrimaud yes we will see in an other PR but I don't know if we should do like the generator? 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : ahaha indeed, the final goal is not to generate the same thing than generator-jhipster, because generator-jhipster generates too much code, and some stuffs are useless

We should keep in mind: if it's possible to split features, let's do it

As you're the lead on Angular part, you'll decide what you think it's better to our users

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/75975 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by qmonmert** [comment]
thanks
