### ISSUE TITLE
Front-end - Improvements

### ISSUE THREAD

**Issue by fdelbrayelle** [jhipster/jhipster-lite#1478]
Following a little test of [front-end generator](https://jhlite.herokuapp.com/generator), here are some improvements that could be achieve:
- Use a CSS "pointer" custor, so that the user knows he can click the whole button + radio button area
- Focus on the input of `Path (required) :` label

**Comment by fdelbrayelle** [comment]
I mean that when you arrive on the page, your input focus is on this field by default whether it's prefilled or not. What do you think about that?

**Comment by Franceq34** [comment]
Oh ok I see ! 
then I agree, we could do that by adding **autofocus** on the input (https://developer.mozilla.org/fr/docs/Web/HTML/Global_attributes/autofocus)

done here :
https://github.com/jhipster/jhipster-lite/pull/1482/files

**Comment by Franceq34** [comment]
both ideas were done and merged I think the ticket can be closed
