### ISSUE TITLE
Frontend: Save commands history

### ISSUE THREAD

**Issue by Franceq34** [jhipster/jhipster-lite#1520]
The idea of the ticket is to call and save the history API `/api/project-histories` each time the user calls an API.
In the future it will allow us to
- manage the state of API buttons
- display the history of the commands called.

**Comment by pascalgrimaud** [comment]
@Franceq34 : can you add some description to give some contexts to our users plz?

**Comment by pascalgrimaud** [comment]
@Franceq34 : don't forget your bounty here

**Comment by Franceq34** [comment]
$200 bounty claimed => https://opencollective.com/generator-jhipster/expenses/76378

**Comment by pascalgrimaud** [comment]
@Franceq34 : approved
