### ISSUE TITLE
Frontend: Indicate when generator buttons were already used

### ISSUE THREAD

**Issue by Franceq34** [jhipster/jhipster-lite#1549]
The goal is to update the buttons of the generator part to indicate to the user if the action was already called.

To do :
- Refactor the "init" part in a new component such as VueGenerator, SpringBootGenerator etc .. (see https://github.com/jhipster/jhipster-lite/issues/1288)
- Create a new button component in springboot context (that use DefaultButton) This new button will take in parameter the service name linked to the button and will ask the HistoryStore if it was already used
- Implement this new buttons in every XxxxxGenerator.component
- Update project history on project path update (delay on input change)

**Comment by pascalgrimaud** [comment]
@Franceq34 : don't forget your bounty here

**Comment by Franceq34** [comment]
$200 bounty claimed => https://opencollective.com/generator-jhipster/expenses/76379

**Comment by pascalgrimaud** [comment]
@Franceq34 : approved
