### ISSUE TITLE
Frontend: Add mongock support

### ISSUE THREAD

**Issue by beatfreaker** [jhipster/jhipster-lite#1553]
Front end part of #691

**Comment by beatfreaker** [comment]
Should button look like this ?
also we will have two separate button for `Mongock` and `User & Authority chagelog for Mongock`
as we have two different api correct ?

<img width="1308" alt="Screenshot 2022-05-01 at 11 34 52 AM" src="https://user-images.githubusercontent.com/4180238/166134370-b47eaff3-ef67-44b3-9a35-d4be1e5470ac.png">

**Comment by pascalgrimaud** [comment]
Yes I'm fine with this, user button is another one

I'm still working with @sabrinapayet and @Franceq34 to think about that, how to organize better all these features
