### ISSUE TITLE
Frontend : UI/UX improvements

### ISSUE THREAD

**Issue by Franceq34** [jhipster/jhipster-lite#1565]
The goal of this issue is to track the work done on UI/UX and have a better idea of what could look like the final Jhipster generator app. Feel free to **submit any idea in this thread.** 📝 If you feel creative don't hesitate to design some mock-ups with pencil/paper or any tools you are comfortable with. ([Marvel](https://marvelapp.com/features/prototyping), [Miro](https://miro.com/fr/), [Adobe XD](https://www.adobe.com/fr/products/xd.html), [Figma](https://www.figma.com/) etc ...)

### Functionalities needed 🛠

**SpringBoot generator :**

- Project configuration (path, basename, project name, package and port)
- Generator commands (cf « [Generate your project](https://github.com/jhipster/jhipster-lite#generate-your-project) » → or refer to [generator swagger](https://jhlite.herokuapp.com/swagger-ui/index.html)) (Here is the biggest challenge of the UX, as there are tens of APIs, we need to determine how to display them and filter smartly)
- Download the generated project
- Swagger access
- "About" section (JHipster, Github, Twitter, Opencollective ...) 

**Account management (cloud version) :**
- Registration
- Forgot password 

We won’t focus now on **Quarkus** generator or **Micronaut** generator, as this is a completely different context and there’s not any work began on it, but we can keep in mind that this could be added someday.

### Users habits 👤

We can imagine 3 types of user needs using JHLite.

- **The designer** : he **generates his project with the JHLite** small bricks. He initialized his project and added his favorite Springboot options. His project has its lifecycle and the user c**an come back at any moment** to add bricks (ex: adding a new database for example ...)
- **The builder** : this user **has already his project generated with or without JHLite** (maybe JHipster). He wants to add a few bricks.
- **The newbie** : this user could be **afraid with the modular aspect of JHlite**, he is a beginner or could be used to JHipster legacy. He will use an interface "Quickstart" with some API bundles -> he wants to generate his application easily with basic options.

**Comment by pascalgrimaud** [comment]
cc @assimbly as you have probably some suggestion

**Comment by pascalgrimaud** [comment]
Here the current version (v0.3.0):

![image](https://user-images.githubusercontent.com/9156882/166646768-e8167302-d9b9-411c-ab20-c92eaf5583dd.png)

**Comment by skin27** [comment]
Looks good, I will give it a try later this week to give feedback in detail.

**Comment by Franceq34** [comment]
Here is what I got using Figma.

![Capture d’écran de 2022-05-05 16-34-32](https://user-images.githubusercontent.com/24738688/166947330-47b56efd-d556-409d-93c8-ef6349eb9793.png)

On hover on a button :
![Capture d’écran de 2022-05-05 16-34-58](https://user-images.githubusercontent.com/24738688/166947332-e7b89d2e-5fa9-4df8-9257-635dc0cd782f.png)



Here's what I added : 
- Language selection in navbar
- Light/Dark mode in navbar
- Description of each APIs to help new users, because clicking on a button named "Init" could be confusing

I updated :
- highlight download button which seems important to me
- added a mandatory Toggle selector at the top : BUILD, SERVER, CLIENT, because in the current design you have to click twice to have access to buttons (example : click on SpringBoot radio button and click on Spring Boot panel header)

![Capture d’écran de 2022-05-05 16-41-29](https://user-images.githubusercontent.com/24738688/166948668-7eb0a1bf-6632-45ed-b172-730061c45180.png)

- added filters in each section (Maven/Gradle in build, Angular/React/vue in client etc ...)
I chose filters because we will be able to add subfilters -> choose springboot will add new filters : log tools, databases, databases migration etc ...)
![Capture d’écran de 2022-05-05 16-41-32](https://user-images.githubusercontent.com/24738688/166948948-8412086b-5313-4e76-86a6-7702ef3fa84d.png)

![278022192_4576934799074060_4885803103953718758_n](https://user-images.githubusercontent.com/24738688/166950912-9fbe8f07-f5d5-4ac3-9149-03cf39793b39.jpg)

Maybe we could add filters as tags below the description of each button when hovered

**Comment by pascalgrimaud** [comment]
Very good work here @Franceq34 ! A lot of good ideas here
I'll give you feedback very soon

**Comment by pascalgrimaud** [comment]
In fact, all good ideas
Maybe the filter can be changed, as + and - can be confused, but I don't know what to propose

**Comment by deepu105** [comment]
I like the proposed design theme. Some comments and suggestions

1. I'm not a fan of the proposed server/build/client thingy as it assumes static grouping. See below for alternative suggestions
2. I would suggest a wizard like (can be accordions/tabs that are activated one after other) or guided UI where you are promted for project config first followed by server stuff followed by build stuff and so on for example. But for scalability I would recommend the UI being dynamically generated based on an API that dictates what comes first, what holds what options and so on. So ideally an API should provide metadata needed for the UI
3. This can be done by introducing a type param to each configuration at the API level. So a configuration can be a string, boolean, choice or multiple choice. With this type specified, you will be able to construct a dynamic UI just using the API and show string fields for project name and so on, a list or radio button for stuff like maven or gradle and finally a checkbox for stuff like kafka, websocket and so on. On top of this the API can provide field metadata with grouping. Each group will be a step of a wizard. Within each group there will be array of fields. Each field will specify name, type, accepted values (fot options)

**Comment by assimbly** [comment]
First:

- I like the theme and basic setup of Franceq34
- I agree with Deepu to give users a more guided / wizard approach and to make it dynamic to add new options. 

Here my 2 cents about this process: 

In my opinion the configuration/generating of an app is somewhat like the checkout experience of a webshop. Even the slightest friction in the checkout process can drive shoppers away from a site—many never to return. I believe the same applies for the UI of JHL (and why it's so important).

Too have a good experience most checkouts are designed by the following 3 rules:

1. Clear flow
2. Easy form filling 
3. Speed

To achieve this, the process is mostly

1. Broken up in separate steps/sections
2. Provide an outline of the configuration process 
3. Show a summary of the progress
4. Option to revert/go back in the process

For JHipster the process can be 

1. Configure (your project)
2. Choose (your tech)
3. Generate (your app)
5. Run (now) 

The above outline in short terms and hipster terms (= short term plus text in parentheses). I favor a top-down approach to
go through every section. Where the first section is on top and the user (developers) scroll downs to go to the next step 
until it reaches the next step. On the right the user can see the progress.

Just like the Amazon checkout:

![amazon-checkout](https://user-images.githubusercontent.com/35961736/167294568-86631902-58ad-47a7-b278-f85129cb562f.png)


Here on the various sections in detail:


**1. Configure your project**

- Project name (as this the name of configuration, this is what people want to add first, not the path)
- Organization name
- Base name:
- Package name:
- Path: (required) or Path:* (which is more common to required). 

1. In the input fields there can be placeholders / examples. 
2. Give information (infobox) what every field does (what and why is that configuration needed)
3. Let people choose path with a folder chooser. (if folder already contains a configuration file then load this configuration into the UI).
4. If possible generate the package name can be generated from the project/base/organization name.
5. In the future I would expect also here the kind of application (micoservice, microfrontend, web application etc)


**2. Choose your tech**

- The tech tiles (build tool/backend/frontend) below each other
- Make items in the tiles bigger and the various items (i.e. angular, react, vue) below each other
- Use not too much color (if it doesn't add something). Easier for the eye when using for example light blue.

**3. Generate your app **

- Make a section title "Generate"
- Make the tiles exactly the same as the "configuration" tiles/items
- Make button green when generated (succesfully)

**4. Run your app** 

I think (at least when user run JHL locally) users also want to know

- Do I have a runnable app (in Jhipster Classic this is always the case, but with JHL not)
- When I have runable, run the app directly from the UI (and open a new tab) - if technically possible


** Summary **

Like at Amazon there could be a summary side panel. Is configuration complete? What did we generate? Also the download (and run) buttons can be placed here. Make the download (and run) button as separate color (yellow?)

---------------------------

The 0.3 had already some good improvements. I think with a few iterations based on the above ideas JHL UI could be the next level of easy application generation. Note that the above comments are just suggestions, nothing strict to follow.

**Comment by pascalgrimaud** [comment]
I discuss about it with @hdurix during our last JHipster Day, and indeed, I think it's good idea.
Anyway, I don't know the amount of work, specially for the frontend.

**Comment by DamnClin** [comment]
The API generation and documentation from an implicit bean graph (making it explicit with inheritance is not a good idea IMHO) afraid me more than the frontend part (but I may be wrong).

There is, indeed, some work to achieve this but I really think the current interface mechanism is too fragile and that this is worth it to ease upcoming contributions.

I think this is a good time to start this since there are enough modules to find the limitations of the designs.

If you agree with the main idea I can try to bootstrap something "soon" (I'll need help to make the full thing real)

**Comment by pascalgrimaud** [comment]
> I really think the current interface mechanism is too fragile

Totally agree, and that's why this ticket was created :-)

**Comment by deepu105** [comment]
I would suggest to design the metadata API first and UX after that to save
time. Once you have a solid API it would be easier to decide on UI/UX

**Comment by DamnClin** [comment]
The module mechanism is making it's way \o/ we now have automatic APIs: https://github.com/jhipster/jhipster-lite/pull/2036 and a very simple module list screen https://github.com/jhipster/jhipster-lite/pull/2055 the next step will be to be able to apply modules using the UI.

But, I'm not sure how to do this, here are the constraints to keep in mind:
* All module needs at least 1 parameter: the project folder;
* They have specific parameters (string, integers or boolean), mandatory or not;
* We need to be able to apply multiple modules keeping the previously entered parameters (or it will be a nightmare).

I started (and trash) a module form screen working on it's own, it was looking like that: 

![moduleForm](https://user-images.githubusercontent.com/59929679/173292516-62b2f89c-cec0-4820-b0e8-122555bea783.png)

I trashed it because having a dedicated screen to apply modules in just a nightmare!

I have some ideas like keeping the side form @Franceq34 show but the fields in this forms needs to be dynamic so that mean different actions on lines: 

* When you have all properties set you can just apply the module;
* When properties are missing you first need to click to fill the form and you'll then be able to apply.

BUT this sucks because of not mandatory properties, this is where I ran out of ideas :D. Don't hesitate to tell if this is not clear (because for me it is :D)

**Comment by Gnuk** [comment]
I'll make a proposal later in the morning from discussions with @DamnClin .

**Comment by Gnuk** [comment]
![modules](https://user-images.githubusercontent.com/1397032/173321641-c8e5f36c-66e5-4293-9935-181707634d5d.png)

Here is the idea when you select a module.

On the left side you have all the properties relatives to the module.

On the module, you know if all the properties are set and how many optional properties are available.

The apply button is not enabled until all mandatory properties are filled.

An "optional" indication is added to a field on the left side to know it's optional.

**Comment by pascalgrimaud** [comment]
Good point @Gnuk 
Additional idea would be an option to ignore all checks and make all 'apply' buttons available

**Comment by Franceq34** [comment]
I really like the idea of this front generated from API.
I wonder what is the best strategy to make the transition from the current design to this one.

Regarding the mockup of @Gnuk, I like the structure of the page. 
I have some questions about it :
Correct me i I'm wrong, but "Category" is -> Maven Gradle, Angular, Vue ... and "Module" are the direct calls to APIs ?
- Maybe it needs Categories and Sub-categories ?
- If you fill for example lineBreak for module 1 and module has a lineBreak, will it be "auto-filled" ?
- It could also be great to know what is the default value if an optional is not filled.
- I think it needs a download button

**Comment by DamnClin** [comment]
> I wonder what is the best strategy to make the transition from the current design to this one.

For me the migration strategy is the one we started: the page exists on a path (for now /modules), we update the page && the modules until we are happy with that and switch it to the main page.

> Maybe it needs Categories and Sub-categories ?

I don't think so, I think we need tags and a search / filter on this page

> If you fill for example lineBreak for module 1 and module has a lineBreak, will it be "auto-filled" ?

Yes, that's the whole point of that :)

**Comment by DamnClin** [comment]
https://github.com/jhipster/jhipster-lite/pull/2325 was the last think we discussed with @Gnuk. I see, at least those UX tickets on that screen: 

* https://github.com/jhipster/jhipster-lite/issues/2251
* https://github.com/jhipster/jhipster-lite/issues/2250
* https://github.com/jhipster/jhipster-lite/issues/2319

But what do you think for this peculiar ticket lifecycle?

PS: Yep, the current UI really is ugly, I can't make any beautiful screen no matter how hard I try :D

**Comment by assimbly** [comment]
"PS: Yep, the current UI really is ugly, I can't make any beautiful screen no matter how hard I try :D"

Ha, you made me laugh with that comment :). I am sure though that with every try things will improve over time. Keep up the great work!

**Comment by pascalgrimaud** [comment]
Just a check point. Here the current module page:

![image](https://user-images.githubusercontent.com/9156882/179469902-9e039364-ee0b-4989-985a-8b3d639190ca.png)

**Comment by DamnClin** [comment]
On this patch page I see at least 2 missing buttons: 

* Download
* Format & Download

That are needed for the deployed version.

Then, there will be the other page discussed here https://github.com/jhipster/jhipster-lite/discussions/2671

**Comment by DamnClin** [comment]
Did some update in https://github.com/jhipster/jhipster-lite/pull/2751, still ugly (dunno if it's more or less...) but some new feature should make it more usable

**Comment by DamnClin** [comment]
@pascalgrimaud @Franceq34  what do you think, it is good enough, we close this one for now?

**Comment by pascalgrimaud** [comment]
Yes we can close it I think.
Let's open smaller tickets for improving the CSS and design

**Comment by pascalgrimaud** [comment]
Adding a bounty on this ticket.
As you did the main work on this, plz claim it @DamnClin

**Comment by DamnClin** [comment]
Claimed $300 on this https://opencollective.com/generator-jhipster/expenses/88312

**Comment by pascalgrimaud** [comment]
@DamnClin : approved - so I suppose the other part will be for @Gnuk !

**Comment by Gnuk** [comment]
Claimed $200 on this https://opencollective.com/generator-jhipster/expenses/88313

**Comment by pascalgrimaud** [comment]
@Gnuk : approved

Thanks for your work here !

**Comment by Franceq34** [comment]
Really nice work that have been done here congrats !
