### ISSUE TITLE
Frontend: Add an AlertBus

### ISSUE THREAD

**Issue by Franceq34** [jhipster/jhipster-lite#1592]
**Statement :**
We have multiple messages that transit in the application.
When calling "add Angular" for example : 

![Capture d’écran de 2022-05-05 11-00-22](https://user-images.githubusercontent.com/24738688/166892560-2ff37ec5-c867-4442-9744-c4fe98c0f42b.png)

You can notice we are calling the Logger, the toaster service, and we can imagine other options in the future.

The idea of the ticket is to create an AlertBus in the secondary that would **emit** events such as success, error or information events.

This Bus will be subscribed by the Logger and and the ToastService.

Doing so, we will also be removing this primary dependency in secondary : 

![Capture d’écran de 2022-05-05 11-05-28](https://user-images.githubusercontent.com/24738688/166893274-8afe8d51-4921-4884-b286-ceb3d29ec94e.png)

What do you think about it ? @nonomoho @seraphinandrieux

**Comment by pascalgrimaud** [comment]
Ok then, looks good so let's do it

**Comment by Franceq34** [comment]
WIP :)
