### ISSUE TITLE
CI: status-check with skip ci message

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1627]
When using [skip ci] in commit message, the status-check job is pending, so only admin can merged, so it's a problem:

![image](https://user-images.githubusercontent.com/9156882/167247081-657ff5d7-3bc0-495c-a417-3973daa6282f.png)

**Comment by pascalgrimaud** [comment]
@renanfranca : I changed your role as admin of this repo, you should be able to access to it

**Comment by renanfranca** [comment]
@pascalgrimaud : I discovered that the words `[skip ci]` and `[ci skip]` are used by github action to skip all jobs by default. That's why the status-check wasn't executed. The message that requires admin's roles to merge is always there and fades away after the pipeline starts.

The variable `github.event.head_commit.message` return an empty string when executed at a pull request.

I am going to create a pull request to implement the feature that skips the ci, is that ok? I tried the word [not ci] and it is not reserved, feel free to suggest a better one 😃👍

**Comment by pascalgrimaud** [comment]
mhh I see. Can't we force to run the status-check even if the words contain `[skip ci]` or `[ci skip]` ?

**Comment by renanfranca** [comment]
> mhh I see. Can't we force to run the status-check even if the words contain `[skip ci]` or `[ci skip]` ?

I changed  status-checks implementation without any conditions and without "needs". Tested without the `[skip ci]` or `[ci skip]` and it runs... with `[skip ci]` or `[ci skip]` it didn't run and any jobs. When using `[skip ci]` or `[ci skip]` no entrance appears at Actions.

https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

**Comment by renanfranca** [comment]
After some research, I realized that if the workflow is trigger by push or pull_request or using branch filtering like it is today:

```yml
name: build
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
```
There isn't a way to avoid the default behavior of skipping complete the overflow and letting the status-checks pending when using the tags: 
```
[skip ci]
[ci skip]
[no ci]
[skip actions]
[actions skip]
```

Here are some references:

> You won't be able to merge the pull request if your repository is configured to require specific checks to pass first. To allow the pull request to be merged you can push a new commit to the pull request without the skip instruction in the commit message.

source: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs


> [Handling skipped but required checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks)
> Warning: If a workflow is skipped due to [path filtering](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore), [branch filtering](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore) or a [commit message](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs), then checks associated with that workflow will remain in a "Pending" state. A pull request that requires those checks to be successful will be blocked from merging.

> For this reason you should not use path or branch filtering to skip workflow runs if the workflow is required. For more information, see "[Skipping workflow runs](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs)" and "[Required workflows](https://docs.github.com/en/actions/using-workflows/required-workflows)."

> If, however, a job within a workflow is skipped due to a conditional, it will report its status as "Success". For more information, see "[Using conditions to control job execution](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution)."

source: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks 

There is a possibility of using pull_request_target to trigger the workflow, but can't use branch filtering. I tried that path but I couldn't make it work. Although pull_request_target brings security concerns:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

For now, I implement a solution that uses different tags that don't trigger the default behavior of skipping completely the workflow and run the status-checks:
- https://github.com/jhipster/jhipster-lite/pull/8741

**Comment by pascalgrimaud** [comment]
@renanfranca : is it done? can it be closed?

**Comment by renanfranca** [comment]
@pascalgrimaud : It's done ✔️.  I will close it now.
