### ISSUE TITLE
CI: start and test the generated applications

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1649]
If it's only backend:
- test health check

If there is a front:
- maybe cypress ?

**Comment by seraphinandrieux** [comment]
I never worked on CI before.
This ticket could be a good begining.
If someone else really wants to do it go for it.
If not, I would like try to do it :)

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's important to have this, to keep the quality

**Comment by pascalgrimaud** [comment]
Do you plan to work on this @seraphinandrieux ?
Otherwise, I'll take it as it looks important to have this, to reduce the possible bugs when starting the app

**Comment by pascalgrimaud** [comment]
I'm starting this one, as it's really needed

**Comment by pascalgrimaud** [comment]
bounty claimed: https://opencollective.com/generator-jhipster/expenses/99050
cc @DanielFran :)

**Comment by DanielFran** [comment]
@pascalgrimaud Approved
