### ISSUE TITLE
Angular: health page

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1652]
After generating Angular as client, it could be nice to have the possibility to generate health page:

- entry in menu
- health html
- health component
- health service
- health tests

SImilar to:
![image](https://user-images.githubusercontent.com/9156882/167257792-7b6a661a-1b21-4ce9-a1c9-d4634385f357.png)

**Comment by qmonmert** [comment]
@pascalgrimaud I don't understand why on JHLite, I have:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/9989211/168442058-48dfa59f-75cc-4e21-a943-e2cc1f1930ab.png">
<img width="351" alt="image" src="https://user-images.githubusercontent.com/9989211/168442069-57e0241e-2dc9-4a9f-b2a9-6341600819e7.png">

whereas on Generator:
<img width="464" alt="image" src="https://user-images.githubusercontent.com/9989211/168442086-a81f3b74-e5bb-48a3-9533-0329eb944056.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/9989211/168442100-828b3d91-196c-497a-b142-0a554c5fcba3.png">
(I have property `components`). An idea?

**Comment by pascalgrimaud** [comment]
@qmonmert : I edit your pull request to keep this opened.

Can you add the front part to generate the health check plz? Then, we can close this one after that :)

![image](https://user-images.githubusercontent.com/9156882/173880005-056fd0fe-a753-441d-ac90-a13259b396f7.png)

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/82559 :)

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
