### ISSUE TITLE
Ease new module creation by structuring modules as a tree

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#1666]
Most of current modules have a parent -> child relationship (with some modules being root). The idea would be to enforce that with an interface to define a new module, here's a very incomplete idea:

```java
public interface JHipsterModule {
  ModuleKey key();
  ModuleKey parent();
}

public interface ModuleKey {
  String get();
}

public class RootKey implements ModuleKey {
  public String get() {
    return "root";
  }
}
```

This enforced parent -> child relationship will allow us to define a dependencies tree between modules those allowing: 
* Automatic HATEOAS API generation;
* Generic (no new code for a new module) JHipster Lite front end part using the HATEOAS API (we'll need some form definition mechanism for that).

I think this can be a great facilitator to create new modules!

**Comment by pascalgrimaud** [comment]
It should not be mandatory @antarus 

Supposing I created a new project, using my personal starter, I'd like to add PostgreSQL, without the requirement to use init, maven, java base.

That's why I think building a tree can help but should not be mandatory. Each developer should know what he/she adds to the project when using each feature of JHLite

**Comment by antarus** [comment]
@pascalgrimaud I completely agree that it shouldn't be mandatory. 
But jhipster-lite needs to be clearer on what a module needs and maybe what it will add/modify.
For example, I had to switch to debug mode to see the error and determine the files that were missing to add the oauth2. Then I had to look for the modules which added its files.

To be studied, but I think that with the new module system, we can maintain a list of files that each module adds / modifies. This could provide solutions to errors related to missing files for example.

**Comment by pascalgrimaud** [comment]
I'm adding a bounty on this as it's important to ease the use of module

**Comment by DamnClin** [comment]
I think this is covered by https://github.com/jhipster/jhipster-lite/pull/3022

**Comment by hdurix** [comment]
I also think so. We can close this issue. Don't forget the bounty @DamnClin.

**Comment by DamnClin** [comment]
Claimed https://opencollective.com/generator-jhipster/expenses/91032
