### ISSUE TITLE
Allow user to create Merge request on github repository

### ISSUE THREAD

**Issue by matthieuRioual** [jhipster/jhipster-lite#1669]
The idea would be to allow authenticated user to be able to create merge request on a repository.

The authentification could be done like on jhipster-online with Oauth2  and store token ever in a DB or in the storage.
For creating merge request, we could use Github API for java.

**Comment by matthieulapatate** [comment]
Just wondering if i should create a new context or simply use init one for instance.

**Comment by pascalgrimaud** [comment]
It's for managing project, so it's in Project context:
- project/domain -> something like Cloud
- project/infra/sec -> CloudRepository

I don't have better name, need to think more, but it could be a start
