### ISSUE TITLE
Refactoring: Spring Boot JWT

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1688]
Following discussion with @DamnClin 

The current Spring Boot + JWT option is simply a c/c of existing code from generator-jhipster
This part can be improved to respect better hexagonal architecture concept

Cc @hdurix so you can follow the work here too

**Comment by DamnClin** [comment]
I think we can close this one as it is covered by https://github.com/jhipster/jhipster-lite/issues/2481
