### ISSUE TITLE
Refactoring: Spring Boot OAuth2

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1689]
Following discussion with @DamnClin 

The current Spring Boot + OAuth2 option is simply a c/c of existing code from generator-jhipster
This part can be improved to respect better hexagonal architecture concept

Cc @hdurix so you can follow the work here too

**Comment by DamnClin** [comment]
I can take this since we've done this refactoring. We'll take some time to battle test and contribute the templates here
