### ISSUE TITLE
Feature: Cucumber

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1699]
The goal is to add Cucumber support: https://cucumber.io/

Some links which can help:

- https://blog.ippon.fr/2020/08/31/cucumber-et-resttemplate/
- https://gitlab.com/nerp-ippon/nerp/-/tree/main/webservices/src/test/java/com/ippon/nerp/cucumber

**Comment by DamnClin** [comment]
I have some improved version of this, I'll take it :)

**Comment by DamnClin** [comment]
Just a little update: we have done the Cucumber integration with fluent assertion API on a dedicated project. We'll take some time to battle test it on the project and we'll then work on the templating

**Comment by pascalgrimaud** [comment]
Good news! Thanks a lot @DamnClin

**Comment by DamnClin** [comment]
Normally https://github.com/jhipster/jhipster-lite/pull/1859 should be he last prerequisite for that, will try to do it when merged

**Comment by DamnClin** [comment]
Hum, I was wrong... Need to add a new annotation in the hexagonal architecture this have other prerequisites... we'll be back on this one after

**Comment by pascalgrimaud** [comment]
Don't forget to claim the bounty @DamnClin and put the link of opencollective here, in comments :)

**Comment by DamnClin** [comment]
https://opencollective.com/generator-jhipster/expenses/79244

**Comment by pascalgrimaud** [comment]
@DamnClin : approved
