### ISSUE TITLE
Add front modules acces from tests

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#1732]
In the current version when you generate a vue.js front end (an perhaps any other front end) VisualStudio Code don't see main sources from test source (which is very bad for the Dev experience).

I ended up updating `tsconfig.json` to have: 

```
  "include": [
    "src/test/**/*.ts",
    "src/main/webapp/**/*.ts",
    "src/main/webapp/**/*.d.ts",
    "src/main/webapp/**/*.tsx",
    "src/main/webapp/**/*.vue"
  ],
```

I also created a `tsconfig-build.json` with:

```
{
    "extends": "./tsconfig.json",
    "exclude": [
        "src/test/**/*.ts"
    ]
}
```

And updated the build target (in `package.json`) to: 

```
"build": "vue-tsc -p tsconfig-build.json --noEmit && vite build --emptyOutDir",
```

This looks OK but I don't want to contribute that directly since I'm really bad on those part and not sure that's a good way to handle this!

**Comment by pascalgrimaud** [comment]
Cc @seraphinandrieux @Franceq34 @nonomoho : what do you think about that?

**Comment by hdurix** [comment]
I'm not sure we can do better than this solution, especially as JS tests are not in the expected default folder (`<root-dir>/tests`)

**Comment by hdurix** [comment]
I'm stealing this from you @DamnClin to do the generated apps part
