### ISSUE TITLE
Default values for REST API

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-lite#1734]
In most API POST endpoints, you need to provide the `generator-jhipster` info (baseName, packageName, etc...)
Basically you need to provide the structure
```json
{
  "folder": "/tmp/jhlite/jhipster",
  "generator-jhipster": {
    "baseName": "jhipster",
    "projectName": "jhipster project",
    "packageName": "com.mycompany.myapp",
    "serverPort": 8080
  }
}
```
It would be nice if the `generator-jhipster` structure were automatically filled from the info found at `folder` path so you just need to provide
```json
{
  "folder": "/tmp/jhlite/jhipster"
}

**Comment by pascalgrimaud** [comment]
I'll have a look because, there is already default value so your use case should work

**Comment by DamnClin** [comment]
I think this can be close since this problem don't exist with modules

**Comment by pascalgrimaud** [comment]
Closing this, following the previous comment
