### ISSUE TITLE
Add Redis as a new key-value NoSQL database option

### ISSUE THREAD

**Issue by fdelbrayelle** [jhipster/jhipster-lite#1779]
Add Redis as a key-value database option first next to MongoDB in the NoSQL options.

The idea is to add just the dependency and basic configuration to let users/developers add what they need from there.

And in another PR add the option to use it as a cache provider.

And maybe in another one, the option to use it as a message broker next to Apache Kafka.

**Comment by pascalgrimaud** [comment]
Increasing the bounty to motivate people as it's a good feature to have

**Comment by frascu** [comment]
I can work on this issue. Could you assign me?
