### ISSUE TITLE
Handle java dependencies in the new module mechanism

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#1787]
We started the modules mechanism (https://github.com/jhipster/jhipster-lite/issues/1768) with just context and files, we now need to handle java dependencies, here's an API idea: 

```
JHipsterDependency optionalTestPom = dependency()
    .groupId("group.id")
    .artifactId("artifact-id")
    .versionSlug("version-slug")
    .optional()
    .scope(DependencyScope.TEST)
    .type(DependencyType.POM)
    .build()

moduleForProject(new JHipsterProjectFolder(FileUtils.tmpDirForTest()))
.javaDependencies()
  .add(optionalTestPom)
  .add(groupId("org.springframework.boot"), artifactId("spring-boot"))
  .add(groupId("org.springframework.cloud"), artifactId("spring-cloud-dependencies"), versionSlug("spring-cloud"))
  .and()
.build()
```

This give us 3 ways of adding a dependency:

* A way with all available options (and a builder);
* A way to add dependencies without versions (just group id and artifact id);
* A way to add group id, artifact id and version slug.

The version slug is used to get the version from `src/main/resources/generator/dependencies/pom.xml` to keep the current update behavior but reduce the complexity for module creators

**Comment by pascalgrimaud** [comment]
adding a bounty on this ticket:
- it's a lot of work
- it will manage add / update dependencies, to this part is awesome

**Comment by DamnClin** [comment]
Bounty claim: https://opencollective.com/generator-jhipster/expenses/79245

**Comment by pascalgrimaud** [comment]
@DamnClin : approved
