### ISSUE TITLE
Add Spring properties management in modules

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#1868]
Add the possibility to manage spring properties in modules. API ideas:

```
moduleForProject(...)
    .springProperties()
      .set("springdoc.swagger-ui.operationsSorter", "alpha")
      .and()
    .context()
    // ...
```

Totally handling this one is looks challenging! We need to handle: 

* .properties and .yml files
* Existing properties update
* New properties
* Decent new key position in files

**Comment by pascalgrimaud** [comment]
At the beginning, I chose properties as it's simpler to manage, it's easy to find and replace the needle

About yml, we could use SnakeYAML, but maybe it's a lot of effort. And adding support for both type of file: properties and yml will be overkill.

So for now, I'd follow https://start.spring.io/ as it generates application.properties

**Comment by DamnClin** [comment]
Ok, I'll try to make a PR for that in the next days
