### ISSUE TITLE
Module: xml version header removed

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1878]
This part xml version header is removed when using module system:

![image](https://user-images.githubusercontent.com/9156882/170858734-36e282dc-d301-4778-a8a6-b7b01f27b082.png)

**Comment by DamnClin** [comment]
Of course I'll take this one!

I'm not sure what to do, do we force this header or do we try to keep the existing ones?

**Comment by pascalgrimaud** [comment]
We can try to force this header, using UTF8
