### ISSUE TITLE
Improvement: useless spaces and line break in module pom.xml management

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#1879]
`pom.xml` management in module add some useless trailing spaces and leave some blank lines after dependency removal.

Step to reproduce: build an app using the cucumber module (or any other other module updating dependencies) and check the generated `pom.xml`

**Comment by MSaguer** [comment]
After `pom.xml` generated by fullapp tests-ci, I see the following issues
- trailing spaces generated on version properties
![image](https://user-images.githubusercontent.com/42449441/171492558-916dc8a5-c284-44c7-a639-493b2914eb34.png)
- unexpected empty lines in dependency block
![image](https://user-images.githubusercontent.com/42449441/171492745-1bf2fe3f-fd33-45bb-849b-f148db4e1c1b.png)

Is that all you have seen?

**Comment by DamnClin** [comment]
The trailling spaces are un-intended. The line break between dependencies is totally intended and easy to remove if we want to (the trailling spaces may not be).

There is another tricky problem when deleting a dependency (this happen, for example when you increase scope, ex: test -> compile). In that case, if there was line break before and after the dependency they will remain.

But, considering your saying: "unexpected empty lines in dependency block" I was probably wrong to add those line break and removing them all along may solve the dependency removal problem (in most cases since the problem just won't be there anymore)!

I don't known, to be honest I haven't spent time on this since prettier is fixing it it's ugly but not blocking :D. I'm trying to have some feedback on this feature since the behavior really change from actual one and I'm not that confident that it will work as intended in all cases (since I don't know them :D).
