### ISSUE TITLE
Update readme when a module is execute

### ISSUE THREAD

**Issue by antarus** [jhipster/jhipster-lite#1933]
When adding an option it might be good to update the readme on how to configure/use it.
For example when adding a database, it might be good to add the command to use to launch the docker-compose.

**Comment by pascalgrimaud** [comment]
Agree, the ReadmeService has been created, and needed to be called to add text in README for each option

**Comment by DamnClin** [comment]
What I did for the cucumber was was to create a dedicated documentation in /documentation/cucumber.md. The goal is that it will be easier to update.

I'm not a fan of updating the readme if we want to keep the possibility to start JHLite on a project not generated with JHLite...

We can also build something that will: 
* Update the readme with the given file content if we find a needle;
* Put the file content in documentation if we can't find it.

This way it'll work in all cases. I can add it to the module mechanism if you want

**Comment by pascalgrimaud** [comment]
Another idea would be:
- in README, we can put a link to documentation/xxxx.md
- and add a specific and dedicated documentation/xxxx.md, according to the module

**Comment by antarus** [comment]
I did an implementation for postgresql but I think a mix of your ideas would be ideal. 
In addition, it would limit my problem of separation between documentation for development and configuration in the readme. 
All the documentation for the module would be in one place.

**Comment by DamnClin** [comment]
I created https://github.com/jhipster/jhipster-lite/issues/1952 that will help to achieve this. Dunno when but I'm gonna do an implementation for this optional replacement thing :)

**Comment by DamnClin** [comment]
I ended up doing this https://github.com/jhipster/jhipster-lite/pull/1955 once this is merged the module documentation feature should be easier to do. @antarus you are working on it or I add it to the modules mechanism?

**Comment by antarus** [comment]
You can add it. i can use your work after ;)

**Comment by DamnClin** [comment]
I ended up adding it here https://github.com/jhipster/jhipster-lite/pull/1955

**Comment by antarus** [comment]
@DamnClin 
I started looking to refactor the postgresql generator with the new module system. I think it lacks the management of docker images or does it use the current DockerApplicationService service? 
Sorry, I'm starting with the hexagonal architecture and DDD in general and I wonder if the docker generator should not be included in the module system :D

**Comment by DamnClin** [comment]
I may be wrong (just took 3mn to check that) but I don't think there is a need for a specific docker management in module since module is not doing anything special with docker file or the likes. I think you can rely on the existing service to get the version and do the update you want on files. Am I missing something there?

**Comment by antarus** [comment]
Ok I will look at how to use the existing service with the new module system. Docker files can be managed via the module's template system too.  
Thank you
