### ISSUE TITLE
Upgrade to Angular 14

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#1948]

**Comment by qmonmert** [comment]
we need to wait a new release of https://www.npmjs.com/package/@angular-builders/jest

**Comment by pascalgrimaud** [comment]
Adding a bounty to this migration

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/82196 😉

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
