### ISSUE TITLE
Module: Handle spring yaml

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#1956]
Following https://github.com/jhipster/jhipster-lite/pull/1953 we'll need to add yml spring properties management

**Comment by swarajsaaj** [comment]
Do you want to use yaml for all generated properties files (`application.yml` and `bootstrap.yml`) instead of `application.properties` ? or use both somehow giving an option?

**Comment by DamnClin** [comment]
Depends :⁠-⁠). Give option for init but stick to existing if the file is here. I also want to keep formatting.

In fact, I really want to do it and, since I'm starting to finally feel better (less sick) I'll probably be able to take that soon :⁠-⁠)

**Comment by swarajsaaj** [comment]
Great :) in that case wish you get well soon and take it up when you feel like👍

**Comment by murdos** [comment]
FYI I intend to work on this feature, since I think it would be a nice feature to have :)

**Comment by murdos** [comment]
@pascalgrimaud : I propose to consider this ticket as done as an initial limited state with the work done with the 4 PR mentioned above, and released in version 0.47. 
And follow continued effort with #7939.
WDYT?

**Comment by pascalgrimaud** [comment]
Agree @murdos

**Comment by murdos** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/174931
