### ISSUE TITLE
Spring Boot MVC: add Spring Boot Actuator

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#198]
New API with this

**Comment by swarajsaaj** [comment]
Should it be in "mvc" context instead? Do you feel any use of actuator without a web dependency?

**Comment by pascalgrimaud** [comment]
Indeed @swarajsaaj you're right, about putting this in MVC

But I don't think actuator should be added by default, so it should be optional, do you agree?

**Comment by swarajsaaj** [comment]
@pascalgrimaud  Yes I agree with a separate API for adding actuator in MVC resource with:-
- Basic endpoints in application properties
- Core health probes
- Keep it under "/management" to match generator-jhipster path
- And core metrics

**Comment by pascalgrimaud** [comment]
sound perfect. Can I assign to you this ticket ?

**Comment by swarajsaaj** [comment]
Yes please :)

**Comment by swarajsaaj** [comment]
There is a conflict with springfox+actuator and `spring.mvc.pathmatch.matching-strategy` property already added at https://github.com/jhipster/jhipster-lite/blob/8d4c8bc555232f74046afcaa899a216ab5920b34/src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcDomainService.java#L118.

Spring actuator's path matching strategy cannot be configured to `AntPathMatcher` by properties.
Ref:- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#pathpattern-based-path-matching-strategy-for-spring-mvc

Are we already planning to replace springfox with springdoc in #219 ? Shall we remove this property in this ticket if we are not going to depend on springfox?

**Comment by pascalgrimaud** [comment]
Oh I see: it's because I added springfox by default when adding Tomcat MVC or Undertow MVC.
I shouldn't do that:
- so springfox should be removed from MVC
- adding springdoc could be done separately, or maybe should be by default with MVC, I don't' know

**Comment by pascalgrimaud** [comment]
We could remove first springfox in a 1st PR, then you can continue the work for this ticket separately. What do you think?

**Comment by pascalgrimaud** [comment]
We could remove first springfox in a 1st PR, then you can continue the work for this ticket separately. What do you think?

**Comment by swarajsaaj** [comment]
Sure, Looks good 👍

**Comment by pascalgrimaud** [comment]
@swarajsaaj : I'm doing the PR for removing springfox. I'll submit it in few minutes
