### ISSUE TITLE
optionalReplacement duplicate data when execute several times

### ISSUE THREAD

**Issue by antarus** [jhipster/jhipster-lite#2015]
When a module that uses the documentation or optionalReplacement methods is executed several times, the lines are duplicated in the modified files. 

This is not very problematic because it should only happen in the development phase.

**Comment by DamnClin** [comment]
In fact we can't do anything about that without taking the risk to have a very bad impact on files in afraid!

**Comment by antarus** [comment]
I'm ok with you.
We could just search for the added string before doing the replacement, but that will impact performance and potentially prevent the string from being added to the file if another legitimate reference exists in that file.

Or we prevent the execution of module already applied? with force option but on the rest/web side, it will not be easy to manage..

**Comment by DamnClin** [comment]
@pascalgrimaud what do you think, we ignore replacements if the target if already there?

**Comment by pascalgrimaud** [comment]
I don't care too much as it can be updated easily by the user, after applying the feature a 2nd time

**Comment by DamnClin** [comment]
Arf, can't find it but it was fixed in https://github.com/jhipster/jhipster-lite/pull/2625

**Comment by pascalgrimaud** [comment]
So it can be closed I think
