### ISSUE TITLE
Backend error handling

### ISSUE THREAD

**Issue by antarus** [jhipster/jhipster-lite#2075]
With the current version of main, there are huge errors on the back when typing /tmp/test as Path on the screen

It's not very reassuring :D

Errors should be handled better.

Raised an error of package.json and application.properties not found when we haven't initialized a single module should not have arrived

Edit: Seems to be related to the API call `api/project/details?folder=%2Ftmp`

**Comment by pascalgrimaud** [comment]
yes we can catch it and display a better log

**Comment by antarus** [comment]
I've used this system before in an application and it's cool.

It could even be a new module :D

**Comment by DamnClin** [comment]
This specific error is fixed in https://github.com/jhipster/jhipster-lite/issues/2075, I create an issue for an internationalized errors mechanism
