### ISSUE TITLE
Spring Boot core: add default logback to Spring Boot

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#209]
Should be included by default when adding spring boot

Need one for src/main and one for src/test

Need to add method to allow adding new entry

**Comment by swarajsaaj** [comment]
Hi @pascalgrimaud 
what is meant by "Need to add method to allow adding new entry", does it mean adding a new appender dynamically or just the method to add these logback files separately?

**Comment by pascalgrimaud** [comment]
2 solutions for this ticket, we can discuss:


### 1st solution :

- [spring boot core](https://github.com/jhipster/jhipster-lite/tree/main/src/main/java/tech/jhipster/lite/generator/server/springboot/core) : it should generate a new file `logback.xml` which should be as minimal as possible with a needle

- add a new context, similar to [properties](https://github.com/jhipster/jhipster-lite/tree/main/src/main/java/tech/jhipster/lite/generator/server/springboot/properties) with some methods to allow adding new entry. This context should be annotated with SharedKernel, so other contexts can accessed to it

### 2nd solution :

- [spring boot core](https://github.com/jhipster/jhipster-lite/tree/main/src/main/java/tech/jhipster/lite/generator/server/springboot/core) : it should generate a new file `logback.xml`. This file can be improved when needed by other features.

The problem with this solution is: with minimal spring boot project, there can be a lot of useless entries, poluted by other features

**Comment by swarajsaaj** [comment]
I would agree with the 1st solution, as its more in-line with the overall architecture, and ofcourse would be shared with business-contexts, and can be enhanced whenever a new functionality is added.

In 2nd solution, it would either have a lot of unwanted content or may end with too many conditionals in future. (Neither of them seems desirable). 

If some contexts need custom appenders too (for e.g. `ApplicationInsightsAppender`) for any specific cloud feature it won't be possible in 2nd option without conditionals in template, but better with a needle/shared-context in 1st option

**Comment by pascalgrimaud** [comment]
so let's choose the 1st solution :)
