### ISSUE TITLE
Add tags to modules

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2101]
Sooner or later we'll need a tag mechansim for modules, adding it asap will ease migration of existing modules (and it's pretty straightforward to do :D)

**Comment by antarus** [comment]
Tags would be mandatory? If si, the sooner the better

**Comment by DamnClin** [comment]
Hum I don't know, it may be a good idea to set them as mandatory

**Comment by antarus** [comment]
Ok i can do a try after work

**Comment by DamnClin** [comment]
Great! I won't be available to help today but I may be tomorrow evening if needed
