### ISSUE TITLE
Add the possibility to comment spring properties in modules

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2106]
Sometimes it's usefull to add some comments in spring properties, the API can be:

```
.springMainProperties()
  .comment(propertyKey("springdoc.swagger-ui.operationsSorter"), comment("This is a comment"))
  .set(propertyKey("springdoc.swagger-ui.operationsSorter"), propertyValue("alpha"))
```

This will add a comment before the given property key

**Comment by DamnClin** [comment]
Hum, I'm really not sure this is a good first issue, designing this may be challenging! (we have to stay yaml friendly)

**Comment by pascalgrimaud** [comment]
ahaha ok, 'good first issue' removed

**Comment by pascalgrimaud** [comment]
Adding a bounty as I'd like to have this

**Comment by pascalgrimaud** [comment]
Increasing the bounty, following the amount of work and time spent on this

**Comment by renanfranca** [comment]
> Increasing the bounty, following the amount of work and time spent on this

Thanks @pascalgrimaud 💪❤️😃!
