### ISSUE TITLE
Convert ApiDoc to module

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2108]
Convert ApiDoc (src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdoc) to module (this is a good first issue)

**Comment by pascalgrimaud** [comment]
cc @Bolo89 : do you want to do this part, as you did the 1st version?

**Comment by Bolo89** [comment]
@pascalgrimaud Yes, you can assign me all ticket linked to my dev
