### ISSUE TITLE
Convert Consul to module

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2115]
Convert consul (src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/consul) to module (this is a good first issue)

**Comment by pascalgrimaud** [comment]
I'm taking this one
hope I'll find time to start to work back on JHipster Lite, as the last weeks, I didn't manage to do it

**Comment by DamnClin** [comment]
Ok, I'm doing https://github.com/jhipster/jhipster-lite/issues/2116 right now, you'll have a lot to get from this one I think :D
