### ISSUE TITLE
Convert MSSQL to module

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2119]
Convert MSSQL (src/main/java/tech/jhipster/lite/generator/server/springboot/database/mssql) to module (this is a good first issue)

**Comment by pascalgrimaud** [comment]
cc @seraphinandrieux as you did it recently :p

**Comment by seraphinandrieux** [comment]
I take it in charge

**Comment by DanielFran** [comment]
@seraphinandrieux Did you start something? I have some time, and I can take care of it...
