### ISSUE TITLE
Front: add Setup section

### ISSUE THREAD

**Issue by marioneyraud** [jhipster/jhipster-lite#2147]
add setup section below Initialization

**Comment by pascalgrimaud** [comment]
it's for putting:
- github actions button
- later: gitlab ci
- probably move codespaces and gitpod there too

**Comment by pascalgrimaud** [comment]
Adding a bounty for this one and all the work done for:

![image](https://user-images.githubusercontent.com/9156882/174332677-ffde5211-3fb4-48cb-862b-927416c17c56.png)
