### ISSUE TITLE
Add plugin management to module system 

### ISSUE THREAD

**Issue by antarus** [jhipster/jhipster-lite#2177]
Add plugin management to module system as was done for java dependencies, properties etc

This will refactor modules adding plugins.

EDIT: need for migrate frontendmaven, javatool-arch, sonar, springboot-core, springboot-docker module

**Comment by DamnClin** [comment]
You mean maven plugins? If so I think we have to accept that it will be different for maven and graddle (dependencies can use the same mechanism)

**Comment by antarus** [comment]
Yes I am talking about maven plugins.
but it seems to me that graddle also has also a plugins system? no?

**Comment by antarus** [comment]
For maven plugins we need:
- groupid
- artifactid
- version
- execution definition
- configuration definition


gradle:
- groupid
- artifactid
- version
- ???
