### ISSUE TITLE
Add java dependency management in module system

### ISSUE THREAD

**Issue by antarus** [jhipster/jhipster-lite#2179]
Add the possibility to manage dependency management in the module system.
manage `<dependencyManagement>` in pom.xml

(need for migrate springcloud sub modules)

**Comment by DamnClin** [comment]
For this one I was thinking to add POM in `JavaDependencyScope` and put them in dependency management but I need to RTFM to ensure that it is a good way to do that :D

**Comment by DamnClin** [comment]
I started something for that. Can't end it right now but hopefully soon enough :D. Can you affect me on this one please?

**Comment by pascalgrimaud** [comment]
Thanks @DamnClin
