### ISSUE TITLE
Spring Boot Web: add swagger with springdoc

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#219]
The goal here is to have swagger page, to test the different API.

To achieve this:

### In Domain :

1) add this property

```
<springdoc-openapi-ui.version>1.5.12</springdoc-openapi-ui.version>
```

2) add this dependency:

```xml
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-ui</artifactId>
      <version>${springdoc-openapi-ui.version}</version>
    </dependency>
```

3) Then, add these 2 files, as mustache templates:

```java
package tech.jhipster.light.technical.infrastructure.primary.springdoc;

import io.swagger.v3.oas.models.ExternalDocumentation;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import org.springdoc.core.GroupedOpenApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class SpringdocConfiguration {

  @Bean
  public OpenAPI jhLightOpenAPI() {
    return new OpenAPI()
      .info(
        new Info()
          .title("JHipster Light API")
          .description("JHipster Light API")
          .version("v0.0.1")
          .license(new License().name("Apache 2.0").url("https://jhipster.tech"))
      )
      .externalDocs(new ExternalDocumentation().description("JHipster Light Documentation").url("https://jhipster.tech/light"));
  }

  @Bean
  public GroupedOpenApi jhLightAllOpenAPI() {
    // prettier-ignore
    return GroupedOpenApi.builder()
      .group("all")
      .pathsToMatch("/api/**")
      .build();
  }
}
```

4) add these properties in application.properties

```
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
```

### In infrastructure : 

`infrastructure/primary/rest/SpringBootWebResource` :

New API: `/api/servers/spring-boot/web/swagger`

**Comment by Pragya001** [comment]
Hi Pascal,
What needs to be done here @pascalgrimaud ?

**Comment by pascalgrimaud** [comment]
@Pragya001 : just updated the ticket with more details. How did you find this project ? :-) Are you interested in JHipster ?

**Comment by Pragya001** [comment]
@pascalgrimaud  Thanks!
I was looking for some work to contribute to Spring-Boot/Java. Bumped into one of the issues you raised on JHipster. :)

**Comment by pascalgrimaud** [comment]
This project is a little bit special:
- done in hexagonal architecture
- generate spring boot project in hexagonal architecture too
- could be similar to generator-jhipster but allow generation step by step
- still in 'alpha' and not official jhipster project yet

**Comment by Pragya001** [comment]
@pascalgrimaud 
Thanks! Will start working on this from tomorrow.

**Comment by pascalgrimaud** [comment]
Thanks a lot @Pragya001 for helping this project ! It should be soon in the official JHipster organization
I updated the ticket to use springdoc, instead of springfox.
Don't hesitate to ask if you need help

**Comment by pascalgrimaud** [comment]
@Pragya001 : do you still plan to work on this? If you don't have time or motivation, no worry, you can tell us. It's an Open Source project, we work during our free time.

I'm asking it because we'll need this very soon.
It will help to test easily the security part
