### ISSUE TITLE
Error when generating Cypress with Svelte

### ISSUE THREAD

**Issue by marioneyraud** [jhipster/jhipster-lite#2195]
Hello,

When I try to generate cypress to a project with Svelte, I have the following error:

Bad Request: Cannot read json content : Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)
 at [Source: (String)"{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "es2020",
    "lib": ["es2020", "DOM"],
    "target": "es2020",
    /**
\u0009\u0009\u0009svelte-preprocess cannot figure out whether you have a value or a type, so tell TypeScript
\u0009\u0009\u0009to enforce using \`import type\` instead of \`import\` for Types.
\u0009\u0009*/
    "importsNotUsedAsValues": "error",
\u0009\u0009\u0009TypeScript doesn't know about import usages in the template because it only sees the
\u0009\u0009\u0009script of a Svelte file. Therefore preserve all val"[truncated 687 chars]; line: 7, column: 6]

**Comment by pascalgrimaud** [comment]
Cc @flcarre
