### ISSUE TITLE
Rename modules/{module-slug}/apply endpoint

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2212]
The current `/apply` endpoint is for a specific need: a patch (just adding the thinks in the module).

As our goal is to manage dependencies between modules we should rename this to `/apply-patch` to enable upcoming endpoint: `apply-tree` that will apply module and all it's dependencies.

What do you think of that? cc @pascalgrimaud @hdurix

**Comment by pascalgrimaud** [comment]
Good ideas here
The apply-tree could do the same thing than generator-jhipster 

One possible problem could be:
- java base module can have 2 parents: maven or gradle
- liquibase can have different possible parent: psql, mysql, mariadb, etc
- need to think about how to manage it

But it's not related to this ticket

**Comment by DamnClin** [comment]
In fact apply-tree is the opposite of generator-jhipster, the same think would be a mode going from one patch to another.

For the tree building we'll need to find a way but multiple parents (and probably many other problem that we still have to figure out :-))

That being say, the current generator-jhipster way of doing that is a solution to that problem:-)
