### ISSUE TITLE
Migrate svelte to module

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2242]
Migrate src/main/java/tech/jhipster/lite/generator/client/svelte/core to modules

**Comment by SoniaLahi** [comment]
You can assign it to me

**Comment by DamnClin** [comment]
cc @SoniaLahi you started something on that or I can take it?

**Comment by DamnClin** [comment]
Great. There is a missing feature in the module mechanism for this one: files renaming. Ping me if you want help on that part.

PS: don't migrate the not styled API, we are deleting them :)
