### ISSUE TITLE
Migrate Typescript to module

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2283]
Migrate src/main/java/tech/jhipster/lite/generator/typescript to module

**Comment by pascalgrimaud** [comment]
Wonder if this module is important to keep.
It could be used by @Gnuk for his live coding in Typescript :-D

**Comment by pascalgrimaud** [comment]
I can do it tomorrow

**Comment by SoniaLahi** [comment]
Hi @pascalgrimaud, I will take this ticket :stuck_out_tongue_winking_eye:
