### ISSUE TITLE
Spring Boot Database Migration: flyway support

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#234]

**Comment by Bolo89** [comment]
Hello,

I can develop this feature. The steps could be :  

Add the dependencies in the pom.xml

Add in the application.properties file the values : 
- spring.flyway.enabled=true
- spring.flyway.driver-class-name=
- spring.flyway.url=
- spring.flyway.user=
- spring.flyway.password=

And add in the Project domain (in the config map, without default values)
- flywayDriverClassName=
- flywayUrl=
- flywayUser=
- flywayPassword=

It's ok ? or missing somethings ? :)

**Comment by pascalgrimaud** [comment]
Thanks a lot @Bolo89 !

About default values, I'm not sure it is necessary, as after generation, the user should edit, if needed.
It's better than providing all real values (user/password) in the API

Then, another question:
- spring.flyway.url, spring.flyway.user, spring.flyway.password depend on the database, right ?
- which value will you put by default?
- maybe, one suggestion would be to use the sames than spring.datasource.url, spring.datasource.user, etc
- it could be something like: spring.flyway.url=${spring.datasource.url}

What do you think?

**Comment by Bolo89** [comment]
I will use directly the properties of the datasource. Thanks.
