### ISSUE TITLE
Add MockitoExtention to UnitTest

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2376]
Currently, there are these annotations:

```
@DisplayNameGeneration(ReplaceCamelCase.class)
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
```

The suggestion here would be to add by default:

```
@ExtendWith(MockitoExtension.class)
```

What do you think @DamnClin ?
Good or bad idea ?
I don't think it should impact the performance when launching all unit tests, and it's to avoid forgetting when some users want to use Mock, InjectMocks

**Comment by DamnClin** [comment]
I think this is a bad idea sine using a mock is an exceptional case in a test, allowing this "by default" would push people to add mocks and I'm really not a fan of that

**Comment by pascalgrimaud** [comment]
Closing this one as it's not relevant
