### ISSUE TITLE
Svelte broken

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2409]
The current Svelte is broken because of:

![Screenshot_20220706-071208](https://user-images.githubusercontent.com/9156882/177473722-3c2b992b-882d-40dd-af4b-0f55bd7fea87.png)

Cc @flcarre

**Comment by pascalgrimaud** [comment]
Adding a bounty to have a quick fix here, if possible

**Comment by flcarre** [comment]
I'm already on

**Comment by flcarre** [comment]
closed in #2428

**Comment by pascalgrimaud** [comment]
@flcarre : approved

**Comment by pascalgrimaud** [comment]
Fixed
