### ISSUE TITLE
Migrate dummy feature to module

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2444]

**Comment by DamnClin** [comment]
I think we should switch to cucumber tests for this dummy feature, it will make everything way simpler (but adds a dependency)

**Comment by DamnClin** [comment]
I also think we should add some business in this example to show what should be tested and what should not, the feature is too simple here

**Comment by DamnClin** [comment]
Discussed that with @pascalgrimaud, I'll take it and make a small example but with some business in it so it is possible to take it as an example

**Comment by pascalgrimaud** [comment]
Agree we need some 🍻 here

**Comment by pascalgrimaud** [comment]
Adding a dedicated bounty for all the work done for the migrations to module
