### ISSUE TITLE
Angular: Remove ngx-webstorage dependency

### ISSUE THREAD

**Issue by wmarques** [jhipster/jhipster-lite#2458]
I saw that we use the lib `ngx-webstorage` in order to access LocalStorage and SessionStorage.
I find it quite overkill as it's very easy to access those with plain JavaScript, that's why I suggest to remove this lib and replace it with vanilla JS.

WDYT ? ping @qmonmert

**Comment by qmonmert** [comment]
@wmarques I agree with you. I used `ngx-webstorage` like in the generator, but no problem to remove it.
