### ISSUE TITLE
Migrate Spring boot MVC

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2467]
Migrate src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web to module.

I think we should split it to have a module dedicated to error handling (for example I'm not using zalando problems so I remove this part). What do you think @pascalgrimaud ?

**Comment by pascalgrimaud** [comment]
Sure we can split this module into 2 different one:
- 1 for simple MVC
- 1 for Zalando with Exception Handler

But, if I remember well, the current JWT and OAuth2 implementation need Zalando

**Comment by DamnClin** [comment]
I think they used to need it for a configuration in the SecurityConfiguration (personally I rewrite this) but yes there will be some replacement to handle here
