### ISSUE TITLE
Delete add pom and wrapper modules

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2472]
We have the maven init module which adds a base pom.xml and the maven wrapper, then two dedicated module. One for the pom and one for the wrapper. I think this is kinda missleading and that we should just keep the init module. What do you think @pascalgrimaud ?

**Comment by DamnClin** [comment]
We currently have 3 maven module: 

* maven pom (add a pom)
* maven wrapper (add maven wrapper)
* maven init (the 2 previous ones)

My suggestion is to only keep maven init

**Comment by pascalgrimaud** [comment]
Agree, let's keep only maven init
