### ISSUE TITLE
Migrate maven frontend

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2473]
Migrate src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven to module

**Comment by DamnClin** [comment]
Looking at that I see that we are reading `node.version` and `npm.version` from `src/main/resources/generator/dependencies/pom.xml`but I'm confused, is this really handled by dependabot? After a quick look I really don't think those 2 versions are really handled by dependabot (there are no dependency using them) but i really don't know this tool.

@pascalgrimaud can you confirm that these 2 versions won't ever be automatically managed that way and that we need to find a way to handle them?

**Comment by pascalgrimaud** [comment]
Yes I confirm the current system cant upgrade automatically node and npm, in pom.xml
