### ISSUE TITLE
Migrate or delete gradle modules

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2503]
Gradle modules `src/main/java/tech/jhipster/lite/generator/buildtool/gradle` allow initialization of a gradle project but after that everything will fail.

I think we should delete that for now to avoid spending time on that. Any though @pascalgrimaud ?

**Comment by pascalgrimaud** [comment]
Can we just remove the gradle part in the front, for now? Or just hide the button

**Comment by DamnClin** [comment]
A plan can be to create the module factory (not the resources) and delete all other parts so we don't lose the business logic BUT we don't need to take more time on that. What do you think?

**Comment by pascalgrimaud** [comment]
I'm fine so, let's move to module system
It won't impact our users as gradle doesn't work currently

What I'd like is to keep the template in resources, qo it can be reused

**Comment by atomfrede** [comment]
I vote for migration :) But it would be totally okay to remove it for now, not sure I'll have enough time in the coming days/weeks to do significant contributions to this.

**Comment by DamnClin** [comment]
Did something, don't hesitate to tell if that wasn't your idea on that :)

**Comment by atomfrede** [comment]
Looks okay so far. I'll see to make it work again, maybe after the moving parts have settled a little
