### ISSUE TITLE
Split OAuth account module

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2506]
To do https://github.com/jhipster/jhipster-lite/issues/2481 and https://github.com/jhipster/jhipster-lite/issues/2482 we'll need an `Account` model. The idea would be to take the one in OAuth2 account and put it in a dedicated module. Doing that we probably should rename `Username` which appears to be very missleading to `UserId` (still string based to handle many types of Userid often depending on IDP).

After that, given we'll have an `Account` domain model and context it'll be easy to create a `User` domain model and context for persistence.

I'm convinced we need this `Account` <-> `User` separation but I know this is really missleading. Any ideas on how we can ease the understanding of those two concepts (an `Account` is the authentication of someone on the app and a `User` is information for a user, not the same information, not the same business value, etc...).

Having this also leads to problems of data desynchronisation, when I can I get users from the IDP

**Comment by pascalgrimaud** [comment]
agree to rename from UserId to Username

let's split the account / user into 2 different contexts, we could simply add a README in the context if needed

the IDP sync is something I always delete in my real projects, as it doesn't work well, so not sure we should keep this sync like it's done in generator-jhipster

**Comment by DamnClin** [comment]
It's the opposite, from `Username` to `UserId`, still OK? (`Username` is read as user name which is really missleading)

**Comment by pascalgrimaud** [comment]
oh sure :-D

**Comment by DamnClin** [comment]
After a quick look to the JWT module in fact the common part is in authentication/domain with only 3 classes: 

* Username (soon to be UserId)
* Role
* Roles

We can either move that to a dedicated module or duplicate them in both modules for now (waiting for modules hierarchy)

**Comment by DamnClin** [comment]
In fact reading some documentation on that `Username` really is the default keyword in all tools (Spring, Keycloak, ...) I know it's missleading but I'm wondering if it wont be even more missleading callind it another way...

**Comment by DamnClin** [comment]
While working on JWT I found another (hopefully better) way to that, closing this one
