### ISSUE TITLE
Migrate or delete npm install and pretiffy

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2534]
There are two "modules" in src/main/java/tech/jhipster/lite/generator/packagemanager/npm to make an `npm install` and an `npm run prettier:format`

What do we do with those? I don't think those are dedicated modules, for me they should be options before downloading or something like that

**Comment by pascalgrimaud** [comment]
Need to think a little bit, I don't know if we should keep this or delete it

The idea was to format automatically after generating code, so we don't need to care too much about the formatting -> this idea comes from the generator-jhipster

**Comment by DamnClin** [comment]
Related to https://github.com/jhipster/jhipster-lite/issues/2732
