### ISSUE TITLE
Migration to Vite 3

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2578]
Following https://twitter.com/vite_js/status/1547218048410607616

Need to be done for:
- JHLite
- generated Vue 3
- generated React
- generated Svelte

Need to test manually as our current CI doesn't start the different app to launch Cypress

**Comment by DanielFran** [comment]
@qmonmert everything was green 💚

**Comment by qmonmert** [comment]
@pascalgrimaud my bad, tests are ok with React (I forgot `npm run build` with React). I think that the ticket can be closed.

**Comment by pascalgrimaud** [comment]
Thanks @qmonmert for helping

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/86684 :)

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by qmonmert** [comment]
@pascalgrimaud thanks
