### ISSUE TITLE
Manage spring.factories in modules

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2611]
`META-INF/spring.factories` are files loaded very early in spring lifecycle that comes to be very usefull. As those files can't be renamed / duplicated we need a way to manage them in modules.

The idea is to be able to set a value to a property and either:

* Create the property with the value;
* Add value to existing property.

For now we only need that for test spring.factories.

When done this must be used in the MongoDB module

**Comment by Yourgene** [comment]
Hi,
If nobody is already working on this issue, I'll take it. 

2 of 3 cassandra modules I'm working on are using spring.factories

**Comment by DamnClin** [comment]
You can have a look at https://github.com/jhipster/jhipster-lite/tree/main/src/main/java/tech/jhipster/lite/module/domain/javaproperties since it may use some of this logic

**Comment by pascalgrimaud** [comment]
Adding a bounty as it was more work than expected

**Comment by pascalgrimaud** [comment]
Thanks for your work @Yourgene : don't forget to claim your bounty

**Comment by Yourgene** [comment]
Thank you for the merge, and the added bounty :)
