### ISSUE TITLE
Refactor AsyncSpringLiquibaseTest

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2627]
The current implementation of `AsyncSpringLiquibaseTest` is mainly testing implementation details while using a class that should be deleted (LogbackRecorder). A refactoring might be a good idea here

**Comment by DamnClin** [comment]
cc @pascalgrimaud I think this is really important to rework and needs a bounty (this is the "slow test" shown in Julien's demo amoung many other problems). Ah, and this is really not easy to get right I think...

**Comment by murdos** [comment]
FYI I'm working on rewriting these tests

**Comment by murdos** [comment]
bounty claimed: https://opencollective.com/generator-jhipster/expenses/106794

**Comment by pascalgrimaud** [comment]
@murdos : approved
