### ISSUE TITLE
Spring Boot Security: OAuth2

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#270]

**Comment by pblanchardie** [comment]
Ready!

**Comment by pblanchardie** [comment]
Options:

- Custom
- Keycloak
- Okta
- Auth0

**Comment by pascalgrimaud** [comment]
work in progress here: https://github.com/pascalgrimaud/tmp-jhlite-oauth2

**Comment by pblanchardie** [comment]
[AdminUserDTO:12](https://github.com/pascalgrimaud/tmp-jhlite-oauth2/blob/6b78b9506b12d5c60495a4963842c658a875d80b/src/main/java/tech/jhipster/beer/account/application/AdminUserDTO.java#L12)
Do we still want to provide such login regex? see https://github.com/jhipster/generator-jhipster/issues/12740.

[SecurityConfiguration:194](https://github.com/jhipster/generator-jhipster/blob/ae3817af2284086800e9f7e8b1c7991b42a3e4b0/generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs#L194)
[SecurityConfiguration:241](https://github.com/jhipster/generator-jhipster/blob/ae3817af2284086800e9f7e8b1c7991b42a3e4b0/generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs#L241)
Interesting to see that session management and CSRF are still needed for monoliths to provide `oauth2Login`.
With a JHipster OAuth2 monolith (indeed, the generator warns it is stateful), we still rely on the JSESSIONID cookie so It looks like the JWT layer is not used at all. At least for `/api/account`, but I did not see any Authorization header management in the generated frontend. I'll need some time to test and understand what's going on ;)

[.antMatchers("/api/auth-info").permitAll()](https://github.com/pascalgrimaud/tmp-jhlite-oauth2/blob/6b78b9506b12d5c60495a4963842c658a875d80b/src/main/java/tech/jhipster/beer/security/oauth2/infrastructure/config/SecurityConfiguration.java#L92)
What is this?

**Comment by pascalgrimaud** [comment]
AdminUserDTO needs some refactoring, it's related to Account context, I didn't finish this part yet.

About aurh-info, see https://github.com/jhipster/jhipster-sample-app-oauth2/blob/main/src/main/java/io/github/jhipster/sample/web/rest/AuthInfoResource.java

**Comment by pblanchardie** [comment]
Now I have a clear understanding of everything JHipster currently generates (a bit late I admit!).

JHipster OAuth2 simply relies on the default session-based login for monoliths, but it also enables a JWT resource server so the generated API can be consumed by other applications with Authorization Bearer.
I just tested it and it works pretty well on your [tmp-jhlite-oauth2](https://github.com/pascalgrimaud/tmp-jhlite-oauth2) repository as well as in a JHipster generated app.
_The generated web_app client does not allow direct access grants so I enabled it to get an access token from keycloak directly._

So the [tmp-jhlite-oauth2](https://github.com/pascalgrimaud/tmp-jhlite-oauth2) repository would be the "full" or "monolith" option, proving the 3 layers:
- OAuth2 Client, which is required in all scenarii
  - with CustomClaimConverter for authority mapping with private providers (aka keycloak, okta, auth0)
- OAuth2 Login, which is useful for user-facing backends (monoliths)
- OAuth2 Resource Server JWT, which is useful for all kinds of web services, including microservices, but optional for user-facing backends (monoliths)

Obviously, for microservices, OAuth2 Login is disabled and only Authorization Bearer is supported. I guess it should be another option of JHipster Lite and I wonder how we'll separate them.

|                                        | Monolith | Microservice  |
|----------------------------|-----------------|----------------|
| OAuth2 Client                 | required    |   required  |
| OAuth2 Login                 |  _user-facing_  |_N/A_ |
| OAuth2 Resource Server | _web service_    | required       |
