### ISSUE TITLE
JPA persistence for dummy feature

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2725]
Add a JPA based persistence for dummy feature with dedicated modules for liquibase and flyway changelogs

**Comment by pascalgrimaud** [comment]
Just keep in mind, the dummy feature should be usable without database

What about the different existing database: MySQL, PostgreSQL, MariaDB, MongoDB ?
Then later, maybe Cassandra, Neo4J etc...
Should it support all these database too ? Or simply we can use the in memory in these cases

**Comment by DamnClin** [comment]
The plan is to have dedicated persistence modules so we can do them whenever we want

**Comment by pascalgrimaud** [comment]
Adding a bounty on this big feature
