### ISSUE TITLE
Add format & download to module screen

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2732]
The goal of this action is to make: 

```
npm i 
npm run prettier:format
```

before downloading the project

**Comment by pascalgrimaud** [comment]
We need to think more, because `npm i` will download lot of libs into `node_modules` and it's not a good idea to zip and download all this big folder

**Comment by DamnClin** [comment]
Yep, we'll have to filter the `node_modules` folder in the zip
