### ISSUE TITLE
Spring Boot: AOP Logging

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#274]

**Comment by MSaguer** [comment]
Do you confirm that this issue consists in adding aop logging just like [LoggingAspect.java](https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/java/io/github/jhipster/sample/aop/logging/LoggingAspect.java) and all its configuration?

I could create new package server/springboot/aop/logging

**Comment by pascalgrimaud** [comment]
@MSaguer : exactly, with this https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/java/io/github/jhipster/sample/config/LoggingAspectConfiguration.java too

Yes, I think it should be created in a new context

**Comment by MSaguer** [comment]
Ok. Second file was what I meant by "all its configuration".
You can assign it to me

**Comment by MSaguer** [comment]
Hi,

This development requires to add "jhipster-dependencies" in the dependencyManagement section.

Can this element be added directly in the pom.xml.mustache file? Else new addDependencyManagement should be added in maven service by another issue.

**Comment by pascalgrimaud** [comment]
Why do we need jhipster-dependencies for this?

**Comment by pascalgrimaud** [comment]
Oh I see. Maybe because of https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/java/io/github/jhipster/sample/config/LoggingAspectConfiguration.java#L13 ?

I think this constant should be replaced by a value in application.properties, which can be activated or not.

More simpler than the dev profile.

I'll give more details what I have in mind if needed, tomorrow :-)

**Comment by MSaguer** [comment]
Yeah, my message was lacking details. As you guessed, the aim was to access JHipsterConstants for the profile definition.

Let's use the spring.profiles.active properties.

I've started to add the addDependencyManagement methods. I keep it in a branch just in case it could be usefull later.

**Comment by pascalgrimaud** [comment]
I'd prefer a property instead of profile.
Something like:
application.aop.logging=false

By default, it's false, in application.properties
It can be true in application-fast.properties as this profile is used specially for dev

One of big change with generator-jhipster is to remove dev/prod profile, which is so confusing.
default/fast is better

**Comment by pascalgrimaud** [comment]
Adding a bounty on this.
As it's not so difficult, but the missing LoggingAspectTest is important, as it's not coded in main generator-jhipster. We need to code it here.

**Comment by MSaguer** [comment]
many thanks @pascalgrimaud for this bug bounty and for your reviews. It was quite interresting to work on this.

I claimed it in https://opencollective.com/generator-jhipster/expenses/59408

**Comment by pascalgrimaud** [comment]
@MSaguer : approved :-)
