### ISSUE TITLE
Angular: bug on generated app

### ISSUE THREAD

**Issue by qmonmert** [jhipster/jhipster-lite#2750]
In `src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/login/login.component.html.mustache`, we have this template:
```
<div>You are logged in as user "{{ account?.login }}".</div>
```
but in the generated app `src/main/webapp/app/login/login.component.html`, we have:
```
<div>You are logged in as user "".</div>
```
@DamnClin it was supposed to work?

**Comment by DamnClin** [comment]
I have always seen that bugged, no idea what it is supposed to do :)

**Comment by qmonmert** [comment]
template in the generated app should be:
```
<div>You are logged in as user "{{ account?.login }}".</div>
```

**Comment by DamnClin** [comment]
This module is one of the last one to be migrated to the new module system. As it is using the old mechanism you have to escape mustaches in it (don't remember how it done but I can look for it)

**Comment by qmonmert** [comment]
Ok I do that!
