### ISSUE TITLE
Spring Boot: LoggingConfiguration

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#276]
To be able to push logs to Logstash for example

**Comment by pblanchardie** [comment]
JHipser's LoggingConfiguration was responsible for logstash, but was also configuring console logging.
The `useJsonFormat` property was convenient for logstash, but I think it shouldn't impact console logging: it was a pain to have console logging in JSON when you only wanted JSON in logstash.

I'd go with a logstash configuration that does not impact console logging.

`LogstashConfiguration`

`/api/servers/spring-boot/logging/logstash` -> should aop logging fall into `logging/`?
or 
`/api/servers/spring-boot/logstash`

I'll draft something, tell me if you have already thought about something about logging.

**Comment by pascalgrimaud** [comment]
As it is for logstash, I think renaming is better.

Agree about log in console, it should never be in JSON format, it is not readable.

As both are related to logging, we could use spring-boot/logging

**Comment by pblanchardie** [comment]
> Agree about log in console, it should never be in JSON format, it is not readable.

Yes, #415 is only about TCP and does not impact console logging, that's better.

If you can't or don't want to use TCP, you'll have to produce JSON logs with console or file appenders. I guess it was the idea behind the hack in JHipster but it messed up in my case.
If it's frequent, it will be easy to provide alternatives to "logstash TCP", eg. "logstash file"

**Comment by pblanchardie** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/60553

**Comment by pascalgrimaud** [comment]
@pblanchardie : approved
