### ISSUE TITLE
Extract versions to specific files

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#278]
The different version should be extracted to a dedicated `pom.xml` file.
Then, this file can be updated automatically by dependabot

Some examples:
- https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBoot.java#L5
- https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/server/springboot/database/postgresql/domain/Postgresql.java#L5

**Comment by DanielFran** [comment]
@pascalgrimaud Can you assign to me, please?

My proposition:
1- Create a module with only the pom where it will be declared all the dependency versions
2- Create a property file from the pom.xml
3- Create a class to read a property and use it each time we need a dependency version.

**Comment by pascalgrimaud** [comment]
Yes exactly what I have in mind too

**Comment by pascalgrimaud** [comment]
Let me think a little bit about the folder structure before starting something.
I'll propose it here

**Comment by pascalgrimaud** [comment]
After thinking a little bit, I would suggest to add the method in existing BuildTooService:

![image](https://user-images.githubusercontent.com/9156882/149090135-e369e48a-f867-4b42-b19b-ad1000b9b3d7.png)


Here the mini roadmap to do this:
- 1st PR
  - add a new `pom.xml` to `src/main/resources/generator/buildtool/` folder with old dependencies (it's intended)
  - update [dependabot](https://github.com/jhipster/jhipster-lite/blob/main/.github/dependabot.yml#L1-L9) maybe to add this folder ?
  - check if some of these dependencies are auto updated
- 2nd PR
  - add a method in `BuildToolService` to extract the version, for example, `getVersion("spring-boot")` should return Optional `2.6.2`

- other PRs: refactoring with small PRs to update context by context, and use this new method

What do you think?

**Comment by DanielFran** [comment]
Seems OK for me.

For 3rd part, `3- Create a class to read a property and use it each time we need a dependency version.`, I was thinking if the property file can be used as any other application property and then use @Value annotation to have access to the property value, so no need to create a specific class/method to have access to the versions ;)

Anyway, let's do it step by step with small PRs!

**Comment by pascalgrimaud** [comment]
Mhhh unless I miss understood, the 3rd part is similar to the 2nd part I mentioned

Anyway, I don't think we need `@Value`, as we'll be in the domain, so we can't rely on framework and we don't need framework in fact here. Simple Java code can read files

**Comment by pascalgrimaud** [comment]
I'm trying to do the NPM part, with a fresh `package.json`, but I wonder where we should put these new files:
- `pom.xml`
- `package.json`
- Dockerfile / docker-compose for Docker ?
etc

I'd suggest:
- for `pom.xml`, it could be `src/main/resources/generator/buildtool/dependencies/pom.xml`
- for `package.json`, it could be `src/main/resources/generator/packagemanager/dependencies/package.json`

Another solution would be:
- `src/main/resources/generator/dependencies/pom.xml`
- `src/main/resources/generator/dependencies/package.json`

what do you think? which solution do you prefer? Do you have better idea?

**Comment by pascalgrimaud** [comment]
@DanielFran :  I'm adding a bounty on this. I don't need this, as the NPM part was pretty easy

**Comment by pascalgrimaud** [comment]
@DanielFran : I'm closing this one as I think the main work is finished.

Now we can improve other context (spring boot, postgresql, liquibase, etc), step by step, for using this new system of version -> and it should be done in another PRs

**Comment by DanielFran** [comment]
@pascalgrimaud Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/62472

**Comment by pascalgrimaud** [comment]
@DanielFran : approved
