### ISSUE TITLE
Spring Boot: Eureka client

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#280]

**Comment by Bolo89** [comment]
Hello @pascalgrimaud, i'm interrested to do this ticket. Possible ?

**Comment by pascalgrimaud** [comment]
Yes go ahead @Bolo89 
Tell me if you need details?

**Comment by pascalgrimaud** [comment]
Increasing the bounty as it was more work than expected, because it needed to do some refactoring part
