### ISSUE TITLE
Spring Boot: broker Kafka

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#283]

**Comment by fdelbrayelle** [comment]
I can migrate what I've done on Kafka module here!

**Comment by pascalgrimaud** [comment]
Thanks, I'll complete this ticket with the mini roadmap later

**Comment by pascalgrimaud** [comment]
So the roadmap is already here!

**Comment by fdelbrayelle** [comment]
:heavy_check_mark: What has been done today:
- Apache Kafka Clients dependency
- Testcontains dependency
- Docker Compose

:monocle_face: WIP:
- Dummy Producer with Kafka Properties and topic name management (POST endpoint)
- Dummy Consumer with Kafka Properties and topic name management (POST endpoint)
- AKHQ support through a Docker Compose file

**Comment by pascalgrimaud** [comment]
increasing the bounty as in this PR, there are 3 features:
- kafka dependencies + configuration
- dummy consumer
- dummy producer

**Comment by fdelbrayelle** [comment]
Remaining work to do:
- AKHQ support to monitor topics
- Dummy consumer
- Front button to add Kafka support
