### ISSUE TITLE
Simple usage stats

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2832]
As there are plan to have deployed versions of JHlite keeping simple modules application stats in a persistence can be a good idea. Nothing fancy for now, just starting to gather data.

@jdubois I'dd like to put that in a simple relational DB, what kind of DB is a good idea for the deployment you have?

**Comment by jdubois** [comment]
We have different options, but for something simple/cheap/easy I would recommend you use MongoDB with the Spring MongoDB Starter.
On Azure, I can host this on CosmosDB (they support the MongoDB API), and they have a free tier, which means 0 cost (also if you want to test/develop).

**Comment by DamnClin** [comment]
Ok, this is cool cause it gives use a good reason to build the mongock module! Can't do anything this week but I'll try to work on it next week

**Comment by pascalgrimaud** [comment]
There are 2 different uses of JH Lite:
- locally : the user doesn't need a database, so we should keep the current behavior
- cloud : we could store the stats in an existing database

So I think we should add this feature only to the 'cloud' profile

**Comment by DamnClin** [comment]
Locally it can be an in memory implementation yep
