### ISSUE TITLE
Java: add Sonar configuration

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#284]

**Comment by swarajsaaj** [comment]
I propose following approach:-
1. Add plugin configuration in pom.xml
2. Add sonar.properties
3. Add sonar.yml in src/main/docker for sonarqube community server.

@pascalgrimaud would you suggest anything more to be done?

**Comment by pascalgrimaud** [comment]
Yes it's the good approach I think

Anyway:
- I don't know if we have all method to add the configuration in pom.xml. We need to check this part first and do a 1st PR separately if needs
- then, I wonder where to put this. Maybe in server/java/sonar. Not sure it's specific to java, as it could be similar if it was kotlin. Maybe simply server/sonar ?

**Comment by swarajsaaj** [comment]
> I don't know if we have all method to add the configuration in pom.xml. We need to check this part first and do a 1st PR separately if needs

Yes, would enhance the `BuildToolDomainService` with required configurations in plugins

> then, I wonder where to put this. Maybe in server/java/sonar. Not sure it's specific to java, as it could be similar if it was kotlin. Maybe simply server/sonar ?

I agree, its not just `java`, as per current structure it should be `server/sonar`.
Then I think its not limited to only server-side applications, then even `server/javatool` should not be in `server`. Isn't it?

**Comment by pascalgrimaud** [comment]
oh by `server`, it means backend, so I think javatool is in the right place. Anyway, it would be easy to move if needed.

About sonar, we could have another / similar configuration for "client", like Angular, React or Vue later.

So I'm suggesting this:
- put it into `server/sonar` for now, and then later we could move it if it's necessary

What do you think?

**Comment by swarajsaaj** [comment]
Yes, let's start with `server/sonar` and move it later if needed :)
You may assign this ticket to me.

**Comment by pascalgrimaud** [comment]
Not sure if it can help: https://github.com/pascalgrimaud/jhipster-lite/commit/cfd245cfbf042c016f6fec46995ae508be98582b

I did this for JHLite, and to reduce the code smells, before working on pushing an analysis to Sonarcloud
