### ISSUE TITLE
Rename cucumber modules

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2852]
here the different names:
- cucumber-jwt-authentication
- cucumber-oauth2-authentication
- springboot-cucumber

The names should be consistent, maybe:
- cucumber-jwt-authentication -> springboot-cucumber-jwt-authentication
- cucumber-oauth2-authentication -> springboot-cucumber-oauth2-authentication

What do you think, @DamnClin ?

**Comment by DamnClin** [comment]
Sounds good

**Comment by pascalgrimaud** [comment]
thanks, I'm doing it right now
