### ISSUE TITLE
Sample Vue project in Hexa Arch

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#286]
Init project with Vue

**Comment by pascalgrimaud** [comment]
I'm starting this.
- generate JHipster + Vue project with last release 7.4.1
- clean all unnecessary files, like register, settings, user-management, etc

The goal is to have:
- home page
- login popup

Nothing more.

**Comment by pascalgrimaud** [comment]
Here a first version of clean project: https://github.com/pascalgrimaud/jh-vue-lite

Then, there is some work to change the structure and use Hexagonal Architecture

**Comment by pascalgrimaud** [comment]
In this repo https://github.com/pascalgrimaud/jh-vue-lite (not in jhipster-lite), the next steps would be (in webapp folder)
- try to clean useless files
- most important and hardest part: refactoring in Hexagonal Architecture
- add missing unit tests, the coverage must be at 100%

Once it's done, we can consider to include this part in JHipster Light

I'm adding a bounty on this, as it's hard and requires some advanced knowledges in this architecture

**Comment by pascalgrimaud** [comment]
Cc @franceq34, following our discussion

Maybe cc @nonomoho and @seraphinandrieux as you can be interested by this.

**Comment by Franceq34** [comment]
I'm in !

**Comment by pascalgrimaud** [comment]
closing this and migrate the bounty to https://github.com/jhipster/jhipster-lite/issues/295
