### ISSUE TITLE
UX/UI: dark/light mode

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2892]
It would be cool to be able to switch between these 2 modes.

**Comment by pascalgrimaud** [comment]
I'm adding a bounty on this, as I'd like to have the light mode (instead of the dark one)

cc @Gnuk : maybe you can take care of this ?

**Comment by Gnuk** [comment]
Yes, I'll start this after I made more components/templates

**Comment by MAYURIKOTHARI19** [comment]
Can you assign this to me I would love to work on it..

**Comment by Gnuk** [comment]
Hi @MAYURIKOTHARI19 , I'm currently making some components and migrating some of them in Tikui, maybe you'll like to know more about this to not create some conflicts between our PR. Dont hesitate to contact me!

Meanwhile, tomorrow I'll have some discussions about style with @ascelineboullen if you're interested about this.

**Comment by pascalgrimaud** [comment]
@zhyd1997 : increasing the bounty for the time spending on this and your patience :)

**Comment by pascalgrimaud** [comment]
done by https://github.com/jhipster/jhipster-lite/pull/6024
plz @zhyd1997 : claim the bounty

**Comment by zhyd1997** [comment]
Hi @pascalgrimaud 

Maybe the bounty can be splited 2 parts, one for @Gnuk (took so much time to review) and you @pascalgrimaud (give me onboarding for this project when I was working on this task)

Thanks ⭐

**Comment by pascalgrimaud** [comment]
no @zhyd1997 : take the full bounty, it's deserved

Then @Gnuk can take another bounty, I'll discuss with him

**Comment by zhyd1997** [comment]
The team has already given the opportunity to contribute to open source, so it's part of what I am looking for...or the bounty can be used for the project to develop better and better 😆

**Comment by pascalgrimaud** [comment]
@zhyd1997 : really, no worry, take the full bounty. Maybe it will motivate you to continue and improve JHLite in other tickets :) Happy to have you as contributor

**Comment by zhyd1997** [comment]
Okay, great thanks! 🙏

**Comment by zhyd1997** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/148587

**Comment by pascalgrimaud** [comment]
@zhyd1997 : approved <3
