### ISSUE TITLE
UX/UI: inclusive design

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2893]
It's important to respect that:
https://www.microsoft.com/design/inclusive/

Is it the correct link, @jdubois ?

**Comment by jdubois** [comment]
Yes it is!
And currently the application isn't even responsive (doesn't work on my mobile), so there is probably some good work to do.
Have a look at what @roryp does, he's our top expert at Microsoft (and he's in my team!!). Maybe an opportunity to collaborate on accessibility?

**Comment by Gnuk** [comment]
Maybe you're interested about this issue @ascelineboullen

**Comment by pascalgrimaud** [comment]
Closing in favor ofhttps://github.com/jhipster/jhipster-lite/issues/10576
