### ISSUE TITLE
Dummy feature without security

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2895]
We should be able to use dummy feature without security part, as the security part can be added later:

```json
{
  "actions" : [ {
    "module" : "init",
    "date" : "2022-08-02T07:06:29.750718088Z",
    "properties" : {
      "projectName" : "beer project",
      "baseName" : "beer"
    }
  }, {
    "module" : "maven-java",
    "date" : "2022-08-02T07:06:44.875139201Z",
    "properties" : {
      "projectName" : "beer project",
      "baseName" : "beer",
      "packageName" : "tech.jhipster.beer"
    }
  }, {
    "module" : "java-base",
    "date" : "2022-08-02T07:06:55.190554429Z",
    "properties" : {
      "projectName" : "beer project",
      "baseName" : "beer",
      "packageName" : "tech.jhipster.beer"
    }
  }, {
    "module" : "springboot",
    "date" : "2022-08-02T07:07:02.789362424Z",
    "properties" : {
      "projectName" : "beer project",
      "baseName" : "beer",
      "packageName" : "tech.jhipster.beer"
    }
  }, {
    "module" : "springboot-tomcat",
    "date" : "2022-08-02T07:07:15.902075728Z",
    "properties" : {
      "projectName" : "beer project",
      "baseName" : "beer",
      "packageName" : "tech.jhipster.beer",
      "serverPort" : 8080
    }
  }, {
    "module" : "zalando-problems",
    "date" : "2022-08-02T07:07:20.175083567Z",
    "properties" : {
      "projectName" : "beer project",
      "baseName" : "beer",
      "packageName" : "tech.jhipster.beer",
      "serverPort" : 8080
    }
  }, {
    "module" : "bean-validation-test",
    "date" : "2022-08-02T07:07:21.449589208Z",
    "properties" : {
      "projectName" : "beer project",
      "baseName" : "beer",
      "packageName" : "tech.jhipster.beer",
      "serverPort" : 8080
    }
  }, {
    "module" : "springdoc-openapi",
    "date" : "2022-08-02T07:08:01.145956859Z",
    "properties" : {
      "projectName" : "beer project",
      "baseName" : "beer",
      "packageName" : "tech.jhipster.beer",
      "serverPort" : 8080
    }
  }, {
    "module" : "dummy-feature",
    "date" : "2022-08-02T07:08:10.450645540Z",
    "properties" : {
      "projectName" : "beer project",
      "baseName" : "beer",
      "packageName" : "tech.jhipster.beer",
      "serverPort" : 8080
    }
  } ]
}
```

**Comment by DamnClin** [comment]
I disagree! The current dummy feature clearly have an admin / user separation and have no meaning at all without authentication and authentication can add some complexity so I really want to enforce that in the dummy feature

**Comment by pascalgrimaud** [comment]
So for an user who'd like to start a very light project, using `init, maven, java-base, springboot, springboot-tomcat, springdoc`, what would be the best to have a **simpler** dummy ?

**Comment by DamnClin** [comment]
Hard to say, why this peculiar combination? 

For me, the main purpose of this dummy feature is to be able to build an app to validate stuff in the CI. Of course, this can be used as a training example but we can't build training examples for each possible modules combination.

**Comment by pascalgrimaud** [comment]
I suggested to have a simpler dummy with less parents: here, security and cucumber are mandatory. Cucumber is not used in every projects for example :-D
Security is, but it would be nice to be able to add it later

Let me think about it. I don't plan to update the current dummy, which looks very nice, just discuss

**Comment by DamnClin** [comment]
We can remove cucumber and security but that probably mean no WebService exposure so a dummy with just a domain model (we can do that on the order part of the current dummy feature)

**Comment by pascalgrimaud** [comment]
The dummy module belongs to you @DamnClin 

If I want a simpler dummy, I could simply create a new one, with another name, directly in JHLite or in a custom JHLite
So let's close this ticket, as not important to have
