### ISSUE TITLE
Maven: possibility to generate only wrapper

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2896]
It would be cool to be able to generate only the wrapper:
- for existing Java projects without wrapper, so we can use JHLite to add the wrapper (instead of copy/paste from existing projects)
- to upgrade the wrapper when there is a new version

I think it's a good first issue

**Comment by AnneJacquet** [comment]
I understand the use case but I'm unsure about the link with maven-java. The maven-java module creates the wrapper and the pom.xml.

The maven-java could stay as it is and we create a new standalone module with no dependency for just the wrapper. 
- pros : different modules for different use cases (creating a brand new project vs upgrading the wrapper/adding it to existing project)
- cons : two modules overlap 

The maven-java could be split into two modules : one for the wrapper and one for the pom.xml.
- pros : no overlapping
- cons : no idea for clear naming 🤔 

Did you have anything in mind ?

**Comment by pascalgrimaud** [comment]
What I have in mind is to code inside "maven" package:

![image](https://user-images.githubusercontent.com/9156882/194027637-2dbb043b-5478-405f-9b87-b6943118ce40.png)

And it could be a separated module in MavenModuleConfiguration:

![image](https://user-images.githubusercontent.com/9156882/194027838-4c0ada2c-0990-46f3-baac-b291b997b29b.png)

This module:
- doesn't depend on any other module, we could use it directly on any existing project
- will only add maven wrapper

Don't hesitate to tell me if I'm not clear enough, or if I'm wrong :-D
