### ISSUE TITLE
Avoid automatic transactions

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2906]
Seems like there are "automatic" transaction when using a database starter. What I mean is that even without `@Transactional` annotation the query are executed (that mean there is a transaction somewhere).

This is not really good since, if it comes from an open in view (or something similar), that mean too much connections and transactions.

@DanielFran do you have any idea on the root cause of that?

**Comment by atomfrede** [comment]
In the main generator we set it to false. It seems to be (still) [true by default.](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.data.spring.jpa.open-in-view)

**Comment by DanielFran** [comment]
We do initialize it also by default to false when using sqlCommon
https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/server/springboot/database/sqlcommon/domain/SQLCommonModuleBuilder.java#L80

**Comment by DamnClin** [comment]
Yep, that's the first think I checked, I don't really understand the source of that... need to dig a little on that one

**Comment by DamnClin** [comment]
Digged into that a little and the root cause was `@EnableJpaRepositories(basePackages = {"org.company.product"})` which have a `enableDefaultTransactions` property default to true.

For me this is a bad thing since it's really common to make multiple operations in one transaction (ex: read and update). So I really prefer enforcing manual transaction management and have tests fails if I forgot any transaction handling.
