### ISSUE TITLE
Hexagonal Arch: generate AnnotationArchTest

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2922]
In JHipster Lite, we have this test: `AnnotationArchTest`
It could be nice to generate it too, at the same time than `HexagonalArchTest` when using this module

**Comment by DamnClin** [comment]
Yep but we should also add IntTest pattern for integration tests :)

**Comment by pascalgrimaud** [comment]
done for pattern IntTest too
