### ISSUE TITLE
React: core

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#293]

**Comment by matthieulapatate** [comment]
Hello, would that be an executable application or web-based one ? I would be interested in working on it.

**Comment by pascalgrimaud** [comment]
@matthieulapatate : you can have a look at https://github.com/jhipster/jhipster-lite/pull/648 and help there, as the work has already been started

**Comment by pascalgrimaud** [comment]
Following discussion with @qmonmert, it's better to not confuse our users by supporting 2 React options.
We can rethink about it, if one day, we're not happy with Vite anymore.

So you can claim a part or the full bounty, for all the work done here, @qmonmert 
Thanks so much for your help on this project.
