### ISSUE TITLE
Angular: core

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#294]

**Comment by pascalgrimaud** [comment]
I assigned this ticket to you @qmonmert and added a bounty
Will see if it's not enough, according to the amount of work, I can increase it later :)

**Comment by pascalgrimaud** [comment]
You need a crazy job @qmonmert ! Really. Increasing the bounty as it will be well deserved

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/64145 😅

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by pascalgrimaud** [comment]
- closed by https://github.com/jhipster/jhipster-lite/pull/571
