### ISSUE TITLE
JHipster Lite internal: init front

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#295]

**Comment by swarajsaaj** [comment]
What are the thoughts/ideas here? I guess the front would be web-based. Is the vision to have something similar to jhipster-online (with zip and github/gitlab integrations in future?)

**Comment by pascalgrimaud** [comment]
Yes that's my idea. But this is a big ticket, I have a lot of ideas I should detail, which can be splitted into several small tickets

**Comment by pascalgrimaud** [comment]
Before starting this ticket, we should focus on this ticket first
- Vue: https://github.com/jhipster/jhipster-lite/issues/286

Because, once the Vue init is done, we can use it in this project.
Yes, we can use JH Lite on itself :-)
