### ISSUE TITLE
Display minimap on landscape screen

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3137]
It can be a good idea to a minimap (like in RTS games) somewhere on the landscape screen to ease navigation in the landscape

**Comment by abdelfetah18** [comment]
Hi,
This is a minimap that i made. is it good ?

https://github.com/jhipster/jhipster-lite/assets/62770167/e1d3ba56-e5b3-4143-8e9c-bd5252d9ea8d

- Should i add a way to open/close the map ?
- Should i let the user change the map position ?

**Comment by DamnClin** [comment]
Looks good, may be a little bit smaller and bottom left but looks really good

**Comment by pascalgrimaud** [comment]
I think a button to open / close the map would be nice, for users who don't want it, but it can be done in another PR if you prefer

For now, no need to allow to change the position, let's wait some feedbacks

Anyway, it looks good. Nice work @abdelfetah18

**Comment by abdelfetah18** [comment]
Thanks.

This is my PR #7504

> I think a button to open / close the map would be nice, for users who don't want it, but it can be done in another PR if you prefer

Then i will do it in another PR.

> For now, no need to allow to change the position, let's wait some feedbacks

Okay

**Comment by pascalgrimaud** [comment]
@abdelfetah18 : don't forget to post here the link of opencollective. So I can confirm who claims the bounty

**Comment by abdelfetah18** [comment]
https://opencollective.com/generator-jhipster/expenses/164681

**Comment by pascalgrimaud** [comment]
@abdelfetah18 : approved, thanks for your work
