### ISSUE TITLE
Create meta modules?

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3154]
Now that we have the landscape with modules and features it may be a good idea to create a concept of meta modules. 

To create a meta module you declare a module as being part of a meta module in it's organization and, in the landscape it will be displayed as a "classic" module and in the meta module. A given module can be in 0 or 1 meta module.

Meta modules are selectable on their own in the landscape but you can also select just some of the composing modules.

Other modules can depend on module or on meta modules.

Some candidates: 

* `maven-java` become a meta module and we split maven wrapper and maven init in modules
* `spring-boot` is spitted in many modules and become a meta module (and we integrate  `bean-validation-test` in it)
* `java-base` is spitted in many modules and become a meta module

I think this can be a good idea as it looks like this is missing block for full modularity, with this we'll have: 

* modules that describe some changes;
* features that describe well... a feature and allow only one selection;
* meta modules to get finer grains modules when needed.

The challenging part may to display that in a somehow readable way in the landscape...

**Comment by DamnClin** [comment]
cc @hdurix @pascalgrimaud what do you think of that?

**Comment by pascalgrimaud** [comment]
> A given module can be in 0 or 1 meta module.

Instead of 1, shouldn't it be 0 or n, instead?

Example 1:
- maven-java: meta module
- maven-wrapper: module
- maven-init: module

Example 2:
- maven-kotlin: meta module
- maven-wrapper: module (the same one, used in example 1)
- maven-init-kotlin: module

What do you think @DamnClin ?

**Comment by DamnClin** [comment]
Not really possible to do since we won't be able to build links for the landscape

**Comment by pascalgrimaud** [comment]
So for having this, it means to duplicate the module maven-wrapper? It'd be bad in this case

**Comment by DamnClin** [comment]
Yes otherwise we can't depend on `maven-wrapper`

**Comment by DamnClin** [comment]
I think this is overkill for now, closing that
