### ISSUE TITLE
Split init & init-minimal to have a prettier module

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-lite#3224]
Init & init-minimal are not so meaningful. And with Landscape, we force user to choose between both for any project as they are root.

Is there any objection to create a `prettier` module (which could depend on `init`)?

**Comment by DamnClin** [comment]
If it's the only difference between those two none from me (and we should do it if it's only that). I also realized that the "Format" button should be disabled without this module applied

**Comment by hdurix** [comment]
It seems so:

```
❯ diff 67* | grep -v Common
Only in 67f3d012-4474-4d10-a7cc-d7d178d1160c: .husky
Only in 67f3d012-4474-4d10-a7cc-d7d178d1160c: .lintstagedrc.js
Only in 67f3d012-4474-4d10-a7cc-d7d178d1160c: package.json
Only in 67f3d012-4474-4d10-a7cc-d7d178d1160c: .prettierignore
Only in 67f3d012-4474-4d10-a7cc-d7d178d1160c: .prettierrc
```

**Comment by DamnClin** [comment]
Ok, let's totally do that so. You take it?

**Comment by hdurix** [comment]
I'm not sure yet.
