### ISSUE TITLE
Dynamic module urls don't use exception handler

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3276]
Dynamic module urls (handled in `JHipsterModuleApplicationController`) do not use the application exception handler (and it should)

**Comment by AnneJacquet** [comment]
J'ai creusé un peu et la magie se passe dans la classe`AbstractHandlerExceptionResolver`
```java 
@Nullable
protected abstract ModelAndView doResolveException(
	HttpServletRequest request, HttpServletResponse response, @Nullable Object handler, Exception ex);

```

les `@RestController` avec leurs méthodes `@XXXMapping` utilisent l'implem `AbstractHandlerMethodExceptionResolver` alors que le `JHipsterModuleApplicationController implements Controller` utilisent l'implem `ResponseStatusExceptionResolver`.

D'après la doc spring de [AbstractHandlerMethodExceptionResolver](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/handler/AbstractHandlerMethodExceptionResolver.html)
> Abstract base class for [HandlerExceptionResolver](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/HandlerExceptionResolver.html) implementations that support handling exceptions from handlers of type [HandlerMethod](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/method/HandlerMethod.html).


En remplacant la map `private final Map<String, JHipsterModuleApplicationController> controllers;` de `JHipsterModulesPatchApplicationHandlerMapping` par `private final Map<String, HandlerMethod> controllers;
` ==> on utilise l'autre implem et on passe bien par `ExceptionTranslator` 🎉 .

Mais je me demande les avantages de cette solution ⬆️ pour qu'elle ait été choisie par rapport à
<img width="782" alt="image" src="https://user-images.githubusercontent.com/18069443/195307914-d3bc832d-35dd-44a2-b565-927406cbb8d0.png">

**Comment by DamnClin** [comment]
> Mais je me demande les avantages de cette solution arrow_up pour qu'elle ait été choisie par rapport à

probably none, I just didn't dig that deep while doing this dynamic url thing :D

**Comment by AnneJacquet** [comment]
Ok great ! Opening a PR with the latter then !
