### ISSUE TITLE
Move commit checkbox next to apply buttons

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3373]
The commit checkbox should be closed to apply button.

**Comment by DamnClin** [comment]
Why?

**Comment by pascalgrimaud** [comment]
Currently, I think it's a little bit hidden, I found it more logic to move near the buttons, just before to apply, like this:

![image](https://user-images.githubusercontent.com/9156882/189342786-3e93f78b-7683-4413-9c85-b2309b51d2ed.png)

So just before to apply, you can decide to commit or not auto commit
