### ISSUE TITLE
Tikui: rename cache to .cache

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3389]
Is it possible to rename this folder to something else than `cache` ?
Here some suggestion:
- `.cache/`
- `.tikui/`

Or maybe directly inside target ?
- `target/cache/`
- `target/tikui/`

cc @Gnuk

**Comment by Gnuk** [comment]
It's not possible currently, it needs to contribute to tikui core. This should not be inside the target directory I think because it's only used for sass when you're in serve mode in order to be faster on sass changes.

**Comment by pascalgrimaud** [comment]
ok then let's keep this opened, until the improvement is done in Tikui core :)

**Comment by Gnuk** [comment]
Yep, don't hesitate to create the ticket in https://github.com/tikui/tikui-core and reference it (sorry, I'm a little buusy this weekend)

**Comment by Gnuk** [comment]
Would you like the default tikui one from `3.0.0` ? (it's on `.tikui-cache`
