### ISSUE TITLE
prettier broken in generated project

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3424]
cc @hdurix 

Using this following config without committing, prettier is broken.
To reproduce:
- generate project without commit
- go into project
- git init
- npm i
- add and commit to launch pre commit hook

It's broken for 2 reasons:
- https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/prettier/.lintstagedrc.js -> don't have eslint by default, as eslint is used by the front
- `{,src/**/}` should be `{,src/**/,}` instead

```json
{
  "actions" : [ {
    "module" : "init",
    "date" : "2022-09-06T13:57:28.507025541Z",
    "properties" : {
      "packageName" : "tech.jhipster.beer",
      "projectName" : "beer",
      "baseName" : "beer"
    }
  }, {
    "module" : "maven-java",
    "date" : "2022-09-06T13:57:28.535101348Z",
    "properties" : {
      "packageName" : "tech.jhipster.beer",
      "projectName" : "beer",
      "baseName" : "beer"
    }
  }, {
    "module" : "prettier",
    "date" : "2022-09-06T13:57:28.537057218Z",
    "properties" : {
      "packageName" : "tech.jhipster.beer",
      "projectName" : "beer",
      "baseName" : "beer"
    }
  }, {
    "module" : "java-base",
    "date" : "2022-09-06T13:57:28.552742172Z",
    "properties" : {
      "packageName" : "tech.jhipster.beer",
      "projectName" : "beer",
      "baseName" : "beer"
    }
  }, {
    "module" : "spring-boot",
    "date" : "2022-09-06T13:57:28.576666967Z",
    "properties" : {
      "packageName" : "tech.jhipster.beer",
      "projectName" : "beer",
      "baseName" : "beer"
    }
  } ]
}
```

**Comment by hdurix** [comment]
> https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/prettier/.lintstagedrc.js -> don't have eslint by default, as eslint is used by the front

I didn't think this would not work as we don't have any ts or vue file. But you're right, this is not working after `git init`. We have to do it a bit differently: add this line when generating a front-end (and `vue` files only for vue :smiley:).

> `{,src/**/}` should be `{,src/**/,}` instead

I think it can be `{src/**/,}`

And I've found another bug while testing it: when nothing is selected for `endOfLine` parameter, this seems not working.

**Comment by pascalgrimaud** [comment]
bounty claimed: https://opencollective.com/generator-jhipster/expenses/99050
cc @DanielFran :)

**Comment by DanielFran** [comment]
@pascalgrimaud Approved
