### ISSUE TITLE
Fix: Notification don't disapear on there own

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3432]
In the current version user notifications don't disappear until you click it, cc @Gnuk can you take it?

**Comment by Gnuk** [comment]
Yes, that's what I said on the remove bootstrap ticket. This was intentional to remove the bootstrap js behavior. So it's possible to implement it.

**Comment by Gnuk** [comment]
Is  3 seconds OK for you?

**Comment by DamnClin** [comment]
Hum, I think this should depend on the number of words in the message :⁠-⁠)

**Comment by Gnuk** [comment]
So, how many time using words ?

**Comment by DamnClin** [comment]
Mean reading speed is 200 words / mn so taking that into account and adding 1.5s so people notice the notification seems legit
