### ISSUE TITLE
JHipster Lite Logo

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#347]
The logo should be added to this project https://github.com/jhipster/jhipster-artwork

Then in the current README, we will be able to use the link

The work is already started by @sabrinapayet

**Comment by pascalgrimaud** [comment]
Adding a bounty as I know you spent hours to do this!
Thanks a lot!

**Comment by sabrinapayet** [comment]
Bug bounty claim : https://opencollective.com/generator-jhipster/expenses/73693

**Comment by pascalgrimaud** [comment]
@sabrinapayet : approved
