### ISSUE TITLE
Module to make custom JHLite instance

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3482]
Create a module to make custom JHLite instances to allow custom modules.

TODO: 

- [x] Deploy releases on maven central (cc @pascalgrimaud);
- [ ] Make the module.

In fact the module is pretty simple, it needs:

- The JHLite dependency;
- An updated main class with `@SpringBootApplication(scanBasePackageClasses = { JHLiteApp.class, JHipsterCustomApp.class })`
- Some documentation.

**Comment by pascalgrimaud** [comment]
Cc @avdev4j : we should discuss about this

**Comment by hdurix** [comment]
Good idea :+1: 

It would be easy to customize the common JHipster Lite!

**Comment by pascalgrimaud** [comment]
@jdubois : can you help here as you're the admin in the sonatype orga? I wonder if we can already publish this artifact or should we do a new request?

**Comment by pascalgrimaud** [comment]
@jdubois : no I want to publish to maven central, managed by sonatype (not sonarcloud)

**Comment by jdubois** [comment]
Oh sorry! Sonar/Sonatype this is confusing... As long as it's in the same groupId (tech.jhipster) I think you can directly push, and it will create a new project in that groupId. I can then check in the UI and give you statistics.

**Comment by pascalgrimaud** [comment]
Thanks, I'll try to publish it, so :-)

**Comment by pascalgrimaud** [comment]
Good news, it seems to work:
- https://oss.sonatype.org/content/repositories/snapshots/tech/jhipster/

I'm preparing the other PRs to update the current `pom.xml`

**Comment by pascalgrimaud** [comment]
I'm adding the bounty on the 2nd part: the module to generate this project.
This part can be done only after the release

**Comment by pascalgrimaud** [comment]
I manage to init the repository, but I think it needs to be validated.

@jdubois : can you log and have a look at https://oss.sonatype.org/#stagingRepositories plz ?

![image](https://user-images.githubusercontent.com/9156882/190249199-790493fb-3bc2-4602-ad84-663fe5bf5a12.png)

**Comment by pascalgrimaud** [comment]
And if I go to https://oss.sonatype.org/service/local/staging/deploy/maven2/tech/jhipster/lite I have this error:

```xml
<nexus-error>
<errors>
<error>
<id>*</id>
<msg>Staging of Repository within profile ID='58b316c0f54bc' is not yet started!</msg>
</error>
</errors>
</nexus-error>
```

**Comment by pascalgrimaud** [comment]
Maybe try to release it:

![image](https://user-images.githubusercontent.com/9156882/190250069-436b1e3e-2b70-416d-8973-586df9b72a8a.png)

**Comment by pascalgrimaud** [comment]
I found the documentation about the workflow here : https://help.sonatype.com/repomanager2/staging-releases/managing-staging-repositories

**Comment by DamnClin** [comment]
The published jar is a spring boot style jar: that mean we can't really use it as a dependency since we won't have access to the JHLite classes.

We can decide to: 

* Publish a "classic" jar;
* Publish a spring-boot AND "classic" jar using [maven-jar-plugin](https://blog.engineering.publicissapient.fr/2019/04/01/import-spring-boot-application-as-a-maven-dependency)/;

Publishing the spring-boot jar don't seems to make a lot of sense since we already have a published docker image and the possibility to download it from github releases.

@pascalgrimaud what do you think? Any other impact I missed?

**Comment by avdev4j** [comment]
hi @DamnClin 
Does that mean we can use this to generate empty modules to create our own? A kind of module starter, or something else? 

Sorry if my question seems to be weird but I wanted to be sure ;-)

**Comment by DamnClin** [comment]
Not really. The goal is to be able to deploy an application and add custom JHLite modules without adding them to the open source project.

It is designed to allow custom modules in organizations. Ex: you are [entando](https://www.entando.com/) and want to deploy an instance without the module you don't support and with some specific modules.

**Comment by DamnClin** [comment]
Claimed https://opencollective.com/generator-jhipster/expenses/96567

**Comment by pascalgrimaud** [comment]
@DamnClin : approved
