### ISSUE TITLE
Suggestion: rename BusinessContext to BoundedContext

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3540]
suggested by @onepunchmagne 

cc @DamnClin : what do you think?

**Comment by DamnClin** [comment]
I don't like it since it is not a BoundedContext so I don't really get the idea here

**Comment by pascalgrimaud** [comment]
The discussion with @onepunchmagne was related to this : https://github.com/jhipster/jhipster-lite/tree/main/src/main/java/tech/jhipster/lite/technical

As it can look strange to have a BusinessContext package-info in a Technical package

**Comment by pascalgrimaud** [comment]
No other comment since months
So I'm fine to keep BusinessContext. Anyway, it can be renamed easily in the generated project, so no problem for that

Let's close this, as we have more important ticket
