### ISSUE TITLE
Publish JHLite docker image during releases

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3578]
Creating and publishing a docker image can be a good idea to ease local running for newcomers. What do you think @pascalgrimaud ?

**Comment by pascalgrimaud** [comment]
Unless I'm wrong, it's already done:
https://hub.docker.com/r/jhipster/jhipster-lite

**Comment by pascalgrimaud** [comment]
Just checked, it's already done too :-)
We could add a Docker Hub badge, because it's beautiful
