### ISSUE TITLE
Rename ehcache group to cache

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3598]
Rename ehcache **group** to cache, as it will contain other cache system (Caffeine, Memcache, etc.)

These modules won't change:
- ehcache-with-java-config
- ehcache-with-xml-config

![image](https://user-images.githubusercontent.com/9156882/190969295-70b749c6-7ecd-49cd-8893-b25965eedfb7.png)

**Comment by DamnClin** [comment]
I don't think all caches should be in the same **feature**. It is totally possible to have multiple cache mechanisms in the same app (ex: a local Caffeine and a shared ehcache)

**Comment by pascalgrimaud** [comment]
Agree with you but I think it's not too common to use 2 different caches in real projects

So for our use cases, I would suggestion to restrict to 1 cache (group) here. Then, if the user want another cache, he/she can go to the patch page to apply this module as standalone

WDYT ?

**Comment by DamnClin** [comment]
Personally I don't care, I don't often use caches (I prefer simple memoiziers)

**Comment by pascalgrimaud** [comment]
Ok then, I'll do this ticket soon so I could start later the Hibernate cache
