### ISSUE TITLE
JHLite: upgrade and test Spring Boot v3.0.0-MX

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3601]
Linked to:
- https://github.com/jhipster/jhipster-lite/issues/1041
- https://github.com/jhipster/jhipster-lite/pull/1042

The post blog:
- https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0

The goal is to start to upgrade the JHLite to Spring Boot 3
It's not for the generated applications, which can be done in another PR.

**Comment by pascalgrimaud** [comment]
Adding a bounty on this, in case of someone is motivated to give it a try

**Comment by pascalgrimaud** [comment]
I have something working but encountered some issues, related to Springdoc.

Here what is working:
- Spring Boot 3.0.0-M5 + Springdoc 2.0.0-M6-SNAPSHOT
- Spring Boot 3.0.0-M4 + Springdoc 2.0.0-M5

Will submit a PR soon

**Comment by pascalgrimaud** [comment]
Still some issue when running integration tests, because of mongodb
Maybe I could push it to a specific branch if someone wants to help

**Comment by pascalgrimaud** [comment]
Bounty claim: https://opencollective.com/generator-jhipster/expenses/116142
cc @DanielFran

**Comment by DanielFran** [comment]
> Bounty claim: https://opencollective.com/generator-jhipster/expenses/116142
> cc @DanielFran 

@pascalgrimaud approved
