### ISSUE TITLE
Add eslint config to .lintstagedrc.js

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3646]
Following these ticket / pull request:
- https://github.com/jhipster/jhipster-lite/issues/3424
- https://github.com/jhipster/jhipster-lite/pull/3645

When adding a front, we need to:
- check if `.lintstagedrc.js` exist
- then add `  '{,src/**/}*.{js,ts,tsx,vue}': ['eslint --fix'],`

The file should look like:

```javascript
module.exports = {
  '{src/**/,}*.{js,ts,tsx,vue}': ['eslint --fix'],
  '{src/**/,}*.{md,json,yml,html,css,scss,java,xml}': ['prettier --write'],
};
```

**Comment by murdos** [comment]
Hi! I'll try to handle this one, in order to acquaint myself with jhispter-lite generator.

**Comment by pascalgrimaud** [comment]
You're awesome @murdos
