### ISSUE TITLE
Missing start-class properties with Spring Boot

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3748]
Missing start-class property when using Spring Boot module, something similar to:

```xml
<start-class>tech.jhipster.lite.JHLiteApp</start-class>
```

**Comment by swarajsaaj** [comment]
I ll try to look into this.
(quite a lot has changed since my last commit here :), this will help me wrap my head around new system )

**Comment by pascalgrimaud** [comment]
Haha yes, @DamnClin did a crazy work by refactoring the entire engine, so it should be simpler than before :-)

**Comment by pascalgrimaud** [comment]
I'm changing the label
It's not really a bug as it works fine currently, it's more an improvement so no red line in the IDE :-D
