### ISSUE TITLE
Upgrade to Spring Boot 3 for generated app

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3750]
The work can be done in a dedicated branch

Feel free to start the work and doing this, modules per modules if it's easier, and link each Pull Request to this ticket

I can add some bounties, directly in Pull Request, if it deserves :-)

**Comment by pascalgrimaud** [comment]
As our current version of JHLite uses mongock, I wonder if the support for Spring Boot 3 works?
It seems not, can you confirm @dieppa ?

**Comment by osantana85** [comment]
Hello @pascalgrimaud , currently Springboot 3 is not "officially" supported by Mongock, but we’ll take a look next week and let you know if some changes are needed and when will be possible to release a new version with them. Thanks!

**Comment by DamnClin** [comment]
Removing mongock from JHlite is also an option!

**Comment by dhivesh** [comment]
Hi @pascalgrimaud  , @DamnClin, thanks for raising this.

We are prioritising this issue under https://github.com/mongock/mongock/issues/583 and will pick it up tomorrow. If we encounter issues, we'll comment in this thread and make a patch release to enable this asap.

Are there any specific timelines you are looking at?

FYI: @dieppa

**Comment by pascalgrimaud** [comment]
No worry, take your time, as it's open source :-)
Thanks a lot

**Comment by dieppa** [comment]
@pascalgrimaud , I haven't tested myself just yet(I will try today), but I think it needs to be compiled for Java17.

Will keep you updated!

**Comment by pascalgrimaud** [comment]
Yes, JHLite needs Java 17, it's mandatory :-D

**Comment by dieppa** [comment]
I missed the word "only", `... think it ONLY needs to be compiled for Java17`. The good think is that, in our pipeline, we already are testing it against Java17, so that should be straight forward, just having a separate artefacts :)

**Comment by dieppa** [comment]
I continue the comments regarding Mongock in this [issue](https://github.com/jhipster/jhipster-lite/issues/4067)
