### ISSUE TITLE
React: Move to vitest

### ISSUE THREAD

**Issue by qmonmert** [jhipster/jhipster-lite#3751]

**Comment by pascalgrimaud** [comment]
@qmonmert : it can be interesting but is Vitest ready enough ? The last time I check, it was still in active development and it was suggested to not be used in real project with prod

**Comment by qmonmert** [comment]
yes maybe we can wait v 1.0.0 🙂

**Comment by qmonmert** [comment]
PR ✅ with 0.23.4 version of `vitest`

**Comment by pascalgrimaud** [comment]
I'll test it and I think we can go

**Comment by qmonmert** [comment]
ok 🙂

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/100748

**Comment by pascalgrimaud** [comment]
@qmonmert : approved, thanks for your work :-)
