### ISSUE TITLE
Default error page with server app

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3803]
When using tomcat, undertow or netty, we should add a default error page similar to what generator-jhipster provides

**Comment by DamnClin** [comment]
As always the problem is is to have a decent UI for that, still lacking contributors able to do that

**Comment by pascalgrimaud** [comment]
we could take the same page in generator-jhipster, it will be better than nothing
And I think it's an easy ticket

**Comment by DamnClin** [comment]
It would be really missleading since on the information on this page don't work at all for JHLite

**Comment by pascalgrimaud** [comment]
same page, with some update/changes of course, don't worry ;)

**Comment by Yachef** [comment]
Hello guys,

I'm up for that issue :). I'm quite new to jhipster & jhipster-lite so I'm gonna need some help please :).

To be clear, the goal is to replace this screen :
<img width="596" alt="image" src="https://user-images.githubusercontent.com/28443066/197487817-637daeb5-ac66-47c0-ba23-afd880ff06e2.png">

When I tried to generate a project without frontend with generator-hipster, I got that screen, I'm not sure if, based on your discussion above that this the target for jh-lite too : 
![image](https://user-images.githubusercontent.com/28443066/197487672-0e913fed-804d-464c-a2d1-533c2d4d9db8.png)

Thanks

**Comment by pascalgrimaud** [comment]
I think it's a good start, to use the same page in generator-jhipster
so yes ! let's do it and use this same page :)
