### ISSUE TITLE
Prettier hook after each module

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3805]
The prettier hook applied after each module instead of 1, so it's a little bit slow
I wonder if we can apply it only at the end of all modules, instead of each

**Comment by DamnClin** [comment]
That mean doing one commit for all module instead of one for each module and I don't think this is a good idea

**Comment by pascalgrimaud** [comment]
Yes, maybe it's not easily doable
Let's keep this opened, maybe we can have some ideas later

**Comment by DamnClin** [comment]
I don't think it will do that much since prettier only format the updated files

**Comment by pascalgrimaud** [comment]
Here the reason why I created this ticket initialy: https://youtu.be/RnLGnY-vzLI?t=1890

But as you said, not sure we can do something as it's directly related to git commit hook

**Comment by DamnClin** [comment]
In fact I'm not sure that playing the hook only once will be really faster since it's formatting the updated files

**Comment by pascalgrimaud** [comment]
In fact, I though it was prettier:format the problem, but no, it's the hook!
Let's close this, as it's not so important, we can rethink later if it's a real problem :)
