### ISSUE TITLE
Enums module

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3826]
Create a module to add the `Enums` class (from JHLite) in apps

**Comment by cemdrman** [comment]
How can I begin to this issue? Can you help me? I'm new one for this project.

**Comment by DamnClin** [comment]
Hello,

So, first things first you'll need to follow the [contributing guide](https://github.com/jhipster/jhipster-lite/blob/main/CONTRIBUTING.md). 

Then, the goal is to [make a module](https://github.com/jhipster/jhipster-lite/blob/main/documentation/module-creation.md) with [Enums.java](https://github.com/jhipster/jhipster-lite/blob/main/src/test/java/tech/jhipster/lite/common/domain/EnumsTest.java) ant [EnumsTest.java](https://github.com/jhipster/jhipster-lite/blob/main/src/test/java/tech/jhipster/lite/common/domain/EnumsTest.java).

**Comment by amrutp28** [comment]
Hi @DamnClin I am new to project. Can I start with this issue?

**Comment by DamnClin** [comment]
> Hi @DamnClin I am new to this project. Can I start with this issue?

I think @cemdrman wants to take it, while waiting for response on his side you can tell me the kind of issue you are looking for and I may be able to redirect you to a suited one :)

**Comment by amrutp28** [comment]
Thanks for the quick response. I am looking for the java or spring boot related issues.

**Comment by DamnClin** [comment]
You can have a look at https://github.com/jhipster/jhipster-lite/issues/3974 to get a quick understanding of templates or https://github.com/jhipster/jhipster-lite/issues/3684 to go a little bit further and update a module (so some module manipulation).

If you want to build a new module there's that one https://github.com/jhipster/jhipster-lite/issues/877 but this is a big one if you don't know Cassandra already (you can generate and app with generator-jhipster with cassandra and start from here). I can think of a smaller spring module if you want :)

**Comment by DamnClin** [comment]
Just created https://github.com/jhipster/jhipster-lite/issues/3990 that may be in your criteria

**Comment by cemdrman** [comment]
thanks @DamnClin. yes I'm working on this issue

**Comment by cemdrman** [comment]
@DamnClin hi, i have a few question.

1. following packages are created by me, are these true?
-  tech.jhipster.lite.generator.enums.domain;
-  tech.jhipster.lite.generator.enums.application;
- tech.jhipster.lite.generator.enums.primary;

2. in factroy, below conf is true? and how can I write to test about it? what is the validation and can you give me sample please? thanks for your help
 .add(SOURCE.template("Enums.java"), toSrcMainJava().append(properties.packagePath()).append("common/domain").append("Enums.java"))

**Comment by DamnClin** [comment]
1. Yes, (with an annotated package-info.java at package root)
2. Tests strategy and samples are described in the [module creation documentation](https://github.com/jhipster/jhipster-lite/blob/main/documentation/module-creation.md)

**Comment by cemdrman** [comment]
I can't fix test 😢 do I need to move Enums.java to my module

**Comment by DamnClin** [comment]
You need to make templates (`.mustache`) files for your module and to put those templates in `src/main/resources/generator/something`. The templated `Enums` class won't be the exacted same one since we won't be using the same exception and you need to template the package :)

**Comment by DamnClin** [comment]
You can have a look at this PR https://github.com/jhipster/jhipster-lite/pull/3689/files for the memoizers module which idea is really close to the `Enums` module
