### ISSUE TITLE
Angular: use single version in dependencies

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3836]
Following https://github.com/jhipster/jhipster-lite/pull/3835 and several other PRs, it would be cool to:
- add a single version of angular in dependency package.json
- use this same version for all other libs

Pro:
- less dependabot upgrade
- no need to manually do a PR to upgrade Angular

**Comment by A-5ingh** [comment]
@pascalgrimaud Can you please provide more insights on this change?

**Comment by pascalgrimaud** [comment]
Just to warn you, it's not an easy ticket :)

As you can see in this code https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactory.java#L19-L28

For each lib, it will go into this https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/dependencies/angular/package.json and find the version associated to the lib

Because of that, dependabot will try to bump the dependencies separately so it won't work.

The goal here is to find a mechanism to use a single version, but for now, I don't know how.
Maybe something like :

```java
  NpmPackageVersion angularVersion = retrieveVersion("@angular/core", ANGULAR);

  return ClientsModulesFactory.clientModuleBuilder(properties)
      .packageJson()
        .addDependency(packageName("@angular/animations"), angularVersion)
        .addDependency(packageName("@angular/cdk"), ANGULAR)
        .addDependency(packageName("@angular/common"), angularVersion)
        .addDependency(packageName("@angular/compiler"), angularVersion)
        .addDependency(packageName("@angular/core"), angularVersion)
```

I think @DamnClin can have some better ideas as it will impact the engine of JH Lite: maybe you can help here?

**Comment by A-5ingh** [comment]
Thanks, @pascalgrimaud. Yes, it's an interesting problem and I'm up for a challenge on weekends. :) I'll get familiar with `jhipster-lite` in the meantime we wait for response from @DamnClin.

**Comment by DamnClin** [comment]
I think adding a signature with source and package source may be more consistent with the java ones using version slug

**Comment by murdos** [comment]
I'm picking this ticket, in order to reduce the burden of manual dependencies upgrade.

I'm inclined to the following API, with an additional optional PackageName corresponding to the source of the version:
```java
  return ClientsModulesFactory.clientModuleBuilder(properties)
      .packageJson()
        .addDependency(packageName("@angular/animations"), ANGULAR, packageName("@angular/core"))
        .addDependency(packageName("@angular/cdk"), ANGULAR, packageName("@angular/core"))
        .addDependency(packageName("@angular/common"), ANGULAR, packageName("@angular/core"))
        .addDependency(packageName("@angular/compiler"), ANGULAR, packageName("@angular/core"))
        .addDependency(packageName("@angular/core"), ANGULAR)
```

**Comment by murdos** [comment]
I just noticed that dependabot is now supporting grouping dependencies updates: https://github.com/dependabot/dependabot-core/issues/1296
I think #7397 is anyway a nice feature to have for module, but I'll give a try for grouping furthermore dependencies updates since it could also help to group dependencies together that don't share the same version number.

**Comment by pascalgrimaud** [comment]
Increasing the bounty as it was more work than expected
thanks a lot @murdos, it will help a lot

**Comment by murdos** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/160366

**Comment by pascalgrimaud** [comment]
@murdos : approved
