### ISSUE TITLE
Vitest + Coverage

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#3892]
In current main branch, when generating app, using React or Svelte, the coverage is well displayed.
Anyway, if the coverage is under some value, there is no error output, so the `mvn clean verify` is success, and it should not

- it was detected by https://github.com/jhipster/jhipster-lite/pull/3866

cc @qmonmert

**Comment by qmonmert** [comment]
@pascalgrimaud we can close this ticket?

**Comment by pascalgrimaud** [comment]
yes !
