### ISSUE TITLE
Add videos in documentation

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3932]
Add those 2 videos in documentation (readme?)

* https://youtu.be/dTzGQNOKWug
* https://youtu.be/mEECPRZjajI

**Comment by pascalgrimaud** [comment]
Yes, maybe here too https://www.jhipster.tech/jhipster-lite/
It means updating this page https://github.com/jhipster/jhipster.github.io/blob/main/pages/jhipster-lite.md
