### ISSUE TITLE
Add "anchor points" in landscape

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3966]
The idea is to add "anchors", like in GitHub graphs (ex: https://github.com/jhipster/jhipster-lite/actions/runs/3254882914. Those anchors are really good for readability.

They should react like the related connectors

**Comment by swarajsaaj** [comment]
Hi @DamnClin ,
By anchors do you mean these touchpoints?
![image](https://github.com/jhipster/jhipster-lite/assets/6285049/bfeab3cd-d021-4038-92c2-448a946ec14a)

**Comment by DamnClin** [comment]
Yep, I think this could add something as long as they follow the same rules as the lines (on hover, selection etc).

We have to pay attention to the full screen render cost since there were problem with it in the past

**Comment by pascalgrimaud** [comment]
looks nice for me :)

**Comment by abdelfetah18** [comment]
https://opencollective.com/generator-jhipster/expenses/173494
