### ISSUE TITLE
Refactoring: remove indentation management

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#397]
Do not allow changing default indentation.
Let's keep the default value to 2 for all. It will make all code simpler, and less config to test

**Comment by pascalgrimaud** [comment]
This is related to the indentation of sonar plugin:

```xml
        <plugin>
        <groupId>org.sonarsource.scanner.maven</groupId>
        <artifactId>sonar-maven-plugin</artifactId>
        <version>${sonar-maven-plugin.version}</version>
      </plugin>
      <!-- jhipster-needle-maven-add-plugin-management -->
      </plugins>
    </pluginManagement>
  </build>
</project>
```

This is because the indentation of plugin is different between default plugins and pluginManagement/plugins

**Comment by swarajsaaj** [comment]
> This is because the indentation of plugin is different between default plugins and pluginManagement/plugins

Yes and `pluginsManagement/plugins` is one step ahead, so a common `getPlugin` is not possible. If i understand correclty, are you suggesting to use only prettier for this formatting and not using java?

**Comment by pascalgrimaud** [comment]
For this little indentation problem, we could code a getPluginManagement

About removing the possibility of changing indentation, it is for simplifying our based code:
- no need to test indentation=2 and indentation=4
- simpler for regexp
- simpler for applying git patch
- etc

**Comment by pascalgrimaud** [comment]
Let's close this for now, as the issue has been fixed
