### ISSUE TITLE
Refactor CustomClaimConverter

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3973]
Some pain points: 

* The rest access is done without any timeout (this can quickly be a real problem);
* The users cache is not really easy to understand, using a memoizer (from `java-memoizers`) can be a good idea.

**Comment by atomfrede** [comment]
In the main generator we have replaced the map with a node/instance local caffeine cache (to prevent the map from growing indefinitely), maybe we can do the same here and of courser the timeout is 👍 May we should have that in the main generator too.
