### ISSUE TITLE
Refactor ExceptionTranslator

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3975]
`ExceptionTranslator` is really hard to understand and should be refactored (in JHLite and in generated applications)

**Comment by pascalgrimaud** [comment]
I would suggest to do it with Spring Boot 3
Some good links here: https://github.com/jhipster/generator-jhipster/issues/19991

**Comment by DamnClin** [comment]
Ok, we should also do https://github.com/jhipster/jhipster-lite/issues/2794 in the same ticket so (while we are at it)
