### ISSUE TITLE
Rework ehcache modules to work with spring-boot-cache

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3982]
ehcache modules are not really working along with `spring-boot-cache` since they are copy / past from JHipster ehcache integration. We can add a dependency between modules and update the generated code to have an `EHCacheConfiguration.java` file along with `CacheConfiguration.java` (so we keep things modular)

**Comment by pblanchardie** [comment]
The first PR I made was a refactoring with three separate layers (modules) : Cache, JCache and Ehcache (allowing other implementations of JCache with few to no code), with a dependency between modules. @pascalgrimaud was not a big fan and we decided to revert to a copy and paste of the existing approach, without dependencies between multiple modules.

I kept the old branch and I can suggest a PR.

Initially, I thought JHipster Lite would keep entity generation features so I kept the createCache methods with entity needles, and @pascalgrimaud said we can keep them in case it is used with JHipster but I'm not sure it's still the way to go. Should we remove these helper methods and needles?
