### ISSUE TITLE
Add criteria in stats

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3988]
The current stats endpoint is really simple, we can add some criteria: 

* start time
* end time
* module slugs

**Comment by ayushdubey755** [comment]
@DamnClin  Can I work on this issue?
thank you for your insightful comment is there anything else should I know as the first time contributing to this project, I would love to work on it

**Comment by DamnClin** [comment]
I think you should focus on one issue to start :⁠-⁠)

**Comment by kartiktayal** [comment]
Hi @DamnClin , will it be possible for me to pick this one?
I think I should be able to work on it and complete the requirement.

**Comment by DamnClin** [comment]
No problem :)

**Comment by kartiktayal** [comment]
Can you share the endpoint with me if it is not too much trouble to get a headstart?

**Comment by DamnClin** [comment]
`StatisticsResources`

**Comment by kartiktayal** [comment]
@DamnClin , when we say we want to add criteria to the endpoint, we are now introducing the above as request parameters, are we expected to return date and module slugs as well in the API response?
or we just need to filter the data on the basis of criteria and return the AppliedModules count?

**Comment by DamnClin** [comment]
Filter data

**Comment by kartiktayal** [comment]
@DamnClin , I am almost done with my changes but I am facing an issue with test containers where I am getting the error as 

Errors: 
[ERROR]   MongoDBStatisticsRepositoryIntTest.startMongo:57 » IllegalState Could not find a valid Docker environment. Please see logs and check configuration

I have tried a lot of things but it is not working. Maybe you have experienced it in the past.
I am using a Ubuntu machine.
