### ISSUE TITLE
Display applied modules count in header

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3989]
We can display the number of applied modules in header using the modules statistics

**Comment by nassimerrahoui** [comment]
Hello :)
I would like to try to contribute with this first issue if it is possible. I intent to just display the applied modules count in header without refresh it in real time if you are agree with that.

**Comment by DamnClin** [comment]
> Hello :) I would like to try to contribute with this first issue if it is possible. I intent to just display the applied modules count in header without refresh it in real time if you are agree with that.

Yep, totally!

**Comment by nassimerrahoui** [comment]
Here it is :

<img width="1427" alt="desktop" src="https://user-images.githubusercontent.com/23552990/196403414-2d6aeb74-41d2-4d0f-90ae-edafc8e881dd.png">

<img width="399" alt="mobile" src="https://user-images.githubusercontent.com/23552990/196403439-a0dc1fa2-c12a-4169-8cca-258ff0ed234b.png">

**Comment by pascalgrimaud** [comment]
I find a bit strange the information in the navbar.
For me, the navbar should not be used for displaying this kind of information. But I don't know where to put it

**Comment by nassimerrahoui** [comment]
I tried to put this next to the logo but it was more strange : /

**Comment by nassimerrahoui** [comment]
IMO, it is not surprising to have this in the navbar like this. Also, it will be too much if we add a specific style juste for one statistic.

Maybe the need is to have another place dedicate to display some stats.

**Comment by DamnClin** [comment]
> Maybe the need is to have another place dedicated to display some stats.

Later, the plan is to have a dedicated page with stats over time for the instance. For now I wanted to start with that and have a simple counter on https://lite.jhipster.tech (dunno if the mongoDB is deployed on this instance, cc @jdubois)

**Comment by nassimerrahoui** [comment]
It seems that there is something returned by https://lite.jhipster.tech/api/statistics

**Comment by DamnClin** [comment]
Yep but that may be the InMemoryRepository responding :D

**Comment by nassimerrahoui** [comment]
> Yep but that may be the InMemoryRepository responding :D

Oh okay, you are probably right because yesterday it was marked about 400 and now it is marked about 80

**Comment by jdubois** [comment]
Sorry, the Mongo DB part isn't set up yet.
I changed a few things in the way we handle file storage, and realised that the performance is bad, I also need to look at this.

**Comment by pascalgrimaud** [comment]
Isn't it better to use a classic SQL database, like PostgreSQL for that ?

**Comment by jdubois** [comment]
I wanted this because we have a free tier for Cosmos DB, that supports MongoDB... well now there's also PostgreSQL support, I need to check what would make sense

**Comment by pascalgrimaud** [comment]
@nassimerrahoui : I tried but it is still strange for me in the navbar, which should be used to change page, navigate etc, not for this kind of information

I would suggest 2 places:
- near the button, near the other count applied
- similar information like compated / extended, but at another place

![image](https://user-images.githubusercontent.com/9156882/197200827-5fee688e-fbd7-4e67-9ea2-a94d970e8dd8.png)

What do you think ?

**Comment by nassimerrahoui** [comment]
> @nassimerrahoui : I tried but it is still strange for me in the navbar, which should be used to change page, navigate etc, not for this kind of information
> 
> I would suggest 2 places:
> 
> * near the button, near the other count applied
> * similar information like compated / extended, but at another place
> 
> ![image](https://user-images.githubusercontent.com/9156882/197200827-5fee688e-fbd7-4e67-9ea2-a94d970e8dd8.png)
> 
> What do you think ?

I'm agree with that the navbar should be only for navigation. It can be placed like compated / extended and at another place like your previous screenshot, I guess.

Near the other count may be confusing with the current project properties.

**Comment by pascalgrimaud** [comment]
agree for the solution 1 so :D
