### ISSUE TITLE
JHLite: Spring Boot 3 - remove Zalando and use custom ControllerAdvice

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4066]
Links:
- https://github.com/jhipster/jhipster-lite/issues/3601
- https://github.com/jhipster/jhipster-lite/pull/3832

You can use this branch: https://github.com/jhipster/jhipster-lite/tree/spring-boot-3 and submit a pull request against this branch

**Zalando should be removed and ExceptionTranslator should be reworked**

Then, it should fix the following tests:
- ForcedProjectFolderPrefixIntTest
- ExceptionTranslatorIT
- CucumberTest

![image](https://user-images.githubusercontent.com/9156882/197210925-67170560-1e5a-4ce1-bdbd-57377ceffded.png)

**Comment by DamnClin** [comment]
I think we should updated the error management to handle internationalized error on the server side (so it can be tested) as described in https://github.com/jhipster/jhipster-lite/issues/2794

**Comment by biergit** [comment]
Which module should provide the `ExceptionTranslator` ? Should this not be in a dedicated `web-exception-handling` module?

**Comment by pascalgrimaud** [comment]
@biergit : yes, it should be done in a dedicated module, replacing the current one, Zalando problem
