### ISSUE TITLE
Gradle support: init and wrapper

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#408]
Similar to what was done for Maven

**Comment by atomfrede** [comment]
@pascalgrimaud Started to look into it recently. Some question popup. Right now the `BuildToolService` interface contains e.g. `addParent(...)` or `addPluginManagement(...)` while the second one has a quite similar thing in gradle imho, there is no such thing as parent pom. How would you handle such cases where two options are not supporting the same things? Would it be okay to throw something like a "MethodNotSupported" exception? Or do you prefer to extract the maven/gradle specific things into own subinterfaces?

**Comment by pascalgrimaud** [comment]
@atomfrede : thanks for looking into this. I'm not a Gradle user at all, so your ideas are really welcome here.

After playing a little bit with Spring Initializr, indeed there is no parent with Gradle
So I think:
- in build tool at https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/buildtool/generic/domain/BuildToolDomainService.java#L25 we can remove the exception and ignore it for Gradle
- same thing for plugin management

**Comment by pascalgrimaud** [comment]
I should open a new ticket for:
- init project with gradle (minimal libs and config files)

This ticket can be used for adding utils methods but it can be done in several PRs

**Comment by pascalgrimaud** [comment]
So the scope of this ticket has changed, it would be only for adding:
- properties files
- gradle wrapper

Nothing more, so the user can use:
- init
- gradle
- then code a new lib in Java, for example

**Comment by atomfrede** [comment]
Guess this can be closed now.

**Comment by pascalgrimaud** [comment]
Yes it's done !
