### ISSUE TITLE
zalando problems with spring-boot-webflux-netty does not compile

### ISSUE THREAD

**Issue by biergit** [jhipster/jhipster-lite#4111]
`ExceptionHandler` requires `HttpServletRequest` which is not available.

**Comment by pascalgrimaud** [comment]
Adding a bounty for this bug

**Comment by Yachef** [comment]
It looks like right now zalando-problems-spring-webflux is setup by default when using spring-boot-webflux.
When adding zalando-problems module to an existing spring-boot-webflux project, it generates the configuration for the web (not webflux), which causes the compilation error.

I think we have two solutions : 
- Disable the dependency zalando-problems -> spring-boot-webflux, as, by default, spring-boot-webflux comes with zalando-problems
OR
- Remove zalando-problems-spring-webflux from the spring-boot-webflux module. And then extract its logic to the zalando-problems existing module (which will have two implementations : one for web, another for webflux)

**Comment by Yachef** [comment]
> The spring boot webflux shouldn't come with zalando by default, so it should be clean. The 2nd solution is the good one But keep in mind we're migrating to Spring Boot 3, so I don't think Zalando should be implemented for Webflux.
> 
> So I would suggest:
> 
> * in webflux module, clean zalando
> * in webflux module, if possible, disable the dependency zalando-problems

Noted, working on it :)
