### ISSUE TITLE
Release with jhipster-lite-sample-app

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4119]
Like other sample apps, it could be nice to have this

We need to think which modules should be included:
- PostgreSQL
- Liquibase
- all dummies
- between JWT and OAuth2, I don't know yet

Maybe it's closed to the full app https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/generate.sh#L105

**Comment by pascalgrimaud** [comment]
The work is done.
The sample app will be available at https://github.com/jhipster/jhipster-lite-sample-app after the next release v0.30.0 :-)

cc @renanfranca as you wanted to have this one
So closing this

**Comment by renanfranca** [comment]
> The work is done.
> The sample app will be available at https://github.com/jhipster/jhipster-lite-sample-app after the next release v0.30.0 :-)
> 
> cc @renanfranca as you wanted to have this one
> So closing this

I remember when I asked if this up-to-date sample exists! That's really cool because anyone can try to use a project generated by jhlite without the need to learn how to use the generator! If someone enjoys the sample, they will be motivated to dig into the project 👏👏👏👏
