### ISSUE TITLE
Move Base64Utils to common

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4120]
See https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/base64/domain/Base64Utils.java

It should belong to https://github.com/jhipster/jhipster-lite/tree/main/src/main/java/tech/jhipster/lite/common/domain

**Comment by DamnClin** [comment]
Why? I think shared kernel must remains as think as possible, this one looks fine

**Comment by pascalgrimaud** [comment]
Maybe I'm wrong but I see several pro:
- this class is too 'common' and is not related to 'generator' context
- can be copy/paste to other projects
- reduce by 1 folder the size of generator/ folder

**Comment by DamnClin** [comment]
Hum, it's only used in some modules (so it belong to generator), we don't need it in JHLite "engine". I mustn't be copy / pasted since it's really not good :D and folder don't come with a great cost

**Comment by pascalgrimaud** [comment]
not so important ticket, it was for new contributor, let's close this
