### ISSUE TITLE
Public sample JHLite custom

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4122]
It could be nice if we can have some public sample JHLite custom as a use case

I have some idea:
- java tools: adding some utils like Base64Utils, StringUtils, DateUtils, etc
- banners with specific files
- maybe quarkus, but I don't want to lead this. Maybe @avdev4j I don't know

Cc @DamnClin too, as you're the lead on JHLite custom

TO-DO
- [x] add banner modules with `-extension` sufix at the `jhipster-lite-extension` project (https://github.com/jhipster/jhipster-lite-extension/pull/1)
- [x] remove banner modules from `jhipster-lite` (https://github.com/jhipster/jhipster-lite/pull/10067)
- [x] wait to release a new version of `jhipster-lite` (https://github.com/jhipster/jhipster-lite/issues/4122#issuecomment-2171770743)
- [x] upgrade the jhipster-lite version and remove the `-extension` sufix from banner modules name at the `jhipster-lite-extension` (https://github.com/jhipster/jhipster-lite-extension/pull/30)
- [x] https://github.com/jhipster/jhipster-lite-extension/issues/25
- [ ] https://github.com/jhipster/jhipster-lite-extension/issues/24

**Comment by pascalgrimaud** [comment]
@DamnClin : I know you play with a JHLite custom instance. Do you have a public one ? Do you have some ideas to create a sample of it ?
The goal is to create one, let dependabot update it, and be sure it works well, using the CI

**Comment by DamnClin** [comment]
> @DamnClin : I know you play with a JHLite custom instance. Do you have a public one ? Do you have some ideas to create a sample of it ? The goal is to create one, let dependabot update it, and be sure it works well, using the CI

No, it's not public (and absolutely can't be, it's for a context under very heavy legislation constraints). I have 0 availability to do it but, perhaps @murdos have an idea (since he will also use this custom JHLite instance :D)

**Comment by pascalgrimaud** [comment]
@DamnClin : any feedbacks on this private instance? Does JHLite custom work well ?

**Comment by DamnClin** [comment]
> @DamnClin : any feedbacks on this private instance? Does JHLite custom work well ?

No problem for now, we have like 8 custom modules doing different stuff and everything is good for now

**Comment by murdos** [comment]
> No, it's not public (and absolutely can't be, it's for a context under very heavy legislation constraints). I have 0 availability to do it but, perhaps @murdos have an idea (since he will also use this custom JHLite instance :D)

Sure, I might be interested on working on a simple custom jhlite. But for now I'm focusing on making progress on gradle :-)

**Comment by renanfranca** [comment]
@pascalgrimaud: I am going to work on this issue by implementing Quarkus. Will this jhlite-custom-quarkus be published in a new repository?

**Comment by pascalgrimaud** [comment]
@renanfranca : I would say to wait feedbacks from @murdos or @DamnClin as I know they already have something, which is currently not open sourced

**Comment by renanfranca** [comment]
> @renanfranca : I would say to wait feedbacks from @murdos or @DamnClin as I know they already have something, which is currently not open sourced

Cool, @pascalgrimaud! A real-world case is much more interesting 👍

**Comment by murdos** [comment]
@renanfranca : I'm indeed working on custom-jhlite at work, but it'll never been open sourced.
So you can go ahead and create a public custom-jhlite.
You'll need a new repository. I suggest to just name it `jhlite-quarkus` or `jhipster-lite-quarkus`: IMO we don't need to have "custom" in the name, since it can confuse users.

**Comment by renanfranca** [comment]
> @renanfranca : I'm indeed working on custom-jhlite at work, but it'll never been open sourced. So you can go ahead and create a public custom-jhlite. You'll need a new repository. I suggest to just name it `jhlite-quarkus` or `jhipster-lite-quarkus`: IMO we don't need to have "custom" in the name, since it can confuse users.

Thanks @murdos for the feedback. I've mapped out the changes needed to implement Quarkus. The only module that's going to be reused is the 'init'. Even the 'maven-java' sets Spring Boot configurations in the pom.xml. It's basically a whole new jhipster-lite project! That's why, in my opinion, it's not a great example of jhlite-custom because it ignores previous modules and only uses the jhlite engine to generate and show modules.

I am going to work on another issue 👍.

**Comment by pascalgrimaud** [comment]
![image](https://github.com/jhipster/jhipster-lite/assets/9156882/2f2214ab-978c-44b4-9a52-1b2f00e4f015)

@renanfranca : very strange. If you use only init + maven-java, you should not have Spring Boot configuration. Did I miss something ?

**Comment by renanfranca** [comment]
@pascalgrimaud : I generated a project and checked the commit for the maven-java module again, and that was my bad. It does not contain Spring Boot references. I misused the VSCode Git view interface. I am sorry 😅!

So the init + maven-java + java-base could be used as a base module for a jhlite-quarkus project.

**Comment by pascalgrimaud** [comment]
I already used `init + maven-java + java-base` when I want to code a simple Java library, so I know it doesn't need Spring Boot here :)

**Comment by pascalgrimaud** [comment]
after thinking about it, I don't think this custom jhlite should be complex

We could simply migrate the banner module there, that's all.
So with that, we'll have:
- a good example how to implement a JHLite Custom
- no need to maintain it

What do you think @renanfranca ?

**Comment by renanfranca** [comment]
> after thinking about it, I don't think this custom jhlite should be complex\n\nWe could simply migrate the banner modules there, that's all.\nSo with that, we'll have:\n\na good example how to implement a JHLite Custom\nno need to maintain it

I think it's really nice! A "Hello World" that's always up to date. I can work on it after finishing my current issue.

Is it going to be a new repository?

**Comment by pascalgrimaud** [comment]
Yes, it's going to be a new repository, as soon as you want to start it, ping me and I'll create the repo with the correct permission

Then, it will be simply to migrate the banner modules

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/e835cf5b-df0f-444a-97c5-b5d70ed67c2a)

**Comment by renanfranca** [comment]
> Yes, it's going to be a new repository, as soon as you want to start it, ping me and I'll create the repo with the correct permission

@pascalgrimaud : when you have the time, please, create the new repository and I will start it 👍

**Comment by pascalgrimaud** [comment]
what should be the name of the repo ? jhipster-lite-custom ?
since the beginning, I don't like too much the name "custom", but I didn't find a better

**Comment by murdos** [comment]
> what should be the name of the repo ? jhipster-lite-custom ? since the beginning, I don't like too much the name "custom", but I didn't find a better

Maybe `jhipster-lite-sample-extension` or `jhipster-lite-sample-blueprint`?

**Comment by pascalgrimaud** [comment]
I like `jhipster-lite-extension`
I don't want blueprint ... very bad experience with that :-D

**Comment by pascalgrimaud** [comment]
the project is created: https://github.com/jhipster/jhipster-lite-extension

I started to clean the JHipster Teams with appropriate permissions etc

**Comment by renanfranca** [comment]
> the project is created: https://github.com/jhipster/jhipster-lite-extension
> 
> I started to clean the JHipster Teams with appropriate permissions etc

Thank you, @pascalgrimaud 😊

**Comment by renanfranca** [comment]
> remove banner modules from jhipster-lite

I will keep going 😃👍

**Comment by renanfranca** [comment]
@pascalgrimaud : FYI, this issue is on hold waiting to release a new version of jhipster-lite 👍

**Comment by renanfranca** [comment]
Thanks, @pascalgrimaud . I will continue this issue after the weekend 👍

**Comment by pascalgrimaud** [comment]
Finally, I managed to fix the upload to maven central: https://repo.maven.apache.org/maven2/tech/jhipster/lite/jhlite/1.10.0/

**Comment by murdos** [comment]
@pascalgrimaud : can we close this issue? The sonar analysis is tracked by its own issue in https://github.com/jhipster/jhipster-lite-extension

**Comment by murdos** [comment]
BTW @pascalgrimaud, thanks for the bounty! :heart: 
We'll share it with @renanfranca since we have both worked on setting up the custom jhlite.

**Comment by pascalgrimaud** [comment]
Yes we can close, as it's a good example now.
Maybe we could just add a link to the README but it's a detail
Thanks for your work.

**Comment by murdos** [comment]
@pascalgrimaud : bounty claimed: https://opencollective.com/generator-jhipster/expenses/213110

**Comment by pascalgrimaud** [comment]
@murdos : approved

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/215558. Thanks 😀👍

**Comment by pascalgrimaud** [comment]
@renanfranca : approved
