### ISSUE TITLE
Update end-to-end modules dependencies

### ISSUE THREAD

**Issue by Shegaie** [jhipster/jhipster-lite#4129]
- Cypress and PlayWright modules should depend on ClientCore
- End-to-end test base url should be localhost:9000 to be run with no backend
- Front end maven plugin should depend on spring server (= web server serving front end)

**Comment by pascalgrimaud** [comment]
not sure about localhost:9000
if there is only front without backend, yes it should be localhost:9000
if there is back+front, it's better to start the backend, which will provide the front, so it should be localhost:<serverPort>

One reason for that is some e2e tests can't work without backend (like in generator-jhipster)

**Comment by hdurix** [comment]
Yes but the current issue is that if you generate frontend + cypress, this does not work out of the box.

Our first idea was to add a dependency from cypress to frontend maven plugin (= server), but this is so painful as you cannot generate only a frontend with cypress through JHipster Lite, which is a must have for me if you want to have component tests for instance for your frontend.

> One reason for that is some e2e tests can't work without backend (like in generator-jhipster)
Yes but by default, generated tests work without any server.

Honestly I don't know what is best

**Comment by wmarques** [comment]
I guess that depends on what we want to do with end-to-end.

If they're intended to test only the UI, they should work with the 9000 port and API calls should be mocked.
If we want them to test our app with the backend then we should stick with the 8080 and set the backend as a dependency for the Cypress / Playwright modules.

Or maybe do two modules for each testing philosophy.

**Comment by DamnClin** [comment]
I think we should help people using cypress for component tests instead of end to end tests and that mean calling :9000 since :serverPort won't be refresh without restart

**Comment by hdurix** [comment]
What about adding a property for testing frameworks `testingServerPort` as we have `serverPort`? With a default as 9000.

Or would it be too much?

**Comment by hdurix** [comment]
btw it would be more renaming the actual `serverPort` to `testingServerPort` for those 2 modules

**Comment by hdurix** [comment]
not so easy to rename `serverPort` to `testingServerPort`... I'm not sure this is the good way here finally

**Comment by wmarques** [comment]
The main issue here is that one tool deserves two different purposes :)
IMO we can choose a default one, like component testing (so port would be 9000), and if the user want to do "real" end-to-end testing he can still tweak the configuration.

**Comment by hdurix** [comment]
choosing 9000 would work for both out of the box:
- with backend+frontend, you can run both to launch end-to-end tests
- with frontend only, you just have to run the frontend to launch end-to-end tests

@pascalgrimaud what do you think?

**Comment by pascalgrimaud** [comment]
I'm fine so. Let's move to 9000

**Comment by pascalgrimaud** [comment]
Another idea would be to add a new entry in package.json, something like `e2e:headless:back` and it would override the property to use http://localhost:serverPort

So for the front developers:
- need to launch npm start first
- then: `npm run e2e:headless`

For the back developers or the CI:
- need to start the app, using `java -jar` or `./mvnw`
- then: `npm run e2e:headless:back`

So everyone will be happy

What do you think @hdurix ?
