### ISSUE TITLE
JHipster Lite Framework?

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/jhipster-lite#413]
The overall developer experience is great, but after working on #275 I must admit that I had concerns when copying classes from JHipster Framework to templates in JHipster Lite.

It reminds me of old school JHipster, before jhipster-framework was separated as an external dependency. I fear that we'll end up with "JHipster Fat" instead of "JHipster Lite".

Is it the chosen approach to avoid JHipster Lite artifacts and generate everything? We know the drawbacks, but are there pros that you have thought about? Like KISS at the beginning then refactor later if users vote up?

Perhaps it's in the roadmap to externalize technical classes that will be shared by all projects.
If yes, my 2 cents:
Instead of a big jhipster-framework with a big BoM, I'd like to have lightweight artifacts in groupId `tech.jhipster.lite` so we make sure that **only required dependencies** are in the final tree.

- `spring-boot-core` with required Spring Boot dependencies?
- `spring-boot-common` with eg. LogbackRecorder test utility and other common Spring Boot items
- `spring-boot-async` with ExceptionHandlingAsyncTaskExecutor & tests
- ` spring-boot-liquibase`, etc.

Adding a feature in JHipster Lite will simply require creating a new module, adding a dependency and generation of project-specific configuration instead of generating the same classes in all projects, with all associated boilerplate code. Such classes would have to be kept up to date and tested. The same concerns that led to the creation of jhipster-framework are still relevant but with the "Lite" word in mind.

Thus, a jhipster-lite monorepo containing both the generator and the framework modules would be convenient.

Maybe related to #278.

I'm curious to know how you planned to move forward.

**Comment by pascalgrimaud** [comment]
As you probably know, during 7 versions of JHipster, we tried different approach:
- without jhipster framework
- with jhipster framework, like today, with jhipster-bom project

In my opinion, using an external lib is a pain to maintain, to synchronize between cross CI, to release, etc.

Now, let's take the position of a real developer, in real world.
You have a technical user story to add configuration, for scheduler and async
What would you do ?
- add jhipster library ?
- add 2 or 3 configuration java ? -> personaly, I'd use this solution. I don't want to rely on an external library for this. Then, I can quickly edit this part if I'm not happy

JHipster Lite gives you the possibility to generate a very lite Spring Boot project, with only what you need.

Indeed, if you decide to add all options, it is not lite any more. But with this approach (each option = 1 API in JH Lite = 1 pull request in their project = 1 user story), the user will understand better what is generated.
He can't complain and can't say any more: "JHipster generates too much class"

So my opinion now is to generate everything, and fully tested.

**Comment by pascalgrimaud** [comment]
I forgot to say I'm not against your proposition, it has already suggested by Julien D. when I discussed with him about this project. 

But all feedbacks I got about the different developers who used JHIpster is the same: they don't want to rely to a jhipster lib (like ng-jhipster, react-jhipster) because of:
- break changes introduced during minor version
- not well maintained (see react-jhipster)

That's why, for now, I still prefer to generate everything :-)
Still opened to discuss

**Comment by pblanchardie** [comment]
Thanks for the explanation, now I understand why it's a principle of JHipster Lite to generate and test everything.

To be consistent, perhaps it brings another principle: "only add a class if it's absolutely needed to make the feature work"... I'll elaborate on this, as we don't want to have stuff copied from a dzone blog post 8 years ago in our projects!

I agree with the maintenance pain and it's probably a better idea to keep things simple, increasing velocity.

**Comment by pascalgrimaud** [comment]
Big +1 about `only add a class if it's absolutely needed to make the feature work`
