### ISSUE TITLE
Generated readme with readme title at the end

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#4133]
On the generated apps a Readme title remains at file ends, should not be here

**Comment by DamnClin** [comment]
It looks like it was intended to be used in module but there is no module using that... The feature should be deleted I think, agreed @pascalgrimaud ?

**Comment by pascalgrimaud** [comment]
Yes, let's remove it. I love the current system which generates new markdown file in `documentation/` folder
