### ISSUE TITLE
Front: label + field not well displayed

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4151]
When editing a field, the label is not well displayed.
It's minor but I think it can be improved

![image](https://user-images.githubusercontent.com/9156882/198252277-bbfcf82a-44da-4a98-bc93-8b4199a0d36f.png)

**Comment by qmonmert** [comment]
@pascalgrimaud do you speak about borders?

**Comment by pascalgrimaud** [comment]
Yes, exactly and I don't know how to fix this, because my css skills are closed to zero

**Comment by qmonmert** [comment]
> Yes, exactly and I don't know how to fix this, because my css skills are closed to zero

😅
