### ISSUE TITLE
Undertow: can't apply springdoc-mvc-openapi module

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4153]
When using `spring-boot-undertow` module, the `springdoc-mvc-openapi` can't be applied as it's linked only to `spring-boot-tomcat`

![image](https://user-images.githubusercontent.com/9156882/198287493-c511de84-2499-4389-8860-868b87ed3bf5.png)

**Comment by DamnClin** [comment]
I don't see any acceptable solution for that...

**Comment by pascalgrimaud** [comment]
The current solution is to go to `patches` page, to bypass the tree

**Comment by DamnClin** [comment]
Yep but allowing that in landscape will require a lot of work (something with an or in the organization) and I'm not sure this is worth the effort...

**Comment by biergit** [comment]
Another solution would be to provide the modules selected further down the tree (west side on the landscape) to the modules selected further up the tree. Then there would only be one module `springdoc-openapi`. 
This would also provide a solution for https://github.com/jhipster/jhipster-lite/issues/4111 where `zalando-problems` could choose the right dependency depending on whether `spring-boot-webflux-netty` or a servlet container was chosen.

**Comment by pascalgrimaud** [comment]
Adding a bounty as I think it's important to have, when there are more modules

**Comment by murdos** [comment]
A solution would to allow a module to declare multiple features.
Here we would like to to have a feature `spring-server-mvc` so that `spring-boot-tomcat` and `spring-boot-undertow` would both implements features `spring-server-mvc` and `spring-server`, and `springdoc-mvc-openapi` would depends on `spring-server-mvc`.

Or a feature could inherit from another feature: features `spring-server-mvc` and `spring-server-webflux` would be children of `spring-server` feature, and `springdoc-mvc-openapi` would depends on `spring-server-mvc`

**Comment by DamnClin** [comment]
> A solution would to allow a module to declare multiple features. Here we would like to to have a feature `spring-server-mvc` so that `spring-boot-tomcat` and `spring-boot-undertow` would both implements features `spring-server-mvc` and `spring-server`, and `springdoc-mvc-openapi` would depends on `spring-server-mvc`.
> 
> Or a feature could inherit from another feature: features `spring-server-mvc` and `spring-server-webflux` would be children of `spring-server` feature, and `springdoc-mvc-openapi` would depends on `spring-server-mvc`

Not really since that can't be displayed in the UI (and this is the only goal of features(

**Comment by pascalgrimaud** [comment]
I think we'll need to fix this ticket, as we'll have the same issue as soon as gradle is implemented. A lot of module will depend on feature 'build tool', instead of maven directly
The feature build tool will contain maven and gradle

**Comment by DamnClin** [comment]
> I think we'll need to fix this ticket, as we'll have the same issue as soon as gradle is implemented. A lot of module will depend on feature 'build tool', instead of maven directly The feature build tool will contain maven and gradle

Probably but that mean we have to find a possible solution. (But there is not problem with Gradle or Maven, totally different case)

**Comment by DamnClin** [comment]
I still don't understand why we are trying to do complicated stuff here. We ça can just add a feature with empty (or almost empty) modules to choose between reactive and not reactive, that will solve this issue without adding a lot of complexity in the landscape screen

**Comment by murdos** [comment]
> Probably but that mean we have to find a possible solution. (But there is not problem with Gradle or Maven, totally different case)

I was also thinking about the gradle and maven problem, because in my understanding every module adding a maven plugin(s) to the build will need to be split in a maven and gradle flavor (and thus with a dedicated feature), because maven and gradle plugins are always different for achieving a similar feature (contrary to java dependencies).

**Comment by DamnClin** [comment]
> > Probably but that mean we have to find a possible solution. (But there is not problem with Gradle or Maven, totally different case)
> 
> I was also thinking about the gradle and maven problem, because in my understanding every module adding a maven plugin(s) to the build will need to be split in a maven and gradle flavor (and thus with a dedicated feature), because maven and gradle plugins are always different for achieving a similar feature (contrary to java dependencies).

For this case that probably mean we'll set information for both maven and Gradle in plugins

**Comment by murdos** [comment]
> I still don't understand why we are trying to do complicated stuff here. We ça can just add a feature with empty (or almost empty) modules to choose between reactive and not reactive, that will solve this issue without adding a lot of complexity in the landscape screen

Ok, got it. I've something that seems to be satisfying with empty extra modules.
I'm polishing it and I'll submit a draft.

**Comment by murdos** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/117664

**Comment by pascalgrimaud** [comment]
@murdos : approved
