### ISSUE TITLE
Add Spring Boot configuration annotation processor

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/jhipster-lite#416]
https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata.annotation-processor

It automagically generates the `spring-configuration-metadata.json` file and makes IntelliJ IDEA happy.

The only thing to do is adding:
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-configuration-processor</artifactId>
    <optional>true</optional>
</dependency>
```

As we replaced the big old JHipsterProperties with module-specific configuration classes, it would be convenient.

Can we add it as part of Spring Boot core generation?

**Comment by pascalgrimaud** [comment]
It is already added by Security JWT.
But indeed, I think it's better to add it when initializing Spring Boot project, so in Core
