### ISSUE TITLE
Refactoring: move templates related to mongock to dbmigration

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4168]
See https://github.com/jhipster/jhipster-lite/tree/main/src/main/resources/generator/server/springboot/database/mongock

These templates should be in dbmigration instead if database folder

**Comment by niranjanib** [comment]
Hello @pascalgrimaud, I would like to work on this issue.

**Comment by DamnClin** [comment]
Assigned. Don't hesitate to ask if you need help :)

**Comment by niranjanib** [comment]
Sure, thank you!
