### ISSUE TITLE
Drop coverage for fullapp

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4172]
See the sonar analysis for the fullapp:

![image](https://user-images.githubusercontent.com/9156882/198847145-119c7f4c-dea4-4b80-9368-949f140a2cc3.png)

I think it's related to the migration from jest to vitest :-(
So finally, I'm not sure about this move, it looks like vitest is not really ready

cc @Gnuk @qmonmert

**Comment by qmonmert** [comment]
@pascalgrimaud which line is not covered?

**Comment by pascalgrimaud** [comment]
Sorry, power off my computer. I think it's the homepage.component.ts
Maybe it could be fixed by vitest team. Let's wait, as I think the issue comes from there.

This issue is just to track this item

**Comment by qmonmert** [comment]
ok tell me tomorrow

**Comment by Gnuk** [comment]
I just link the PR from vitest relative to the fix: https://github.com/vitest-dev/vitest/pull/2232

**Comment by DamnClin** [comment]
Fixed on main, just run a check
