### ISSUE TITLE
Clean up CONTRIBUTING.md - link missing for generating the Continuous Integration 

### ISSUE THREAD

**Issue by niranjanib** [jhipster/jhipster-lite#4177]
Hi folks,

While going over the CONTRIBUTING.md, I noticed below 2 things under the [Submitting a Pull Request](https://github.com/jhipster/jhipster-lite/blob/main/CONTRIBUTING.md#submitting-a-pull-request) section:

> Launch all tests
> 
> ./mvnw clean verify
> Generate a new JHipster project, and ensure that all tests pass
> 
> ./mvnw clean verify
> Test that the new project runs correctly:
> 
> ./mvnw spring-boot:run
> You can generate our Continuous Integration (with GitHub Actions and Azure Pipelines) by following [this](https://github.com/jhipster/jhipster-lite/blob/main/CONTRIBUTING.md#local-build)
> 

1. There is a step with link reference to generate the Continuous Integration as seen above. Is this step required ? If yes, can the steps be added for it, as the current link is broken? If no, can this be removed from the document to avoid confusion?

2. Can the duplicate step to run test `Generate a new JHipster project, and ensure that all tests pass ./mvnw clean verify` be removed as well?

I checked other JHipster repos and found that the point 1 is happening in other repos as well. Just wanted to check if I'm missing any context :) 

Happy to raise a PR on this, if this can be picked up! Thanks.

**Comment by pascalgrimaud** [comment]
My fault :-)
It was a bad copy/paste from generator-jhipster and it needs to be clean

**Comment by niranjanib** [comment]
No worries, it happens :)

So shall I remove both the steps mentioned in the issue?

**Comment by pascalgrimaud** [comment]
![Screenshot_20221031-074601](https://user-images.githubusercontent.com/9156882/198947839-b9e10026-d4a3-4415-9807-450108c336ac.png)

The part about CI should be updated
In fact, you could use: ./test-ci/generate.sh fullapp for example to reproduce the build
To have the list of possible app, you need to check inside generate.sh

So 2 solutions:
- we could simply remove the part about talking about GitHub Actions/Azure
- or update this part, and describe the generate.sh

What do you prefer ?

**Comment by pascalgrimaud** [comment]
So only this part should change:

> You can generate our Continuous Integration (with GitHub Actions and Azure Pipelines) by following this

**Comment by niranjanib** [comment]
I think updating the link and describing generate.sh will be more helpful. I also see there is an existing section in [Contributing.md ](https://github.com/jhipster/jhipster-lite/blob/main/CONTRIBUTING.md#running-integration-tests-locally) that mentions what you said.

I'll link it to this section and add more details on generate.sh.

**Comment by niranjanib** [comment]
Hi folks, I've added more details to the existing `Running integration tests locally section` in the CONTRIBUTING.md. 
Please review and let me know if more details needs to be added :)
