### ISSUE TITLE
Spring Boot Database: refactoring SQL

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#419]
We could extract some common files / common methods to a common folder related to sql:
server/spring-boot/database/sql

These common files/methods can be used by:
- PostgreSQL
- MySQL
- MariaDB

**Comment by pascalgrimaud** [comment]
not easy one, but I can help you if needed :)
The important part to move in common is spring boot properties (JPA, Hibernate, etc)

**Comment by seraphinandrieux** [comment]
PR #722

**Comment by pascalgrimaud** [comment]
increasing the bounty as it's much much work than expected
thanks a lot @seraphinandrieux
