### ISSUE TITLE
Spring Boot Database: MongoDB

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#421]
Nice to have as there are some stats
See https://start.jhipster.tech/statistics

**Comment by juliensadaoui** [comment]
Hello @pascalgrimaud, i can take this issue.

**Comment by juliensadaoui** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/64369

**Comment by pascalgrimaud** [comment]
@juliensadaoui : approved
