### ISSUE TITLE
CI: GitHub Actions

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#422]
Need to be discussed about how to propose something smart

For a 1st version, it could be really simple:
- a GitHub Actions file to launch mvnw clean verify
- it can contain a needle for adding step

It can work later with the front part, as mvnw verify will test the front part too

**Comment by Hawkurane** [comment]
Thank you for the review and merging my PR @pascalgrimaud 

By the way, i've just claimed the bounty on open collective. Almost forgot how to do this since it's a been a long time I did this 🤣 

https://opencollective.com/generator-jhipster/expenses/66175

**Comment by pascalgrimaud** [comment]
It's fine @Hawkurane, but can you update the title in your Invoice plz?

https://github.com/jhipster/issues/422 -> https://github.com/jhipster/jhipster-lite/issues/422

**Comment by Hawkurane** [comment]
My bad, it's all done now :)

**Comment by pascalgrimaud** [comment]
Thanks, approved @Hawkurane :)
