### ISSUE TITLE
Trailling line break for SonarQube commands

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#4238]
When using the sonar module, the generated readme contains a trailling linebreak:

```bash
docker compose -f src/main/docker/sonar.yml up -d
./mvnw clean verify sonar:sonar

```

Should be removed in SonarModulesFactory

**Comment by kartiktayal** [comment]
@DamnClin This does not seem to be the case when I have generated the fullapp using tests-ci. The sonar.md seems to be okay.
![image](https://user-images.githubusercontent.com/47282169/200311403-fd86c8df-cb8a-48ea-ac5e-7437e381955b.png)
Please correct me in case my understanding is incorrect.

**Comment by DamnClin** [comment]
It is in the main readme :). There's a trailling line break in the launch command
