### ISSUE TITLE
Manage src/main/docker/sonar.yml with dependabot

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#4239]
Manage versions in `src/main/docker/sonar.yml` with dependenbot

**Comment by DamnClin** [comment]
It is supposed to be done but not updating our sonar version...

**Comment by swarajsaaj** [comment]
@pascalgrimaud Isn't sonar dependency now managed with renovate? I guess this issue can be closed then.
Last PR for sonar:- https://github.com/jhipster/jhipster-lite/pull/9068

**Comment by murdos** [comment]
@swarajsaaj Good catch! This is indeed resolved 🙂
