### ISSUE TITLE
Rename sonar* modules to sonar-qube*

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#4241]
Sonar modules should be SonarQube modules. Files to update: 

* JHLiteModuleSlug
* SonarModulesFactory
* SonarModulesFactoryTest
* SonarApplicationService
* SonarModuleConfiguration

**Comment by kartiktayal** [comment]
Hi Everyone,
I would like to contribute by picking this issue. Full disclosure: I am new to open source contribution so pretty excited on learning through this experience since I am a big fan of the amazing work done by Jhipster team

**Comment by DamnClin** [comment]
Great! Welcome, affected to you :)

**Comment by kartiktayal** [comment]
@DamnClin I had a query, should we change the file names from sonar to sonarqube such as sonar docker file and sonar sh file in tests-ci?
Should we look for other changes in the project if we take this into consideration?

**Comment by DamnClin** [comment]
> @DamnClin I had a query, should we change the file names from sonar to sonarqube such as sonar docker file and sonar sh file in tests-ci? Should we look for other changes in the project if we take this into consideration?

Not in this PR :)
