### ISSUE TITLE
Liquibase: add new xml

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#425]
- add missing needles: https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/springboot/dbmigration/liquibase/resources/master.xml#L16
- add methods for adding new xml

**Comment by MSaguer** [comment]
Hi Pascal, can I help on these issue?

**Comment by pascalgrimaud** [comment]
@MSaguer : sure, your help is really welcome
