### ISSUE TITLE
Spring Boot PostgreSQL: User / Authority Entities

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#426]
Can be done after https://github.com/jhipster/jhipster-lite/issues/425

- create UserEntity and AuthorityEntity
- create UserJpaRepository, AuthorityJpaRepository
- add new xml entry in Liquibase: need to think about flyway, once the support is added, but for now, let's focus on liquibase

**Comment by MSaguer** [comment]
User entity is different when generated with jwt or oauth2 options. 
* With Jwt, user has an integer ID and UserRepository contains methods related to password
* With oauth2, user ID is a string

I think that this issue could be limited to the jwt option for a moment. It depends if #270 is close before this one :)

**Comment by pascalgrimaud** [comment]
Yes I know :)

For JWT, the User Entity can be used for authentication
For OAuth2, the User Entity is not used for authentication, but the developer can created this entity in the database. Then, he'll be in charge of sync between Keycloak and this table

The use case is simple:
- given an existing project with Database PostgreSQL
- when calling this API
- then I want to have UserEntity, AuthorityEntity and new xml entry

**Comment by pascalgrimaud** [comment]
@MSaguer : don't forget your bounty here :-)

**Comment by pascalgrimaud** [comment]
@MSaguer : my bad, it was already claimed :-D forget my comment ahah
