### ISSUE TITLE
History in .jhipster folder

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#427]
Each time an API is used, we could add an entry in a history file, something like: .jhipster/history

I don't know how to achieve this for now, so any suggestion is welcome:
- shared context which is called after each API
- using AOP for methods in primary/rest and only for output
- spring events

**Comment by swarajsaaj** [comment]
This kind of history/log can also be used to make dependencies while generating project using frontend/cli. 
A few thoughts:-
- The project information like baseName, packageName etc. should also be persisted (to make the project directory more stateful), currently we need to pass it on every request in REST, which can cause mismatches.
- Version of the jh-lite could also be stored for providing upgradability in future releases.


I like the AOP/Annotation way as it will give flexibility and visibility how things are being generated.

**Comment by pascalgrimaud** [comment]
@swarajsaaj : thanks for thinking about it, but plz don't start this ticket before we agree together :-)

I'm still thinking about baseName and packageName.

baseName is used at init
packageName is used at maven
Then, once it is used, we can find the information by reading package.json or pom.xml, it means we don't need to store it.
It means there are some API which can be used in existing Spring Boot project (without the need to be init with JH Lite)

I think the history could be used for reproducing some issues later, so we know which API were used : but I'm not sure about my ideas!

That's why we should discuss, before starting something

**Comment by swarajsaaj** [comment]
Sure @pascalgrimaud :)

>  It means there are some API which can be used in existing Spring Boot project (without the need to be init with JH Lite)
Yes, that is a benefit we get without depending on a persisted information and taking it from pom/pacakge.json.

And I think there are 2 concepts that are being mixed (at least in my mind :)),
- To be able to reconstruct the current state of application (like we did from .yo-rc.json in generator-jhipster to allow user further commands based on existing structure)
- Maintaining an event-log like history to be able to know what steps user followed to create the project (as you mentioned to be able to reproduce an issue)

For 1st approach, it would depend also on what are needs of frontend/cli in future to work properly (ofcourse something like that would be needed when we move towards entity CRUD). I was also thinking if this can be used for dependency validations of all features (as mentioned earlier)
For 2nd approach, I like it as a audit/event log of what happened during the course of generation, more of like a log maybe? Would a log file be enough here or we have need of a readable structure like json?

Ofcourse, 2nd approach is lightweight and can be done before 1st one.

**Comment by Bolo89** [comment]
Hello,

I can develop the feature. The generator will add in a json file at the init of a project. 
Each rest service can be annotated with à custom annotation (with an unique id for the moment).
With aop, we can intercept all rest service called, and get the id from the annotation, to save it in the history file.

It's good for you ?

**Comment by pascalgrimaud** [comment]
Fine, thanks @Bolo89 
Let's give a try with your suggestions

**Comment by pascalgrimaud** [comment]
added a bounty as it's a lot of work here, and this feature will be very usefull
