### ISSUE TITLE
Spring Boot Database: MSSQL

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#428]
Need to do this, first: https://github.com/jhipster/jhipster-lite/issues/419

The stats with MSSQL is not low, so I think the support is easy and can be added

**Comment by seraphinandrieux** [comment]
Hi Pascal, 
May I take care of this ticket ?

**Comment by pascalgrimaud** [comment]
@seraphinandrieux : I need this for my current customer, but my team didn't have time to start it, so you're really really welcome!

**Comment by pascalgrimaud** [comment]
Increasing the bounty as it was more work than expected, specially for integration tests
