### ISSUE TITLE
Hexagonal Arch Unit test

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#429]
2 steps:
- add dependency
- generate these files: 
  -  https://github.com/jhipster/jhipster-lite/blob/main/src/test/java/tech/jhipster/lite/HexagonalArchTest.java
  - https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/SharedKernel.java
  - https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/BusinessContext.java

**Comment by pascalgrimaud** [comment]
Credits to this project https://gitlab.com/nerp-ippon/nerp/-/tree/main/webservices/src/main/java/com/ippon/nerp mainly coded by @DamnClin

**Comment by MSaguer** [comment]
I'm in

**Comment by MSaguer** [comment]
Shall these files be generated by default? It so, it could be added in SpringBootDomainService.init(), else we may create new new package tech.jhipster.lite.generator.server.springboot.arch.

What do you prefer?

**Comment by pascalgrimaud** [comment]
I don't think it should be generated by default, it should be optional, as it will add arch unit as dependencies, maybe some users don't want it

Another thing: it's not related to spring boot, because you can: init, maven, java base, hexagonal arch unit tests, then code your domain. No need spring boot yet

So I think the location would be here https://github.com/jhipster/jhipster-lite/tree/main/src/main/java/tech/jhipster/lite/generator/server/javatool

**Comment by MSaguer** [comment]
So, let's create a new server.javatool.arch package
