### ISSUE TITLE
Add feature for spring boot oauth2 providers

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#4313]
The spring boot oauth2 modules for providers should be in the same feature:

* `spring-boot-oauth2-auth0`
* `spring-boot-oauth2-okta`

**Comment by pascalgrimaud** [comment]
@DamnClin : can you suggest a name for this feature?

**Comment by DamnClin** [comment]
oauth-provider sounds good

**Comment by Yourgene** [comment]
shouldn't `springdoc-oauth2-auth0` and `springdoc-oauth2-okta` follow the same logic ?

**Comment by DamnClin** [comment]
> shouldn't `springdoc-oauth2-auth0` and `springdoc-oauth2-okta` follow the same logic ?

Probably

**Comment by Yourgene** [comment]
> Probably

If we all agree to also group them, I can include it in the current PR. 

What about `oauth-springdoc` for the name ?

**Comment by DamnClin** [comment]
> What about oauth-springdoc for the name ?

Sounds good
