### ISSUE TITLE
JHLite Custom: ignore all children of a parent module

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4338]
In JHLite Custom, when ignoring a module, it should ignore all the children too.

It doesn't work, and there is a stacktrace:

```
jhlite-hidden-resources.slugs=custom-jhlite,angular-core
```

You need to add other children too:

```
jhlite-hidden-resources.slugs=custom-jhlite,angular-core,angular-health,angular-oauth2,angular-jwt
```

The problem is:
- there are new modules, which have been coded in JHLite: angular-beer
- there is a new release
- the user upgrades the JHLite custom
- it's broken, unless he/she ignores the new module: angular-beer

**Comment by DamnClin** [comment]
In fact, when I did the feature I though about that case and decided to do it that way to avoid "silent" exclusions.

That probably was a mistake and should be reworked but we need to find a way to make it explicit. For example with dedicated properties or values to say "I want to exclude this module or this module and all dependent modules". What do you think?

**Comment by pascalgrimaud** [comment]
No worry, I don't think it was a mistake, it was designed like this, that's all :-D

I don't think our user will search and exclude all dependant modules. So IMO, no need to manage 2 different properties:
- one for excluding single module, 1 by 1
- another for exclusing a specific module and all dependant modules

For example, I don't use Angular, and I don't want to use it.
I'll prefer to ignore `angular-core`, instead of searching and listing all dependant modules to ignore explicitely.

So my opinion is:
- keep current property, and improve the behavior to exclude this module and all dependant module
- maybe, display the excluded modules at start, to avoid "silent" exclusions

**Comment by renanfranca** [comment]
Thank you very much @pascalgrimaud for increasing the bounty 😄 !
