### ISSUE TITLE
New module to add thymeleaf (+HTMX, Alpine) as "client side" technology

### ISSUE THREAD

**Issue by atomfrede** [jhipster/jhipster-lite#4339]
I would like to add a module which adds

- [x] thymeleaf
- [x]  webjars 
- [x]  htmx
- [x]  alpine 
- [x]  tailwind (or bootstrap)
- [x]  skeleton layout and index files
- [x] reference added webjars in the skeleton index file (PR Pending)

Would you consider this more a server module or a client module or even split the different parts (e.g. webjars a very simple dedicated module)? 
Would you say such a module makes sense or is it not useful to have a "classic" server side rendering technology within the landscape?

This is heavily inspired by what Taming Thymeleaf is doing and what the ttcli brings in https://github.com/wimdeblauwe/ttcli

**Comment by gmarziou** [comment]
I think it's a great idea. 

Personally, I'm tired of all these javascript frameworks, on the long run they require too much effort to keep your app up to date, fix vulnerabilities and maintain skills.
I imagine I'm not the only one.

I think JHipster Lite is the perfect vehicle for such approach.

**Comment by atomfrede** [comment]
@gmarziou Exactly why I would like to have such a module. Most often the decision to use a full blown javascript framework is just rushed because everyone is doing it.

**Comment by pascalgrimaud** [comment]
Adding a 1st bounty, to motivate someone to init this module :)

**Comment by atomfrede** [comment]
I will start with the boot thymeleaf module. I think adding at at this level. The question is where to add the webjars module and htmx. I would say webjars can be added quite early, while htmx should depend on thymeleaf and webjars, so the column after thymeleaf.

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/203401/230740491-985226ed-ce3a-4ee6-877b-42767b017947.png">

**Comment by DamnClin** [comment]
You don't pic the level, you just need to define the dependencies, level will be calculated

**Comment by atomfrede** [comment]
yes basically that's what I meant😅 it depends on spring boot module.

**Comment by pascalgrimaud** [comment]
@renanfranca : I reopen this ticket as I think it's not finished, right ?

**Comment by renanfranca** [comment]
> @renanfranca : I reopen this ticket as I think it's not finished, right ?

@pascalgrimaud : You are right, I will keep working on it 👍

**Comment by atomfrede** [comment]
Awesome @renanfranca! If you need some help or feedback feel free to give me a ping!

**Comment by renanfranca** [comment]
> Awesome @renanfranca! If you need some help or feedback feel free to give me a ping!

Thank you very much @atomfrede !

**Comment by atomfrede** [comment]
@renanfranca Nice work thanks for starting this! Should we split the bounty? Or @pascalgrimaud what do you say both claim the bounty? Anyways, I would say we can close this, happy to have this eventually.

**Comment by atomfrede** [comment]
Thanks @pascalgrimaud .

**Comment by pascalgrimaud** [comment]
@atomfrede : I increase the bounty to $600 (100+500), so you can claim each $300 :)

**Comment by renanfranca** [comment]
> @renanfranca Nice work thanks for starting this! Should we split the bounty? Or @pascalgrimaud what do you say both claim the bounty? Anyways, I would say we can close this, happy to have this eventually.

@atomfrede: Thank you too! Nice work! That was a long issue, I am happy that we successfully finished it.

**Comment by renanfranca** [comment]
> @atomfrede : I increase the bounty to $600 (100+500), so you can claim each $300 :)

@pascalgrimaud: Thank you very much!!! 😄

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/181527 . Thanks 😄 ✌️

**Comment by pascalgrimaud** [comment]
@renanfranca : approved
