### ISSUE TITLE
fix failing tests on windows

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/jhipster-lite#438]
- [x] assertion of posix file permissions should not be done on non-posix (aka Windows^^) file system.
- [x] replaceText fails with CRLF
- [ ] handle path separator `\`

**Comment by pascalgrimaud** [comment]
Yes plz, I don't have Windows, I can't test this kind of thing :-(

**Comment by pascalgrimaud** [comment]
I thought it should be enough ? https://github.com/jhipster/jhipster-lite/blob/main/src/test/java/tech/jhipster/lite/common/domain/FileUtilsTest.java#L497-L511

Maybe it's not related to this code ?

**Comment by pblanchardie** [comment]
you're properly checking that you're on posix before **setting** execution permission, but the problem is that https://github.com/jhipster/jhipster-lite/blob/deb0d8be2d279ae15483c136b6481db73f6371ac/src/test/java/tech/jhipster/lite/generator/buildtool/maven/application/MavenAssertFiles.java#L29 tries to check that execution permission is set, without checking we're on posix.

**Comment by pblanchardie** [comment]
https://opencollective.com/generator-jhipster/expenses/61424

**Comment by pascalgrimaud** [comment]
@pblanchardie : approved
