### ISSUE TITLE
IntelliJ IDEA plugin

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/jhipster-lite#441]
Currently we only have the HTTP API.
Perhaps we'll have a CLI, a web app with Vue, a desktop app and so on.
Why not having a plugin in your IDE to add features to your project?

About the use case:
"As a Developer, I want to use my IDE for development so I only use my web browser for browsing docs and testing" ;)
Provide code-generation features straight from the IDE.
There are plenty of code generation plugins available and I think it would be nice to have a JHipster one.

About UI:
A list of available features for the current project with a + button and customization options.
Let's think about it more in depth...

About architecture:
I guess we could embed JHipster Lite in the plugin (it would be cumbersome to call an external API).

---

I can dig into plugin development to see what it looks like.

**Comment by pascalgrimaud** [comment]
Can you give more details on what you have in mind plz?

**Comment by pblanchardie** [comment]
> Can you give more details on what you have in mind plz?

updated description, still needs some thinking about it.

**Comment by pascalgrimaud** [comment]
I think it's a good idea, but honestly, I think it's too early.

I would prefer to focus on features first, and see the adoption of this project.

If it's a success, we could focus on how to use JHipster Lite.

As discussed, I have a ton of ideas:
- local with swagger (current version)
- local with a front part (probably Vue.js)
- in a Cloud like JHipster Online (need to work on Git methods: create projects, pull request etc)
- build a Spring Native app and use it as a Lambda function
- plugins (IntelliJ, VSCode)
- something like JHipster App (see https://github.com/jhipster/jhipster-app)
- a CLI, with picocli, like NubesGen

**Comment by pascalgrimaud** [comment]
As it's not the priority, I'm closing this
As our current webapp is fine enough :-)
