### ISSUE TITLE
Spring Boot Session-based authentication

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/jhipster-lite#442]
- Built-in
- Spring Session
  - Data Redis
  - Hazelcast
  - JDBC (buggy with constraint violations)

**Comment by pascalgrimaud** [comment]
Spring Session can be supported, like JWT.
But I don't understand why you mention Redis and Hazelcast. I don't think it's mandatory, unless I'm wrong.

Anyway, just remember it's not an option which is used a lot in generator-jhipster.
The stats are very low. So I'm not sure it deserves a support.
But we can give a try and you can maintain it :)

**Comment by pblanchardie** [comment]
Very low priority indeed, let's focus on newer solutions if sessions are abandonned by most people.

Multiples choices :
- Without spring session, built-in.
- With spring session: there are multiple session storage solutions for distributed apps: redis, hazelcast, jdbc.

**Comment by pascalgrimaud** [comment]
Do you plan to implement it @pblanchardie ?
Or should we close this as lack of interest?
