### ISSUE TITLE
Git Info Configuration

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4425]
The goal is to use the following plugin and provide git info:

```
          <groupId>io.github.git-commit-id</groupId>
          <artifactId>git-commit-id-maven-plugin</artifactId>
          <version>${git-commit-id-plugin.version}</version>
```

If no one take it, I'll work on it at the end of the month

**Comment by swarajsaaj** [comment]
Hi @pascalgrimaud ,
is this about adding the plugin to `jhipster-lite` generator or generated application? or both?
And also exposing the info on an endpoint?

**Comment by pascalgrimaud** [comment]
The mail goal is to code the module, so it's for generated applications, but once it's done, we can apply it to JHLite itself :-)


Or another approch could be:
- add git info to JHLite
- once the PR is approved, extract the diff and do it as a module

**Comment by pascalgrimaud** [comment]
I'm starting this one
