### ISSUE TITLE
Init: add API to launch npm install and prettier

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#446]
In Init context, add API to launch `npm install` and `npm run prettier:format` from CommandRepository

**Comment by swarajsaaj** [comment]
I did #460 for this, but I doubt if doing with with a synchronous API is best for very long running `npm install` (Timeouts?)

**Comment by pascalgrimaud** [comment]
Indeed, I think it should be async

**Comment by pascalgrimaud** [comment]
Or maybe it could be async by default, and sync as an option? I need to think about the use case, as it is need to run prettier

**Comment by swarajsaaj** [comment]
We could keep prettier execution first and npm install later as the latter is more prone to be long running. 
Or we could also keep a fixed time to wait for an error (a few seconds) and return the response if execution keeps running after that.

**Comment by pascalgrimaud** [comment]
We could look at https://github.com/jhipster/jhipster-online as the process to generate JHipster project is done via API too, but without `npm install`
