### ISSUE TITLE
Inherit spring instead of composing?

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#4585]
Discussing with a client this morning seems like inheriting spring dependency can be a better idea since we'll inherit plugins configuration (can't be composed). @pascalgrimaud you know why we are "just" composing instead of adding a parent?

**Comment by pascalgrimaud** [comment]
probably related to https://github.com/jhipster/jhipster-lite/issues/579 ?

**Comment by DamnClin** [comment]
No, I think it's ok
