### ISSUE TITLE
Delete svelte module?

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#4619]
The svelte module is not really used / maintained and comes with a lot of problems (can't update versions etc). Do we delete is?

**Comment by pascalgrimaud** [comment]
Let's do it in 2 steps:
- disable the module and comment the CI
- if after several releases, it's not maintained, then we can delete it

cc @flcarre @vishal423 : don't know if you are interested on this

**Comment by pascalgrimaud** [comment]
No worry, JHLite is built for allowing to add / remove easily some features.

So it will be easy to disable the Svelte module, during several releases.
Then, if no one wants to maintain it, it can be removed, without any impact on existing other modules.

**Comment by pascalgrimaud** [comment]
as it is still a little bit maintained by @qmonmert, let's wait before disabling Svelte

**Comment by pascalgrimaud** [comment]
It's time to disable or remove Svelte, as @qmonmert you are alone to maintain this.
@flcarre added the initial support but he stopped to contribute to this project

As there are so few interest, I think it's time to:
- disable Svelte in landscape page
- disable it in GitHub Actions
- disable it in dependabot configuration

No need to spend time and effort to maintain it
So we can progress with other options, angular, react and vuejs, and specially prettier 3

What do you think @murdos @qmonmert ?

**Comment by qmonmert** [comment]
ok we can remove it
