### ISSUE TITLE
System.lineSeparator is not relevant in all cases

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/jhipster-lite#477]
- won't make sense on a remote server (aka JHipster Online)
- is not appropriate on some local workstations (Windows with LF project: adds CRLF in LF files)

suggestions:
- only support LF? what is the problem with that?
- auto-detect file line separators when applying modifications?
- switch to a project config with default to LF?

**Comment by pascalgrimaud** [comment]
Great ticket ! Important to fix these issue
Instead of using lineSeparator or hard code \n, we could use our own constant + dedicated method to do some replace when needed

Then, I don't know which is the best solution for our Windows users.
What do you think @swarajsaaj ?

**Comment by pascalgrimaud** [comment]
I think there is 2 issues here:
- the tests in generator should work on Windows and Linux
- the generated code could support only LF. I think it is the choice in generator-jhipster, as it's forced with git, but I'm not sure :-D

**Comment by swarajsaaj** [comment]
It would be really nice to have a consistent convention for line endings in pproject.
Even Java text blocks use only '\n' for new lines, irrespective of OS (currently to get our test cases working on all platforms, we replace it manually with System.lineSeparator() ).

Need to think more on how will it behave for non jhipster-lite projects, as we currently are open to even non-jhipster-lite generated projects, their project configuration on Windows may not have same line endings.

**Comment by pblanchardie** [comment]
Yes @swarajsaaj.

Moreover, when you programmatically add an import in java, it's \n so I'm not sure we should bother with that for some files and not for other.

If we want to handle non-jhipster projects, better abandon the needle and opt pour xml processing with maven library or any other IMHO.

**Comment by pascalgrimaud** [comment]
Handle non jhipster project is an idea and could be done really later. I don't think we should put our effort on this now

**Comment by swarajsaaj** [comment]
> Handle non jhipster project is an idea and could be done really later. I don't think we should put our effort on this now

Great, then lets go ahead with the LF convention. (also maybe add the same in .gitattributes for sanitizing commits)

**Comment by pblanchardie** [comment]
Almost done, will provide PR.

**Comment by pascalgrimaud** [comment]
It should already be the case ?
https://github.com/jhipster/jhipster-lite/blob/main/.gitattributes

**Comment by pblanchardie** [comment]
> It should already be the case ?
> https://github.com/jhipster/jhipster-lite/blob/main/.gitattributes

It only forces ending for bat, sh... and leave the rest up to the system, which is not sufficient indeed.

@swarajsaaj do have gitattributes you like? Else I can provide something.

> we could use our own constant + dedicated method to do some replace when needed
>

Yes!

**Comment by pascalgrimaud** [comment]
When building the Project object, can't we calculate the EOL (by calling some function or reading some existing files), and store it in the Project object?
Then, we could reuse it in our code?

I'd like to keep the gitattributes as closer to the generator-jhipster one as possible.

**Comment by pblanchardie** [comment]
> When building the Project object, can't we calculate the EOL (by calling some function or reading some existing files), and store it in the Project object?

Yep, I'll begin with "switch to a project config with default to LF" then add "auto-detect file line separators".

**Comment by swarajsaaj** [comment]
> @swarajsaaj do have gitattributes you like? Else I can provide something.

Nothing specific for now, you can go ahead with one's you already mentioned.

**Comment by pblanchardie** [comment]
after playing and fixing in #480, I'd say the best option for Windows users is to stick with LF ;)
hope one day CRLF will disappear!

**Comment by pblanchardie** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/60555

**Comment by pascalgrimaud** [comment]
@pblanchardie : approved
