### ISSUE TITLE
Default project configuration howto

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/jhipster-lite#481]
In generation domain services, sometimes we see 2 lines:
```java
project.addDefaultConfig(LINE_SEPARATOR);
String lineSeparator = project.getStringConfig(LINE_SEPARATOR).orElse(LF);
```
And sometimes one line:
```java
String lineSeparator = project.getStringConfig(LINE_SEPARATOR).orElse(LF);
```

@pascalgrimaud what should we generalize?

The first adds the default to project configuration, but anyway the second defaults to the same default.

**Comment by pascalgrimaud** [comment]
My suggestion would be to calculate it here: https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/project/domain/Project.java#L30-L44

Then, simply have the method project.getEOL (or getLineSeparator())

**Comment by pblanchardie** [comment]
> Then, simply have the method project.getEOL (or getLineSeparator())

OK, I was not sure if it was allowed.

But the question remains for other config items (package, indent, etc.).

**Comment by pascalgrimaud** [comment]
Yes it was my idea in https://github.com/jhipster/jhipster-lite/issues/59 but I didn't provide enough details in this ticket as I was alone at the beginning of the project :p

But I'd prefer to do it in separate PR
- 1 for packageName
- 1 for indent
- etc...
Easier to review

**Comment by DamnClin** [comment]
I think this can be closed since this problem is fixed in modules

**Comment by pascalgrimaud** [comment]
Thanks
