### ISSUE TITLE
Module 'angular-health' depends on a health API but does not declare a dependency on spring-boot-actuator module

### ISSUE THREAD

**Issue by Yutsa** [jhipster/jhipster-lite#4852]
If I generate a new project by selecting the `angular-health` module, it will generate a health service using the `/management/health` API.

However nothing provides the endpoint, you need to manually select `spring-boot-actuator`.

I'm not sure if the behaviour is intended, but I would say it would be more natural to declare a dependency to the `spring-boot-actuator`.

Should we add a dependency from `angular-health` to `spring-boot-actuator` ? If that is the case, I volonteer to do it as I am interested in contributing to JHlite.

Reproduced with :

```json
{
  "actions" : [ {
    "module" : "init",
    "date" : "2022-12-26T21:34:50.065931675Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "prettier",
    "date" : "2022-12-26T21:34:56.182047305Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "angular-core",
    "date" : "2022-12-26T21:35:03.851271446Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "angular-health",
    "date" : "2022-12-26T21:35:22.753632032Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  } ]
}
```

**Comment by DamnClin** [comment]
Hello, the frontend modules are really far to have the maturity of the backend modules :D. I can't say if this was intended to do it like that but I think you can do the update if you want to. You'll have to update `organization` in `AngularhealthModuleConfiguration`
