### ISSUE TITLE
Getting "Project can't be downloaded" error when downloading a project

### ISSUE THREAD

**Issue by gtiwari333** [jhipster/jhipster-lite#4873]
I tried creating a simple project from https://lite.jhipster.tech/ and im getting following error when downloading the project.

![Screenshot from 2022-12-29 10-08-14](https://user-images.githubusercontent.com/4362613/209979665-8e045aa0-b766-4e00-8237-5ca301e2b36a.png)

Http Response: 
```
{
"type":"about:blank","title":"Unknown project","status":400,
"detail":"Unknown project folder","instance":"/api/projects",
"key":"unknown-project-folder"
}
```

When tried changing the Project Folder to my local folder.  I'm getting same error message but the Http response is slightly different
```
{"type":"about:blank","title":"Invalid project","status":400,
"detail":"You can't download a project from this folder","instance":"/api/projects",
"key":"invalid-download-folder"}
```

**Comment by DamnClin** [comment]
You need to apply the modules (by clicking "Apply new" or "Apply selected") to create the project, you'll then be able to download it

**Comment by DamnClin** [comment]
Closing this since it looks solved :)
