### ISSUE TITLE
Handle Gradle plugins in modules

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#4955]
Following #1862 gradle plugins need to be handled.
This will require a bit of refactoring, since maven and gradle plugins have different identifiers (gradle only has an id, whereas maven has groupId + artifactId), and also because for a given feature maven and gradle plugin are different.

**Comment by murdos** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/188977

**Comment by pascalgrimaud** [comment]
@murdos : approved
