### ISSUE TITLE
Cassandra migrations

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#5181]
Following https://github.com/jhipster/jhipster-lite/issues/877

**Comment by Yourgene** [comment]
Hi @pascalgrimaud,
Thank you for the review+merge, and adding a bug bounty on it, it was pleasant surprise for me :)

I have a last cassandra PR, to add the `dummy-cassandra` module. 
Could you create an issue and assign it to me as you did for this one ? 
I dont have a lot of free time this week, so the PR should come around the weekend

**Comment by pascalgrimaud** [comment]
Thanks for your work @Yourgene 
No worry, it's open source, so no hurry. Take your time :-)

I'll create the ticket right now
