### ISSUE TITLE
Generates test files with vitest imports but npm scripts run jest

### ISSUE THREAD

**Issue by matthewreed26** [jhipster/jhipster-lite#5400]
Generated the Vue Typescript as shown:
![Screen Shot 2023-02-18 at 6 06 40 PM](https://user-images.githubusercontent.com/15159154/219903472-5f1d382f-2bc3-4edd-b6d6-3e27768666ca.png)

Initially, `npm run test` runs `jest` but tests (seen on the right) are importing from vitest so the tests fail:
![Screen Shot 2023-02-18 at 6 04 51 PM](https://user-images.githubusercontent.com/15159154/219903468-37da6274-2669-45ec-ae4c-81b5b6680c1a.png)

My change of npm script `test` to run `vitest`, passes all tests and exhibits behavior similar to `jest --watch`:
![Screen Shot 2023-02-18 at 6 05 29 PM](https://user-images.githubusercontent.com/15159154/219903470-614236a7-97d9-4b4b-9cc7-674e17aae2c2.png)

There also appears to be something up with the `AppVue` in `Router.spec.ts` as well:
![Screen Shot 2023-02-18 at 6 28 57 PM](https://user-images.githubusercontent.com/15159154/219904028-0a7ab4ba-970e-47c9-8d73-22c8004169be.png)

**Comment by pascalgrimaud** [comment]
Thanks for reporting this @matthewreed26

I think the problem comes from Typescript, which uses Jest. But Vue doesn't need Jest as it uses Vitest.

The goal of typescript was to init some project to do some Katas, so this module needs to be rework

**Comment by qmonmert** [comment]
@pascalgrimaud you reproduce this bug?

**Comment by pascalgrimaud** [comment]
Adding a bounty on this
The goal would be to remove jest dependency and all related scripts in the module which uses Vitest instead

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
