### ISSUE TITLE
eslint --fix failed without output (ENOENT). (React)

### ISSUE THREAD

**Issue by mbaus** [jhipster/jhipster-lite#5435]
I am new to jhipster lite.  

But every time I want to check in react code I get the following error:

```
git commit -m 'create beers service'                                                                                                                                                                                      on git:main|●1✚2…1
✔ Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ .lintstagedrc.js — 1 file
    ❯ {src/**/,}*.{js,ts,tsx,vue} — 1 file
      ✖ eslint --fix [ENOENT]
    ↓ {src/**/,}*.{md,json,yml,html,css,scss,java,xml} — no files [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ eslint --fix failed without output (ENOENT).
husky - pre-commit hook exited with code 1 (error)
```
At this time the solution is to disabel the husky-pre commit. But is not what I want.

**Comment by DamnClin** [comment]
Hello, there is a file in .jhipster with applied modules and there configuration, can't you provide the content of the file so we can try to reproduce?

**Comment by mbaus** [comment]
Hello,
on my last try with jhipster-lite, i followed this example: https://blog.ippon.tech/how-to-create-a-quick-react-and-angular-app-with-jhipster-lite/

I also used the docker container in the specified version. I can't see any difference to the current version in the concrete example.

First I built the project with ./mvnw (it makes no difference running npm first).

After creating the environment, I created the first three files and try to check them in one by one.

The first hurdle in this approach was the execution rights for .husky/pre-commit were not set. (this happens with the unzip but is not a problem.)

The first file can be checked in with the note that the .husky/pre-commit is not executable.

After I set the rights, the second checkin fails.

Here is the content of the .jhipster/modules/history.json file:
``` 
{
  "actions" : [ {
    "module" : "init",
    "date" : "2023-02-21T21:37:08.987820863Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "maven-java",
    "date" : "2023-02-21T21:37:10.006771445Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "java-base",
    "date" : "2023-02-21T21:37:10.585281014Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "spring-boot",
    "date" : "2023-02-21T21:37:11.970085147Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "spring-boot-tomcat",
    "date" : "2023-02-21T21:37:12.922976710Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "spring-boot-cucumber",
    "date" : "2023-02-21T21:37:14.222211141Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "springdoc-mvc-openapi",
    "date" : "2023-02-21T21:37:15.390164004Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "zalando-problems",
    "date" : "2023-02-21T21:37:16.271113658Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "spring-boot-jwt",
    "date" : "2023-02-21T21:37:17.631910326Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "spring-boot-cucumber-jwt-authentication",
    "date" : "2023-02-21T21:37:19.572779070Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "dummy-feature",
    "date" : "2023-02-21T21:37:20.705198344Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "springdoc-jwt",
    "date" : "2023-02-21T21:37:50.869240472Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "spring-boot-jwt-basic-auth",
    "date" : "2023-02-21T21:37:52.029061260Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "prettier",
    "date" : "2023-02-21T21:38:21.637420984Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "react-core",
    "date" : "2023-02-21T21:38:22.800220690Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "react-jwt",
    "date" : "2023-02-21T21:38:24.234321670Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "frontend-maven-plugin",
    "date" : "2023-02-21T21:39:06.735432081Z",
    "properties" : {
      "packageName" : "de.dacomb.library",
      "projectName" : "My Test Library",
      "baseName" : "library",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  } ]
}
```

**Comment by pascalgrimaud** [comment]
@mbaus : thanks for reporting this, but I didn't manage to reproduce.
- I tested with last tag
- I tested with Docker image
- everything works fine for me

Maybe you could provide a public GitHub project so I can have a look plz?

**Comment by mbaus** [comment]
@pascalgrimaud: thanks for testing it.

Yes, I have provided an example in github so you can reproduce my problem.

You can find it here:
https://github.com/mbaus/sample-lite

I also created an INFO.md file and described the steps to reproduce there.

For better understanding, I recorded two sessions with asciinema. I hope this also helps to understand the problem.

I suspect there are missing libraries or there is an error in the configuration of Prettier or eslint.

Tonight I'll create a new branch of the example repository and try my idea. If I get a positive result, we can discuss my findings.

Best regards and stay healthy

**Comment by mbaus** [comment]
@pascalgrimaud: I Change the Configuration and add som js Librarys.
After that I add a field to my interface to get a dummy change and can commit it again. 

before I commit the interface I enable husky 

and it works fine.

Plz try it out. THX

**Comment by pascalgrimaud** [comment]
Thanks, I manage to reproduce your issue with your project.
I'll have a look later on this, to understand why it can happen

**Comment by qmonmert** [comment]
@mbaus I tested your repo

Add these 3 dev dependencies in your package.json:
```
"eslint": "^8.34.0",
"eslint-plugin-import": "^2.27.5",
"eslint-plugin-react": "^7.32.2",
```
then run:
```
npm install
```
Create a `.eslintrc.js` at the root of your repo with this content (this is an example):
```
module.exports = {
    env: {
      commonjs: true,
      node: true,
      browser: true,
      es6: true,
      jest: true,
    },
    extends: ["eslint:recommended", "plugin:react/recommended"],
    globals: {},
    parserOptions: {
      ecmaFeatures: {
        jsx: true,
      },
      ecmaVersion: 2018,
      sourceType: "module",
    },
    plugins: ["react", "import"],
    ignorePatterns: ["node_modules/"],
    rules: {
        "react/react-in-jsx-scope": "off",
    }
};
``` 
then run:
```
git add -A
git commit -m "test"
```
![image](https://user-images.githubusercontent.com/9989211/221265985-04eb8108-082e-4b63-b0d8-1d7639d90125.png)
Seems good 🙂

**Comment by mbaus** [comment]
@qmonmert : THX for your answer.

Are you sure this is the right solution?

I follow the steps you describe.

After that I take the next file of the tutorial.
And check it in.

Things are looking better now because eslint is doing its job.
Now the colon is considered an error in TypeScript.

```
../src/main/webapp/app/beers/services/beers.ts
  8:38  error  Parsing error: Unexpected token :

✖ 1 problem (1 error, 0 warnings)
```

As a quick fix for me, it's clear that I need to configure eslint myself to be able to use it. Which, in principle, everyone will do.

The reason for reporting this issue is that the initial JHipster configuration contains an incorrect configuration or no indication that you need to create the configuration yourself.

It even goes a little further. I watched Colin Damon's [YouTube video](https://www.youtube.com/watch?v=mEECPRZjajI) . It's very well explained. At the end there is a nice RestService in hexagonal architecture.

Building on that, I then added the components used in the tutorial above.

Here react-jwt is selected in step 7 almost at the end.
I found out that this step installs react-core first. The commit that follows fails because eslint is missing from the generator or is not configured correctly.

If I follow the description here to add the configuration and missing dependencies, I can check in react-core, but react-jwt fails because eslint is not configured for typescript here.

The current workaround for me is after installing the prettier one, adjust the config and manually reload dependencies that work for me.

My expectation from the jhipster lite generator is that the modules can be loaded without breaking the build.

Over the coming week I can write down the scenarios I've tested and where the build breaks without manual intervention. And with what additional intermediate steps there are no problems.

Best regards and stay healthy

**Comment by pascalgrimaud** [comment]
> My expectation from the jhipster lite generator is that the modules can be loaded without breaking the build.

Totally true, without modification, each modules should be loaded without being broken

**Comment by qmonmert** [comment]
@mbaus you're right, I fix that

**Comment by mbaus** [comment]
> @mbaus you're right, I fix that

I'm interested in testing it once you fix the bug.

**Comment by qmonmert** [comment]
@mbaus Pull Request here https://github.com/jhipster/jhipster-lite/pull/5478 😉

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/128121 :)

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
