### ISSUE TITLE
The same bean 'customConversions' will be created if applied both Mongodb and Redis

### ISSUE THREAD

**Issue by medoer** [jhipster/jhipster-lite#5774]
`@Configuration
@EnableRedisRepositories({ "com.xx.demo" })
@Import(value = RedisAutoConfiguration.class)
public class RedisDatabaseConfiguration {

  @Bean
  public RedisCustomConversions customConversions() {
    return new RedisCustomConversions(List.of(DateToZonedDateTimeConverter.INSTANCE, ZonedDateTimeToDateConverter.INSTANCE));
  }
}`

`@Configuration
@EnableMongoRepositories({ "com.xx.demo" })
@Import(value = MongoAutoConfiguration.class)
public class MongodbDatabaseConfiguration {

  @Bean
  public MongoCustomConversions customConversions() {
    List<Converter<?, ?>> converters = new ArrayList<>();
    converters.add(DateToZonedDateTimeConverter.INSTANCE);
    converters.add(ZonedDateTimeToDateConverter.INSTANCE);
    return new MongoCustomConversions(converters);
  }
}
`
Same bean name 'customConversions'.

**Comment by pascalgrimaud** [comment]
Any suggestion for this @juliensadaoui ?

**Comment by DamnClin** [comment]
> Any suggestion for this @juliensadaoui ?

A simple rename of the beans will work I think :D
