### ISSUE TITLE
Do not exist methods test case for CacheConfiguration class

### ISSUE THREAD

**Issue by medoer** [jhipster/jhipster-lite#5775]
The CacheConfiguration class just a @Configuration with a EnableCaching annotation. But have two test class use its methods.

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/20471718/227707741-df7d590c-eb95-4fd5-9bf6-27d8abb14b36.png">

<img width="801" alt="image" src="https://user-images.githubusercontent.com/20471718/227707750-4cba3a61-af12-4715-a9e3-0ec12a3d9438.png">

**Comment by pascalgrimaud** [comment]
@medoer : can you provide the step you used? at least which modules did you use, so I can try to reproduce the issue

**Comment by medoer** [comment]
> 

OK, I will try and give you the step later.

**Comment by medoer** [comment]
> @medoer : can you provide the step you used? at least which modules did you use, so I can try to reproduce the issue

I try and find that when i supported both ehcache-java-config and spring-boot-cache, the `CacheConfiguration ` will be cleared.

**Comment by medoer** [comment]
.hipster/modules/hisotry.json

`{
  "actions" : [ {
    "module" : "init",
    "date" : "2023-03-27T13:34:58.193913Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "maven-java",
    "date" : "2023-03-27T13:34:58.225338Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "java-base",
    "date" : "2023-03-27T13:34:58.239758Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "spring-boot",
    "date" : "2023-03-27T13:34:58.281200Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "ehcache-java-config",
    "date" : "2023-03-27T13:34:58.306741Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "spring-boot-cache",
    "date" : "2023-03-27T13:34:58.328374Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  } ]
}`

**Comment by pascalgrimaud** [comment]
Thanks @medoer, now I understand
Indeed, there is a bug with Spring Boot Cache. For now, you need to choose only 1: spring boot cache or ehcache-java-config
Not both

**Comment by medoer** [comment]
> 

OK.
