### ISSUE TITLE
The project can not running when mongodb been supported.

### ISSUE THREAD

**Issue by medoer** [jhipster/jhipster-lite#5776]
The project can not running success when mongodb was applied, with the error 

`This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.` 

And i try to config like this `spring.data.mongodb.uri=mongodb://localhost:27017/?retryWrites=false`, but it not working for me in my native env.

Can you help me for this.

**Comment by pascalgrimaud** [comment]
@medoer : you need to provide more information to reproduce, otherwise we can't know which config / modules you used

Just tested an application with mongodb and it works fine:

![image](https://user-images.githubusercontent.com/9156882/227865300-80c8c2bb-ae9f-48af-a76b-f391815fc8bb.png)

**Comment by medoer** [comment]
I don't know what happened, after restart the project several times, it's working now.
