### ISSUE TITLE
Using Spring Boot without the Parent POM

### ISSUE THREAD

**Issue by MarlonLuan** [jhipster/jhipster-lite#579]
Sugestion: Change spring-boot-starter-parent to dependency management,

Allowing greater decoupling between the software and the framework

When migrating to other framework like quarkus it would be simpler

https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#using.import

**Comment by pascalgrimaud** [comment]
I'm not against this.
The use of parent is the default solution when using Spring Initializr: https://start.spring.io/

As the result is the same, but the use of dependency management give more flexibility, let's do it

**Comment by beatfreaker** [comment]
@pascalgrimaud Can you please assign this issue to me?
created a PR with the fix.

**Comment by MarlonLuan** [comment]
It is necessary to verify the need to configure the plugins, since with the change of the parent for the dependency management, the plugin configurations are not inherited

**Comment by beatfreaker** [comment]
> It is necessary to verify the need to configure the plugins, since with the change of the parent for the dependency management, the plugin configurations are not inherited

@MarlonLuan thank you for catching that
