### ISSUE TITLE
npm dependencies version conflict when applied both optional-typescript and angular-core

### ISSUE THREAD

**Issue by medoer** [jhipster/jhipster-lite#5965]
Both optional-typescript and angular-core module dependence the jest and so on ,when applied both of them the optional-typescript version in common/package.json will override the version in angular/package.json.

I try to fix this in #5963 , but it is just upgrade the version in common/package.json. 

Is this is an issue?

**Comment by qmonmert** [comment]
+1 to delete `optional-typescript`. I can do it.

**Comment by pascalgrimaud** [comment]
Let's give a chance to the original author to have a look and answer :-)

**Comment by qmonmert** [comment]
ok 🙂

**Comment by pascalgrimaud** [comment]
@medoer : yes I understand the issue. But I would say, it's the responsability of the owner of the module to choose the correct version

Anyway, on my side, what I do when I apply a module:
- create a new branch in my project
- uncheck the auto commit
- apply the module
- verify each change, and sometime modify what I don't want or what I don't like
- manual commit

So with this workflow, I have full control of what I use

**Comment by medoer** [comment]
@pascalgrimaud OK.

**Comment by pascalgrimaud** [comment]
As no answer from @thomaslmbrt, do you want to take the lead on this module @medoer ?

Otherwise, I'll disable or delete it.

**Comment by medoer** [comment]
> As no answer from @thomaslmbrt, do you want to take the lead on this module @medoer ?
> 
> Otherwise, I'll disable or delete it.

yes, I can do it if the author no answer. Just keep the module, I will keep the dependency version same with angular module.

**Comment by medoer** [comment]
> As no answer from @thomaslmbrt, do you want to take the lead on this module @medoer ?
> 
> Otherwise, I'll disable or delete it.

yes, I can do it if the author no answer. Just keep the module, I will keep the dependency version same with angular module.

**Comment by medoer** [comment]
just like this #5963 , synchronization the version  about jest and so on.
