### ISSUE TITLE
Rename generated fast profile to local profile

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#602]
Currently, in generator-jhipster, we have dev and prod profile, which is so confusing

In JHipster Lite, I created 'fast' profile but I don't think the name is correct. I think it's better to name it: local

**Comment by qmonmert** [comment]
I'm on it

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/62533 😛

**Comment by pascalgrimaud** [comment]
Thanks and approved @qmonmert 
I needed this ticket for this one: https://github.com/jhipster/jhipster-lite/issues/621

**Comment by qmonmert** [comment]
thanks @pascalgrimaud :)
