### ISSUE TITLE
Make Docker images public

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-lite#6101]
I realize that images published at https://github.com/jhipster/jhipster-lite/pkgs/container/jhipster-lite are private, is there a reason for that?

**Comment by pascalgrimaud** [comment]
No particular reason, as it's the default config
The official image is at Docker Hub, I didn't know we're using the GitHub images, as it was coded by @PierreBesson

**Comment by jdubois** [comment]
Oh indeed, we should use the Docker Hub instead, as 1) we have a deal with them so we have no rate limiting there (much better for our users) and 2) it's easier to configure and better known.
