### ISSUE TITLE
Sonarcloud: 6 bugs and 15 code smells

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#6146]
See https://sonarcloud.io/summary/overall?id=jhipster_jhipster-lite

Need to be fixed:
- 6 bugs
- 15 code smells

**Comment by pascalgrimaud** [comment]
Reopened it, as it's not totally fixed
And increasing the bounty as it's more work than expected

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/137849 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by qmonmert** [comment]
@pascalgrimaud 🙏
