### ISSUE TITLE
Use get version, managed by dependabot

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#615]

**Comment by pascalgrimaud** [comment]
easy ticket but a little bit long, as it needed to be done in each context
As you started this, I'm assigning this to you @DanielFran

**Comment by pascalgrimaud** [comment]
I don't know, if you think it's ok, we can close it, and later, if needed, we'll improve other part

**Comment by pascalgrimaud** [comment]
@DanielFran : dont forget to claim your bounty here

**Comment by DanielFran** [comment]
@pascalgrimaud Latest PR done ;)

**Comment by DanielFran** [comment]
@pascalgrimaud Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/64241

**Comment by pascalgrimaud** [comment]
@DanielFran : approved, thanks for your help
