### ISSUE TITLE
The "./mvnw sonar:sonar " command execution exception

### ISSUE THREAD

**Issue by medoer** [jhipster/jhipster-lite#6223]
The history json

`{
  "actions" : [ {
    "module" : "init",
    "date" : "2023-05-10T14:27:21.590888Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "application-service-hexagonal-architecture-documentation",
    "date" : "2023-05-10T14:27:21.769215Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "gradle-wrapper",
    "date" : "2023-05-10T14:27:21.797960Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "infinitest-filters",
    "date" : "2023-05-10T14:27:21.831092Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "maven-wrapper",
    "date" : "2023-05-10T14:27:21.850067Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "maven-java",
    "date" : "2023-05-10T14:27:22.019822Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "prettier",
    "date" : "2023-05-10T14:27:22.062589Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "typescript",
    "date" : "2023-05-10T14:27:22.089359Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "dockerfile",
    "date" : "2023-05-10T14:27:22.132483Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "github-actions",
    "date" : "2023-05-10T14:27:22.166376Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "jacoco-check-min-coverage",
    "date" : "2023-05-10T14:27:22.213982Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "java-base",
    "date" : "2023-05-10T14:27:22.257354Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "jib",
    "date" : "2023-05-10T14:27:22.316529Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "react-core",
    "date" : "2023-05-10T14:27:22.365569Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "sonar-qube-java-backend-and-frontend",
    "date" : "2023-05-10T14:27:22.411438Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "java-enums",
    "date" : "2023-05-10T14:27:22.448231Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "pagination-domain",
    "date" : "2023-05-10T14:27:22.509773Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "playwright",
    "date" : "2023-05-10T14:27:22.541719Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "react-jwt",
    "date" : "2023-05-10T14:27:22.584520Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "spring-boot",
    "date" : "2023-05-10T14:27:22.653784Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  }, {
    "module" : "spring-boot-mvc-empty",
    "date" : "2023-05-10T14:27:22.697823Z",
    "properties" : {
      "packageName" : "com.medo.computer",
      "projectName" : "Computer1",
      "baseName" : "computer",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2,
      "oktaDomain" : "dev-123456.okta.com",
      "oktaClientId" : "0oab8eb55Kb9jdMIr5d6"
    }
  } ]
}`

The exception when run ./mvnw sonar:sonar

`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project computer: Error during parsing of generic test execution report '/Users/xxtarget/test-results/TESTS-results-sonar.xml'. Look at the SonarQube documentation to know the expected XML format.: /Users/xx/target/test-results/TESTS-results-sonar.xml (No such file or directory) -> [Help 1]`

**Comment by pascalgrimaud** [comment]
If you didn't run tests yet, you need to launch: `./mvnw clean verify sonar:sonar`

If you already launch test, you can use: `./mvnw initialize sonar:sonar`

Be sure your sonar instance is started. You should have a similar documentation: https://github.com/jhipster/jhipster-lite-sample-app/blob/main/documentation/sonar.md
