### ISSUE TITLE
Local properties storage do no reset

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#6279]
The local properties storage do not reset when changing folder wich is really annoying since, when you start a new application, you still have properties from the previous one. We need to keep properties only for the same application

**Comment by DamnClin** [comment]
No rush, this is annoying but usable (just a doubt that you'll see more properties than needed)

**Comment by renanfranca** [comment]
Hello @DamnClin,

today when click on Module Patch or Landscape menu the folder path is refreshed with a random directory. if the local storage got clear when the folder path change, it will be clear every time.

Can I store the folder path at the local storage after it got generated? What do you think about it?

**Comment by DamnClin** [comment]
You need to have a key depending on the path because we can change path whenever we want :)

**Comment by renanfranca** [comment]
> You need to have a key depending on the path because we can change path whenever we want :)

Thank you, I will store the folder path with a specific key each time it gets changed and clear the properties from storage before loading the module's history ✌️.
