### ISSUE TITLE
Utils in common domain use external library

### ISSUE THREAD

**Issue by Bolo89** [jhipster/jhipster-lite#641]
Utils, in common/domain, should not depend on external libraries (ObjectMapper / jackson).
They can be moved in common/ infra/utils

**Comment by Bolo89** [comment]
@pascalgrimaud , as discussed, for me, it is useless to implement hexa architecture in utility class. The coupling is too strong with the external libs and create min 3 files for each util only to respect the architecture is overkill.

**Comment by pascalgrimaud** [comment]
then, you're right, let's close this so
