### ISSUE TITLE
Authentication module using Webflux

### ISSUE THREAD

**Issue by yacosta738** [jhipster/jhipster-lite#6610]
Implement the authentication and authorization logic using Webflux for 100% reactive applications.

[Spring Security Reactive Apps](https://docs.spring.io/spring-security/reference/reactive/getting-started.html)

**Comment by pascalgrimaud** [comment]
Your contributions are welcome @yacosta738 :-)

**Comment by pascalgrimaud** [comment]
I forgot this ticket https://github.com/jhipster/jhipster-lite/issues/1774
It's duplicated, so I'm closing this one

Plz, feel free to contribute if you want this module @yacosta738
