### ISSUE TITLE
Improve CI to not launch same tests

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#6651]
For each builds, we should compare:
- the hash of the generated project from main branch
- the hash of the generated project from pull request
- if it's different, launch the build
- otherwise, it should be success

With this change, we won't launch same builds for each pull requests

**Comment by pascalgrimaud** [comment]
@renanfranca : I saw a small issue. Every code in main branch should launch all tests. This new logic should apply only for pull request. What do you think?
Otherwise, there are no test anymore in main branch

**Comment by renanfranca** [comment]
> @renanfranca : I saw a small issue. Every code in main branch should launch all tests. This new logic should apply only for pull request. What do you think? Otherwise, there are no test anymore in main branch

I am going to skip the new steps, even the job generate-main-branch-jar if it is not in a pull request. I am going to create a new pull request for that. Thanks 👍
