### ISSUE TITLE
Wrong executable Jar file

### ISSUE THREAD

**Issue by skin27** [jhipster/jhipster-lite#6652]
Until version 0.27 there was always an executable jar file (of around 50 mb) in the release assets. After that this is not provided anymore, and there only a small jar with test.jar extension.

Question: Is there still an executable jar available? Or are building from source or using Docker now the only options?

**Comment by pascalgrimaud** [comment]
Thanks @skin27 : it's clearly a bug ! I'll have a look soon

**Comment by pascalgrimaud** [comment]
I uploaded all correct jar files in each releases, from v0.28.0 to v0.35.0
For the next releases, it should be fixed by https://github.com/jhipster/jhipster-lite/pull/6664
