### ISSUE TITLE
Spring properties text block are not in the right order

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#6654]
Spring properties text blocks ends up adding the comment in random places in the comment block. Expected behavior is to add a line before the properties block

**Comment by pascalgrimaud** [comment]
adding a bounty for this bug

**Comment by renanfranca** [comment]
> Spring properties text blocks ends up adding the comment in random places in the comment block. Expected behavior is to add a line before the properties block

Hello @DamnClin!
If you have the time, can you give me a practical example of this unexpected behavior?

Thank you in advance 😊

**Comment by renanfranca** [comment]
> > > Spring properties text blocks ends up adding the comment in random places in the comment block. Expected behavior is to add a line before the properties block
> > 
> > Hello @DamnClin! If you have the time, can you give me a practical example of this unexpected behavior?
> > 
> > Thank you in advance blush
> 
> Not right now, I found this working for a client and I don't have access to this code base right now :D

😅! Can you show me an example with a pseudo code?

Thanks 😊

**Comment by renanfranca** [comment]
Hello @DamnClin,
I took a look at the code. The already implemented unit test at `FileSystemSpringCommentsCommandsHandlerTest` cover this scenario:
1 - The following properties:
```property
			spring.application.name=JHLite
			springdoc.swagger-ui.tryItOutEnabled=alpha
			logging.level.tech.jhipster.lite=INFO
			springdoc.swagger-ui.tagsSorter=alpha
			springdoc.swagger-ui.operationsSorter=alpha
```

2 - Add the comment `##Swagger properties` at the swagger code block:
```java
  private SpringPropertiesBlockComments springPropertiesBlockCommentsOnPropertyType(SpringPropertyType springPropertyType) {
    Map<PropertyKey, PropertyValue> properties = new LinkedHashMap<>();
    properties.put(propertyKey("springdoc.swagger-ui.operationsSorter"), propertyValue("alpha"));
    properties.put(propertyKey("springdoc.swagger-ui.tagsSorter"), propertyValue("alpha"));
    properties.put(propertyKey("springdoc.swagger-ui.tryItOutEnabled"), propertyValue("alpha"));
    return new SpringPropertiesBlockComments(
      List.of(
        SpringPropertiesBlockComment.builder(springPropertyType).comment(comment("Swagger properties")).properties(properties).build()
      )
    );
  }
```
3 - And the expected result is:
```property
		spring.application.name=JHLite
		logging.level.tech.jhipster.lite=INFO
		## Swagger properties
		springdoc.swagger-ui.operationsSorter=alpha
		springdoc.swagger-ui.tagsSorter=alpha
		springdoc.swagger-ui.tryItOutEnabled=alpha
```

Another scenario is when the block property already has an individual property comment:

1 - The given properties:
```property
        spring.application.name=JHLite
        # This is a comment
        springdoc.swagger-ui.tryItOutEnabled=alpha
        logging.level.tech.jhipster.lite=INFO
        # This is a comment
        springdoc.swagger-ui.tagsSorter=alpha
        springdoc.swagger-ui.operationsSorter=alpha
```
2 - Add the comment `##Swagger properties` at the swagger code block:
```java
  private SpringPropertiesBlockComments springPropertiesBlockCommentsOnPropertyType(SpringPropertyType springPropertyType) {
    Map<PropertyKey, PropertyValue> properties = new LinkedHashMap<>();
    properties.put(propertyKey("springdoc.swagger-ui.operationsSorter"), propertyValue("alpha"));
    properties.put(propertyKey("springdoc.swagger-ui.tagsSorter"), propertyValue("alpha"));
    properties.put(propertyKey("springdoc.swagger-ui.tryItOutEnabled"), propertyValue("alpha"));
    return new SpringPropertiesBlockComments(
      List.of(
        SpringPropertiesBlockComment.builder(springPropertyType).comment(comment("Swagger properties")).properties(properties).build()
      )
    );
  }
```
3 - And the expected result:
```property
          spring.application.name=JHLite
          logging.level.tech.jhipster.lite=INFO
          ## Swagger properties
          springdoc.swagger-ui.operationsSorter=alpha
          # This is a comment
          springdoc.swagger-ui.tagsSorter=alpha
          # This is a comment
          springdoc.swagger-ui.tryItOutEnabled=alpha
```

Maybe there's a given scenario that is not covered. When you have the time, let me know if you have a different scenario in mind and I create a test to fail and then I will make the test green by implementing the solution.

Thank you 😄

**Comment by murdos** [comment]
Spring properties text block has been removed as part of #7939, so this issue is not relevant any more.
