### ISSUE TITLE
Dependabot: Docker images

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#671]
The first step would be:
- read Dependabot docs about Docker :-D
- create some Dockerfiles or Docker Compose, which contains the version of the image we use
- then, add the config in dependabot file of the project
- check if the images are regularly updated

Then, we can create a service to read these versions in another PR

**Comment by Bolo89** [comment]
@pascalgrimaud possible to assign me this issue ?

**Comment by pascalgrimaud** [comment]
@Bolo89 : done. Plz do it in different pull requests, as suggested in the ticket

**Comment by pascalgrimaud** [comment]
it's so huge work. I'm increasing the bounty
