### ISSUE TITLE
Upgrade to prettier 3.x

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#6802]
We should upgrade to prettier 3.x

**Comment by murdos** [comment]
We may need to wait for https://github.com/jhipster/prettier-java/pull/558 and a new prettier-java release :)

**Comment by murdos** [comment]
Also blocked by https://github.com/prettier/eslint-plugin-prettier/issues/562 and release of eslint-plugin-prettier 5.0.0

**Comment by murdos** [comment]
- [ ] Also need a release of vuejs/eslint-config-prettier too https://github.com/vuejs/eslint-config-prettier/issues/16 (with a temporary circumvention: https://github.com/vuejs/eslint-config-prettier/issues/16#issuecomment-1624832382)

**Comment by murdos** [comment]
- [ ] svelte generated applications should stay with Prettier 2.x until prettier-plugin-svelte is compatible: https://github.com/sveltejs/prettier-plugin-svelte/issues/317

**Comment by pascalgrimaud** [comment]
Increasing the bounty as it's more work than expected

Plz @murdos and @qmonmert : sync your work to provide 1 single PR, then the bounty can be shared, as it has just been increased :-)

**Comment by murdos** [comment]
@pascalgrimaud : consolidated work is in https://github.com/jhipster/jhipster-lite/pull/6810 :)

**Comment by murdos** [comment]
> @murdos @qmonmert : thanks. Is https://github.com/jhipster/jhipster-lite/pull/6810 ready to be merged?

Yes, it is 🙂

**Comment by qmonmert** [comment]
Yes

**Comment by pascalgrimaud** [comment]
Cool, I'll have free time to review and test it tomorrow

**Comment by qmonmert** [comment]
@murdos 300 for you and 200 for me? 🙂🤝

cc @pascalgrimaud

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/149888 200 for me 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by qmonmert** [comment]
thanks

**Comment by murdos** [comment]
bounty claimed: https://opencollective.com/generator-jhipster/expenses/149890 :-)
