### ISSUE TITLE
Switch to non parallel stream in rest pagination mapping

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#6803]
Update needs to be done here: https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache

**Comment by murdos** [comment]
It should be removed from the jpa pagination mapping too: https://github.com/jhipster/jhipster-lite/blob/197c063cb9d4127dcd121131431ec894596f03d1/src/main/resources/generator/server/pagination/jpa/AppPages.java.mustache#L34

**Comment by murdos** [comment]
@DamnClin : you self assigned this issue, so I'm assuming you already have a fix or intend to do it.
Otherwise let me know, I can take care of the fix.

**Comment by DamnClin** [comment]
> @DamnClin : you self assigned this issue, so I'm assuming you already have a fix or intend to do it. Otherwise let me know, I can take care of the fix.

Sorry, self assign was a mistake, I was thinking to leave it as a good first issue since we need more of them :D

**Comment by murdos** [comment]
> Sorry, self assign was a mistake, I was thinking to leave it as a good first issue since we need more of them :D
Ok, then I'm leaving this issue for new contributors :)

**Comment by jayasekharreddy-telluri** [comment]
can i take these issue?

**Comment by DamnClin** [comment]
> can i take these issue?

All yours

**Comment by jayasekharreddy-telluri** [comment]
can i get some information like what needs to be done?

**Comment by DamnClin** [comment]
Explained in issue and comments :⁠-⁠)

> Update needs to be done here: https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache

**Comment by jayasekharreddy-telluri** [comment]
can i know how to run the code VS code..

**Comment by DamnClin** [comment]
https://github.com/jhipster/jhipster-lite/blob/main/CONTRIBUTING.md

**Comment by jayasekharreddy-telluri** [comment]
ok i made the changes but i dont know how to check means i would like to check in frontend how my change is impacting please guide me..

**Comment by DamnClin** [comment]
> ok i made the changes but i dont know how to check means i would like to check in frontend how my change is impacting please guide me..

What do you want to check in the frontend? This is tested automatically, you don't need manual checks

**Comment by jayasekharreddy-telluri** [comment]
I have to know right what's happening after switching  stream to non parallel stream whether we are getting the pagination results are correct or not?

**Comment by DamnClin** [comment]
Yes, push your code to the repository, an application will be generated and test will be run on this application. You can see tests in the module you updated. There is no need to do manual checks when developing, checks must be automated
