### ISSUE TITLE
Maven: removeDependency doesn't remove property for version

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#6977]
https://github.com/jhipster/jhipster-lite/blob/4f375e7bde3f7c7ca877b52bddc503509e44bea3/src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootCoreModuleFactory.java#L57 does not remove `<mockito.version>5.4.0</mockito.version>` in `pom.xml` 

See https://github.com/jhipster/jhipster-lite-sample-app/blob/0df81108ece4f8838e4236753e006000775b2fb5/pom.xml#L24C6-L24C21

TO-DO: Implement safe removal of versions
- [x] When removing the dependency manager
- [x] When removing a direct dependency
- [x] Profile: When removing the dependency manager
- [x] Profile: When removing a direct dependency

**Comment by pascalgrimaud** [comment]
I wonder if the method `removeDependency` should remove the version too, or should we add a new method `removeVersion`?
I'd prefer the 2nd solution, with a new method

**Comment by murdos** [comment]
The

> I wonder if the method `removeDependency` should remove the version too, or should we add a new method `removeVersion`? I'd prefer the 2nd solution, with a new method

The property is added automatically when a dependency is added. If possible it would be nice the automatically remove the property if it not used anymore. But I will think more about it and see how it would translate it the gradle side too.

**Comment by DamnClin** [comment]
Not that simple since a version property can be used by multiple dependencies

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/209365. Thanks 😁👍

**Comment by pascalgrimaud** [comment]
@renanfranca : approved
