### ISSUE TITLE
Reorganize memoizers resources

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#7028]
The [memoizers resources](https://github.com/jhipster/jhipster-lite/tree/main/src/main/resources/generator/server/javatool/memoizers) needs to be split in `main` and `test` (and updated in [module factory](https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/server/javatool/memoizer/domain/JavaMemoizersModuleFactory.java))

**Comment by jayasekharreddy-telluri** [comment]
hi @DamnClin  could you please give the some more information about these issue so that i can understand it better and i  will solve these issue

**Comment by pascalgrimaud** [comment]
@jayasekharreddy-telluri : 

You can look at this folder: https://github.com/jhipster/jhipster-lite/tree/main/src/main/resources/generator/server/pagination/domain

The templates are splitted between main and test folders

So we should do the same for the memoizer module
