### ISSUE TITLE
Missing line break in AppPages

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#7032]
[AppPages](https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/pagination/jpa/AppPages.java.mustache) have a missing line break between assertions and operation in `from(Page<S> springPage, Function<S, T> mapper)`

**Comment by Saravana-PS** [comment]
Hi @DamnClin , I would like to work on this issue. Can you please assign this on me?

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/jhipster-lite/pull/7066
