### ISSUE TITLE
RestAppPage formatting is off

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#7033]
[RestAppPage](https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache) formatting in `from({{baseName}}Page<S> source, Function<S, T> mapper)` is off:

* Missing line break between assertions and return;
* Miss aligned return statement.

**Comment by jayasekharreddy-telluri** [comment]
can i take these issue?

**Comment by DamnClin** [comment]
Yep
