### ISSUE TITLE
CI: rerun release drafter

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#7089]
Give the possibility to rerun release drafter by adding the workflow dispatch
- see https://github.com/jhipster/jhipster-lite/blob/main/.github/workflows/github-actions.yml#L6
- need to add it there too: https://github.com/jhipster/jhipster-lite/blob/main/.github/workflows/release-drafter.yml#L2

**Comment by Saravana-PS** [comment]
@pascalgrimaud Is it just enough to add the contents of release-drafter.yml  into the github-actions file?

**Comment by pascalgrimaud** [comment]
Adding ' workflow_dispatch:' in release-drafter.yml is enough. No need to merge both file

**Comment by Saravana-PS** [comment]
@pascalgrimaud Sure, I would like take up this issue. Can you assign it on me?
