### ISSUE TITLE
testcontainers: exclude junit

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#7101]
When there is  `testcontainers` dependency, there are 2 junit dependencies. The results in IDE are:

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/429d837a-f097-4c40-9f05-9d6d8969c9b1)

To avoid this, we should exclude junit:

```xml
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>postgresql</artifactId>
      <version>${testcontainers.version}</version>
      <exclusions>
        <exclusion>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
        </exclusion>
      </exclusions>
      <scope>test</scope>
    </dependency>
```

**Comment by murdos** [comment]
I stumbled upon this issue a few days ago, but it's not as simple as excluding the dependency.
See https://github.com/testcontainers/testcontainers-java/issues/970
There's still a runtime dependency required by testcontainers. A workaround is to recreate fake junit4 rules: https://github.com/spring-projects-experimental/spring-boot-migrator/pull/777/files#diff-f3362ff9066efd77e7727c970892542c62437c2340439773fde412786623bbd4

**Comment by pascalgrimaud** [comment]
Oh nice catch @murdos 
In my project, I don't use GenericContainer so that's why I'm fine, and for existing modules, there is no use of it
