### ISSUE TITLE
License module

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#7102]
It's a perfect module to start to contribute to this project

This module should allow to add:
- license MIT
- license Apache
- etc

**Comment by cvirieux** [comment]
I've started working on this. 

For now I've added Apache and MIT license file as follow : 
![image](https://github.com/jhipster/jhipster-lite/assets/12132069/6134cb1a-2284-41de-9d0f-3fb2e6832936)

I can add more licenses like GNU (AGPL, GPL, LGPL) or Mozilla but I don't know how far to go.

I have also a question on tests. As this is 2 more modules what do I need to add in CI tests ? Do I need to create two tests to cover the two branches ?

**Comment by pascalgrimaud** [comment]
Thanks a log @cvirieux 
I think License Apache and MIT would be enough for now.

Some suggestion about the CI:
- for Apache 2, you can add it to fullapp: https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/generate.sh#L122
- for MIT, another one, maybe oauth2app: https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/generate.sh#L167
- feel free to choose the one you want :)
