### ISSUE TITLE
GeneratorExeptionBuilder class name typo

### ISSUE THREAD

**Issue by a-c-morel** [jhipster/jhipster-lite#7288]
GeneratorExeptionBuilder should be GeneratorExceptionBuilder (with a 'c' after the 'x'.)
https://github.com/jhipster/jhipster-lite/blob/6ee34e4760481ea934c58a65bbb24d8f7ca81dac/src/main/java/tech/jhipster/lite/shared/error/domain/GeneratorException.java#L104

**Comment by DamnClin** [comment]
@a-c-morel  you want to fix it?

**Comment by pascalgrimaud** [comment]
the fix should be:
- in JHLite engine
- in generated projects too

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/fc1eef58-972c-4849-8578-7e7bd3457671)

**Comment by a-c-morel** [comment]
> @a-c-morel you want to fix it?

Yes !

**Comment by DamnClin** [comment]
For the next one: comment Close or Fix with the issue link in the PR so it will be closed when merging :)
