### ISSUE TITLE
Normalize integration tests suffixes

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#7304]
In jhlite code, we have a mix of tests with either `*IntTest` and `IT` suffixes. 
For consistency, I think you should make a choice and stick to it (and enforcing it with an archunit test)

@pascalgrimaud , @DamnClin: WDYT?

**Comment by DamnClin** [comment]
I'm for IntTest :)

**Comment by pascalgrimaud** [comment]
I think it's not only in JHLite code but in generated code too

This choice was to stick closely to generator-jhipster, but it can changed of course
- unit test: *Test
- int test: *IT

Honestly, I don't care about the choice, but I agree we need to be consistent!
What's your preference @murdos ?

**Comment by murdos** [comment]
My preference would go to *IT because it's the canonical suffix used by maven failsafe.
It would allow removing the custom configuration of failsafe and surefire (the include/excludes part).

**Comment by pascalgrimaud** [comment]
> My preference would go to *IT because it's the canonical suffix used by maven failsafe.

Valid point.
Maybe that was the same reason in generator-jhipster too :-D

**Comment by DamnClin** [comment]
Ok for me, I can take it since I probably did the mistake in the first place :D
