### ISSUE TITLE
International errors documentation typos

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#7309]
There are some typos in [application-errors](https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/springboot/mvc/internationalized-errors/documentation/application-errors.md.mustache): 

* sicne -> since;
* have really clear stack -> Have really clear stack;
* ...

**Comment by Sbiswas001** [comment]
Can i do it?

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/jhipster-lite/pull/7737
