### ISSUE TITLE
Suggestion: automatically init a project 

### ISSUE THREAD

**Issue by flcarre** [jhipster/jhipster-lite#734]
Instead of actual error 500 when i want to add a modules in a new path, maybe automatically init a project if path destination do not exist

**Comment by flcarre** [comment]
When i call
POST
/api/vite/vue

with a folder path in my request body that doesn't exist, i've got an Internal Server Error cause my folder is not init. Instead of this error 500, why not call the POST /api/projects/init ?

**Comment by pascalgrimaud** [comment]
I think we can close this, as the behavior is normal
we can't generate a Vue project without existing package.json so the user needs to follow the workflow, the same one when starting from scratch
