### ISSUE TITLE
[suggestions] add different folder archi in front projects

### ISSUE THREAD

**Issue by flcarre** [jhipster/jhipster-lite#735]
For instance we can add atomic design pattern, which is more communly use in front project than hexagonal archi.

https://blog.ippon.tech/atomic-design-in-practice/

https://blog.ippon.fr/2018/05/29/atomic-design-dans-la-pratique/amp/

**Comment by pascalgrimaud** [comment]
I know atomic design pattern, but unless I'm wrong, it's totally another subject.
The goal of JHipster Lite is to generate code and try to organize it in an Hexagonal Architecture, using primary, domain, secondary folders.

For Atomic Design Pattern, it can be related to https://github.com/tikui but it would be another "type" of project.

So in fact, I don't understand well the ticket here :-D

**Comment by flcarre** [comment]
I guess a controller that will create placeholder components following atomic design rules in the primary app folder.

**Comment by nicolasey** [comment]
If I may.
I have seen different hexagonal templates with ability to place folders diffrently, using an array as following : 

`initial/path => different/initial/path`

The goal was to let users choose their own way of organizing their modules. That array allows path customization of a future generated module

**Comment by pascalgrimaud** [comment]
Ok, I got it, thanks for clarification @nicolasey 
It's for giving the possibility to customize like:

```
infrastructure/primary => adapters/in
infrastructure/secondary => adapters/out
```

It could be nice to have but, for now, I don't think we should do this:
- today, this project is not popular enough and giving this possibility will complexify the generator for no real gain
- if the user is not happy with the generated code, he/she can refactorize it to apply the correct path, and it can take less than 1min, so it's very quick
- not enough contributors / not enought final users

So this ticket can be addressed by https://github.com/jhipster/jhipster-lite/issues/1072
As once everything is in constants, the user can simply edit this class, that's all.

Then, really later, we could change these constants into dynamic properties

**Comment by DamnClin** [comment]
cc @nonomoho what do you think, it's ok after https://github.com/jhipster/jhipster-lite/issues/2769?

**Comment by pascalgrimaud** [comment]
Let's discuss first as this ticket is related to 2 different subjects at least

**Comment by pascalgrimaud** [comment]
I'm closing this one as it's not clear enough
Don't hesitate to open a fresh ticket with clear details or comment this one, which can be reopened too
