### ISSUE TITLE
Use dependabot feature for grouping dependencies updates 

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#7414]
Related to #3836 and https://github.com/jhipster/jhipster-lite/issues/3836#issuecomment-1710179206

We can even further group dependencies update thanks to dependabot supporting it: https://github.com/dependabot/dependabot-core/issues/1296
This should allow grouping more update dependencies, and reduce the number of PR and CI load.

**Comment by murdos** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/160753

**Comment by pascalgrimaud** [comment]
@murdos : approved
