### ISSUE TITLE
Add SvelteKit

### ISSUE THREAD

**Issue by flcarre** [jhipster/jhipster-lite#746]

**Comment by flcarre** [comment]
I already have a fully configured Vite+svelte project, so please assigne me on this issues.

**Comment by pascalgrimaud** [comment]
cc @vishal423 : as you are the lead on svelte blueprint, so you know the work will start soon

**Comment by vishal423** [comment]
I think we should go with svelte/kit as used in the blueprint

**Comment by flcarre** [comment]
Svelte kit is faster than vite ?

**Comment by vishal423** [comment]
SvelteKit is a framework for web apps and it internally uses Vite

**Comment by flcarre** [comment]
Ok fine, let's use SvelteKit so
