### ISSUE TITLE
SonarCloud: 94 code smells

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#7463]
See https://sonarcloud.io/summary/new_code?id=jhipster_jhipster-lite

Related to some changes at SonarCloud, not sure their rules are correct

**Comment by pascalgrimaud** [comment]
It's a false positive: https://community.sonarsource.com/t/false-positive-s2699-add-at-least-one-assertion-to-this-test-case/99064

So maybe nothing to do here, just wait

**Comment by pascalgrimaud** [comment]
thanks for your work, @qmonmert 
I added a bounty on this, and I'm closing this one, as it's fixed
Maybe we should do the same for generated code in Vue.js ?

**Comment by qmonmert** [comment]
@pascalgrimaud thanks for the bounty https://opencollective.com/generator-jhipster/expenses/161820 
I will do the same on the generated code in Vue.js 😉

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
