### ISSUE TITLE
Clean: application-local.properties

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#7503]
Not sure it is really used, so I think we need to remove it
So no need to maintain it in our modules

**Comment by murdos** [comment]
IMHO it's useful to have a dedicated Spring profile for configuration dedicated to development.
It should even be enabled by default, and disabled in CI/CD, in order to improves developer experience: you just need to checkout the sources, and have the fewest as possible steps to have things working locally.

**Comment by pascalgrimaud** [comment]
I can understand, but I don't want to follow generator-jhipster, with 'dev', 'prod', 'testdev', 'testprod' profiles, which are so confusing :-D

For my own use, what I put in application-local:
- change logging level, to DEBUG
- activate devtools

And that's all. Can you share me your own use ?

**Comment by murdos** [comment]
I agree that 'dev', 'prod', 'testdev', 'testprod' profiles are confusing :-D 
But I'm sure we can find a balanced in-between :-)

Use cases I see in real world enterprise applications:
- disable sending metrics and logs for observability
- use a different authentication method and/or oauth2 provider
- distinct timeouts or scheduler duration
- configure a specific maps layers provider
- specific kafka configuration (topics, timeouts, ...)
- ...

**Comment by murdos** [comment]
Another usage I was thinking about: activating AsyncSpringLiquibase for development (which is BTW the only useful usage of AsyncSpringLiquibase)

**Comment by pascalgrimaud** [comment]
We can close this, as we can keep this file
