### ISSUE TITLE
Liquibase: remove H2 dependency?

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#7516]
It seems to be only used for `SpringLiquibaseUtilTest`

**Comment by pascalgrimaud** [comment]
+1

**Comment by swarajsaaj** [comment]
Hey folks @murdos  @pascalgrimaud , Can i pick this one?

**Approach**:- 
1. Replace the `h2` jdbc url references in `SpringLiquibaseUtilTest` with one that is actually being used in the app (pick it up from `application.yml`?).
2. Also remove the `h2Dependency` from `LiquibaseModuleFactory.java`

**Comment by murdos** [comment]
Hey @swarajsaaj ,
Sure you can pick this one :) 
But honestly, as commented [here](https://github.com/jhipster/jhipster-lite/pull/9332#discussion_r1536681401), I'm not sure what's the best approach :sweat_smile: 
Thanks for your efforts!
