### ISSUE TITLE
Refactoring: Landscape.vue

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#7590]
The CSS part should be moved into **style/** folder

**Comment by murdos** [comment]
I'm going to try to fix this one

**Comment by qmonmert** [comment]
@murdos I can do this ticket if you don't have time 🙂

**Comment by murdos** [comment]
> @murdos I can do this ticket if you don't have time 🙂

Thanks, but I would like to do it since it's not my area of expertise and I would like to try and learn.
I'll tell you if I give up so you can take over 🙂

**Comment by qmonmert** [comment]
@murdos ok 🤝

**Comment by pascalgrimaud** [comment]
@qmonmert : I didn't create other tickets but the goal is to extract the css to tikui, so it's easy to find other part to work on this

**Comment by qmonmert** [comment]
@pascalgrimaud ok 👍

**Comment by qmonmert** [comment]
@murdos always motivated to do this? it's the last file to refactor and after that we we'll be able to refactor some global CSS

**Comment by murdos** [comment]
@qmonmert : feel free to pick it

**Comment by qmonmert** [comment]
@murdos sure?

**Comment by murdos** [comment]
> @murdos sure?

Sure 😉. I'm busy with the yaml spring configuration right now and real life 😀

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/167698 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
