### ISSUE TITLE
Maven: do not add dependency or plugin if it already exists

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#77]

**Comment by MSaguer** [comment]
Hi Pascal, I can help on this if you want.

**Comment by pascalgrimaud** [comment]
Yes, your help is welcome.
My idea is to have **idempotency** for all API.

**Comment by MSaguer** [comment]
I have proposed PR to have idempotency on add methods. 

I could add tests on delete methods but I'm not sure if it's really usefull. What do you think?

**Comment by pascalgrimaud** [comment]
@MSaguer : thanks for helping this project

For delete methods, no need for now.
It's better to add these checks only when we need.
