### ISSUE TITLE
Missing espace character

### ISSUE THREAD

**Issue by qmonmert** [jhipster/jhipster-lite#7730]
@pascalgrimaud espace character shoud be present betweeen `package` and `-`, `name` and `-` ... ?

![image](https://github.com/jhipster/jhipster-lite/assets/9989211/8ba2af3d-53d2-4fef-a046-6b4c05dedcb0)

**Comment by pascalgrimaud** [comment]
@qmonmert : yes it should be a space :-)

**Comment by qmonmert** [comment]
ok I fix it
