### ISSUE TITLE
React: add cypress

### ISSUE THREAD

**Issue by flcarre** [jhipster/jhipster-lite#776]

**Comment by flcarre** [comment]
pls assigne me @pascalgrimaud

**Comment by pascalgrimaud** [comment]
Unless I'm wrong, I think it could be created in a new context here:
https://github.com/jhipster/jhipster-lite/tree/main/src/main/java/tech/jhipster/lite/generator/client

We'll have client/cypress or client/e2e/cypress
This new API could be used by Angular, React or Vue, as it does not depend on Client.
What do you think ?

**Comment by flcarre** [comment]
I think as Vue and React are on vite, It could bé possible that they need the same configuration. But for Angular and Svelte i have to check to confirm

**Comment by flcarre** [comment]
React and Vue have `@cypress/react` and `@cypress/vue`, so the dependencies are different. This dependencies contains utils fonction for testing. It's possible to use cypress without this packages but this will affect the DX. Svelte and Angular haven't this utils fonction for now. As Vue and React use Vite, the configuration will be different for Svelte and Angular than Vue and React. I think the better choice is to add 1 controller for each framework

**Comment by flcarre** [comment]
https://opencollective.com/generator-jhipster/expenses/72260

**Comment by pascalgrimaud** [comment]
@flcarre : approved
