### ISSUE TITLE
Use `@` instead of `../../../../`

### ISSUE THREAD

**Issue by nonomoho** [jhipster/jhipster-lite#780]
we really need to find a way to use `@` instead, but can be done in another PR

_Originally posted by @pascalgrimaud in https://github.com/jhipster/jhipster-lite/pull/724#discussion_r808102670_

**Comment by nonomoho** [comment]
I take it @pascalgrimaud

**Comment by pascalgrimaud** [comment]
adding a bounty as I spent hours on this and didn't manage to find the fix!
Thanks so much @nonomoho
