### ISSUE TITLE
Display the version in navbar

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#7818]
It would be cool to display the version of JHLite in the navbar. For example here:

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/7150ea80-1215-4962-9b07-9ec666adfa07)

Or somewhere else, if there is any other suggestion

The information is provided by the management api:

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/70aa3f86-39a4-40ce-93d3-fbe4c330ec2b)

**Comment by pascalgrimaud** [comment]
@qmonmert : increasing the bounty for the big amount of recent work on this project. Thanks so much <3

**Comment by qmonmert** [comment]
@pascalgrimaud thanks a lot 😇 https://opencollective.com/generator-jhipster/expenses/169823

**Comment by pascalgrimaud** [comment]
@qmonmert : approved !
