### ISSUE TITLE
React: account with authentication JWT

### ISSUE THREAD

**Issue by flcarre** [jhipster/jhipster-lite#790]

**Comment by pascalgrimaud** [comment]
As discussed, plz provide first a sample project, before working on the generator part
it will be easier for you

**Comment by flcarre** [comment]
Work In Progress here: https://github.com/flcarre/jhipster-lite-react-login-template

**Comment by qmonmert** [comment]
@flcarre I tried to start your app on localhost:8080 but I have an error

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/9989211/167252297-01224408-4299-401a-9293-6b26b6aeac6e.png">

**Comment by flcarre** [comment]
That's strange i don't have this issue, does the website crash ?

**Comment by pascalgrimaud** [comment]
increasing the bounty as it was more work than expected

**Comment by flcarre** [comment]
Thanks for the bounty ! 
https://opencollective.com/generator-jhipster/expenses/84483

**Comment by pascalgrimaud** [comment]
@flcarre : approved
