### ISSUE TITLE
Add package-info.java in dummy feature

### ISSUE THREAD

**Issue by cvirieux** [jhipster/jhipster-lite#7965]
I was playing with the dummy feature and I noticed that package-info.java was not present in the bounded context. 
In my opinion, it suppose to have a BusinessContext like package-info.

![image](https://github.com/jhipster/jhipster-lite/assets/12132069/938191a1-8221-4118-bd8e-63c9fac3055c)

**Comment by pascalgrimaud** [comment]
yes, and it's not the single place where package-info.java is missing
so it's a good idea to add this when missing :)
