### ISSUE TITLE
JHLite : online version without management info

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#8026]
See https://lite.jhipster.tech/management/info

There is no version:

```json
{"git":{}}
```

cc @jdubois : I don't know how the project is built but the git version is missing. Maybe it's related to how you clone the project?

**Comment by zhyd1997** [comment]
![IMG_1243](https://github.com/jhipster/jhipster-lite/assets/31362988/2f83f50e-f2a3-49ad-b521-0ed4c778441b)

Works for me

**Comment by pascalgrimaud** [comment]
Still missing the tag version but it's better than before, as @jdubois worked on the graalvm version

**Comment by zhyd1997** [comment]
Some findings: https://github.com/search?q=repo%3Ajhipster%2Fjhipster-lite%20branch&type=code

**Comment by pascalgrimaud** [comment]
Wonder if your solution can work, as currently we have:

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/5a18f5e0-df6b-482c-bc18-19003f9daad9)

So it really depends on how the build is done by Julien :D

**Comment by zhyd1997** [comment]
Yes, tested and the solution worked

just checkout the pr branch

run  ./mnvw and go to the info url

The release info will show
