### ISSUE TITLE
SpringDoc: fix method name with lower case 1st letter

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#804]
![image](https://user-images.githubusercontent.com/9156882/155185369-42fbb44e-11aa-4489-93be-8bd52860449f.png)

To change:
- https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/springboot/mvc/springdoc/src/SpringDocConfiguration.java.mustache#L19
- https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/springboot/mvc/springdoc/src/SpringDocConfigurationSecurityJWT.java.mustache#L23
- https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/springboot/mvc/springdoc/src/SpringDocConfigurationSecurityJWT.java.mustache#L49

**Comment by Bolo89** [comment]
@pascalgrimaud can u assign me the issue ? Thanks
