### ISSUE TITLE
Angular: empty home page

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#807]
Similar to what is done in Vue/Vite

**Comment by qmonmert** [comment]
I take this ticket

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/65404 :)

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by qmonmert** [comment]
thanks @pascalgrimaud
