### ISSUE TITLE
React: empty home page

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#808]
Similar to what is done in Vue/Vite

**Comment by flcarre** [comment]
Please assign me

**Comment by qmonmert** [comment]
I take this ticket

**Comment by flcarre** [comment]
> I take this ticket

Already done

**Comment by pascalgrimaud** [comment]
@flcarre : oh sad, don't forget to comment the ticket, so there is no double work

**Comment by flcarre** [comment]
I havent work on this, i just was pranked Yesterday too 😅

**Comment by flcarre** [comment]
Done in #862

**Comment by pascalgrimaud** [comment]
@flcarre : no, see https://github.com/jhipster/jhipster-lite/tree/main/src/main/resources/generator/client/vite/react/src/main/webapp/app/common/primary/app

The default App.tsx still contain some CSS, it should be simple text.

**Comment by flcarre** [comment]
Oh ok 😅 i thought the issue was for the "styled" api

**Comment by pascalgrimaud** [comment]
Time to wake up and take a coffee :-)

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/65923 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : approved and thanks for helping this project!

**Comment by qmonmert** [comment]
thanks 🙂
