### ISSUE TITLE
Switch Spring configuration format to YAML by default

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#8093]
Following https://github.com/jhipster/jhipster-lite/issues/7939. 
We should do that before release 1.0.

**Comment by pascalgrimaud** [comment]
totally agree

**Comment by pascalgrimaud** [comment]
@murdos : did you start this ?

**Comment by murdos** [comment]
Not yet. If anyone want to do it, feel free to take the ticket :)

**Comment by pascalgrimaud** [comment]
I'm starting this, but I don't know when I'll finish it, as it is needed before the next release 1.0.0
