### ISSUE TITLE
Bug: missing defined lib so no update

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#8258]
We need to check for each version, if the lib is defined in the pom.xml
Because, when the lib is missing, the version is not updated by dependabot

See https://github.com/jhipster/jhipster-lite/blame/main/src/main/resources/generator/dependencies/pom.xml

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/d916d949-7ca7-49c1-abfa-70a281378ae8)

**Comment by atomfrede** [comment]
If I am not mistaken imported boms are also not updated via dependabot (e.g. testcontainers). Or must the version property follow a certain naming schema, e.g. `testcontainers-bom.version` in this case?

**Comment by pascalgrimaud** [comment]
yes, something to do here :D

**Comment by murdos** [comment]
> If I am not mistaken imported boms are also not updated via dependabot (e.g. testcontainers). Or must the version property follow a certain naming schema, e.g. `testcontainers-bom.version` in this case?

FYI this was due to missing `<type>pom</type>` in dependency declaration, that was preventing dependabot to find new version (since it's searching a jar):
```
pdater | 2024/02/27 00:33:31 INFO <job_792541647> Checking if org.testcontainers:testcontainers-bom 1.19.4 needs updating
  proxy | 2024/02/27 00:33:31 [403] GET https://repo.maven.apache.org:443/maven2/org/testcontainers/testcontainers-bom/maven-metadata.xml
  proxy | 2024/02/27 00:33:31 [403] 200 https://repo.maven.apache.org:443/maven2/org/testcontainers/testcontainers-bom/maven-metadata.xml
  proxy | 2024/02/27 00:33:31 [405] HEAD https://repo.maven.apache.org:443/maven2/org/testcontainers/testcontainers-bom/1.19.6/testcontainers-bom-1.19.6.jar
  proxy | 2024/02/27 00:33:31 [405] 404 https://repo.maven.apache.org:443/maven2/org/testcontainers/testcontainers-bom/1.19.6/testcontainers-bom-1.19.6.jar
```

**Comment by murdos** [comment]
@pascalgrimaud Bounty claimed: https://opencollective.com/generator-jhipster/expenses/194292
