### ISSUE TITLE
Vue app generated has not 100% coverage

### ISSUE THREAD

**Issue by qmonmert** [jhipster/jhipster-lite#8400]
We can see here: https://github.com/jhipster/jhipster-lite/actions/runs/7224050067/job/19684719698

<img width="691" alt="image" src="https://github.com/jhipster/jhipster-lite/assets/9989211/4fd8e0e6-1210-4358-83c3-5e34a9824795">

**Comment by qmonmert** [comment]
@pascalgrimaud the build should be in error or not?

**Comment by pascalgrimaud** [comment]
adding a bounty as it's important to be fixed

**Comment by qmonmert** [comment]
@pascalgrimaud thanks for the bounty 🙂 https://opencollective.com/generator-jhipster/expenses/178810

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
