### ISSUE TITLE
Custom JHLite - instructions in markdown

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#8503]
We need to check if the instructions in markdown work well.
The last time I tried (v1.0.0 if I remember well), I need to do some changes and the Cucumber tests didn't work (probably related to upgrade to last version of Spring Boot)

To do here:
- check the instructions and update if necessary
- if there are some bugs, it needs to be fixed

**Comment by renanfranca** [comment]
@pascalgrimaud : I'm going to work on this issue, is it ok?

**Comment by pascalgrimaud** [comment]
Yes plz go ahead @renanfranca
