### ISSUE TITLE
Use renovate to automatically update maven and gradle wrappers

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#8512]
Since dependabot does not support neither [maven-wrapper](https://github.com/dependabot/dependabot-core/issues/485) nor [gradle-wrapper](https://github.com/dependabot/dependabot-core/issues/2223) I propose to use renovate to automate updating our wrappers.

**Comment by murdos** [comment]
@pascalgrimaud : the next step, when you have some time, would be to install the renovate app for this repo: https://github.com/apps/renovate. 
I've just sent a request for configure it, maybe you'll receive it.

**Comment by pascalgrimaud** [comment]
Just approved it

**Comment by murdos** [comment]
It seems that now you also need to "onboard the organisation": https://developer.mend.io/github/jhipster

**Comment by murdos** [comment]
Everything required has been done, closing the issue :)
