### ISSUE TITLE
Consider using another github action for labelling issues

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#8528]
https://github.com/andymckay/labeler is not maintained anymore, and last release is from 2021

There's a warning on each [triage actions run](https://github.com/jhipster/jhipster-lite/actions/workflows/triage.yml):
> apply-label
The following actions uses node12 which is deprecated and will be forced to run on node16: andymckay/labeler@master. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by renanfranca** [comment]
@murdos : I found a reliable github-action developed by github itself: https://github.com/github/issue-labeler

I've already made it work (at my fork https://github.com/renanfranca/jhipster-lite/actions/runs/7725654397) but even though it is using node16 a warning about node20 appears.
![image](https://github.com/jhipster/jhipster-lite/assets/6011616/7926587d-4ce3-4132-959c-f7b1ec4b9955)

So I created at the github-action repo an issue and pull request which updates to node20 and I am waiting to be reviewed:
- https://github.com/github/issue-labeler/pull/82

**Comment by renanfranca** [comment]
@murdos : I think we can close this issue. What do you think?

**Comment by murdos** [comment]
@renanfranca : sure!
