### ISSUE TITLE
Add missing gradle plugins in generators

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#8588]
Following #4955, the following generators need to be completed with the gradle plugin equivalent to the maven plugin used:
- [x] SpringBootCoreModuleFactory
- [x] GitInfoModuleFactory
- [x] SonarQubeModulesFactory
- [x] https://github.com/jhipster/jhipster-lite/issues/9743
- [x] GradleModuleFactory (add the jacoco plugin that is currently hard-coded in the gradle bootstrap templates)

**Comment by atomfrede** [comment]
If you like I can take at least one or two of them

**Comment by murdos** [comment]
@atomfrede : sure, go ahead! thanks :-)

**Comment by murdos** [comment]
@atomfrede : I'll handle SpringBootCoreModuleFactory since I'll need it soon

**Comment by atomfrede** [comment]
@murdos I have started with with the git module

**Comment by atomfrede** [comment]
@murdos  Have you started to work on another module? If not I plan to work on the frontend plugin next week.

**Comment by murdos** [comment]
@atomfrede :+1: I have not started any work yet :-)

**Comment by renanfranca** [comment]
@murdos : I will try this one `SonarQubeModulesFactory`, is it OK? I spent some time to understand the great work you did here: 
- https://github.com/jhipster/jhipster-lite/issues/1862

**Comment by murdos** [comment]
@renanfranca : Sure, go ahead, thanks :) 
You can check the two previous modules that have been completed, if it can also help you:
- https://github.com/jhipster/jhipster-lite/pull/8623
- https://github.com/jhipster/jhipster-lite/pull/8620

**Comment by renanfranca** [comment]
> @renanfranca : Sure, go ahead, thanks :) 
> You can check the two previous modules that have been completed, if it can also help you:
> - https://github.com/jhipster/jhipster-lite/pull/8623
> - https://github.com/jhipster/jhipster-lite/pull/8620

Thanks! All the help is welcome 🙏

**Comment by renanfranca** [comment]
> [ ] FrontendMavenModuleFactory

Keep moving, almost there 😁🖖

**Comment by atomfrede** [comment]
I don't know the first plugin. Would go with the node-gradle plugin as it works very well and can be configured easily without too many features and assumptions.

**Comment by renanfranca** [comment]
Thank you very much, @murdos and @atomfrede ! I will try to create a sample and share it here before continuing to implement the module 😁

**Comment by renanfranca** [comment]
@murdos and @atomfrede : Here is the [sample-frontend-gradle-project](https://github.com/renanfranca/sample-frontend-gradle) and here is [the suggested implementation ](https://github.com/renanfranca/sample-frontend-gradle/pull/1) (I add a comment at the files changes as well asking specific question).  **WDYT?** 😁🖖

**Comment by murdos** [comment]
@renanfranca : I'm not a gradle expert, so it would be better to wait for @atomfrede review, but it seems fine :-) (I've added directly comments on the PR)

**Comment by atomfrede** [comment]
Will have a look tomorrow.

**Comment by pascalgrimaud** [comment]
Added a bounty, you can claimed it @renanfranca

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/203320. Thanks 😄 ✌

**Comment by pascalgrimaud** [comment]
@renanfranca : approved
