### ISSUE TITLE
Module jacoco-check-min-coverage should work with gradle

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#8625]
The module is currently doing a mandatory replacement on `pom.xml` and don't use any maven plugin API of  `JHipsterModuleBuilder`:
https://github.com/jhipster/jhipster-lite/blob/5ba4d5674209f7f040b5ea9d0bc0f4d651f47290/src/main/java/tech/jhipster/lite/generator/server/javatool/jacoco/domain/JacocoThresholdModuleFactory.java#L16

We can convert the mandatory replacement in the `pom.xml` to an optional replacement, and add a new second optional replacement for `build.gradle.kts`. But this is not very robust, because the replacement can fail silently.

Another option is to use the maven / gradle plugin addition API of  `JHipsterModuleBuilder`, but the underlying java build commands should either be able to replace existing plugin presence to avoid duplicated plugin declaration, or the module should drop the plugin the re-add it with the new configuration.

**Comment by murdos** [comment]
@renanfranca : I saw that you assigned this issue to yourself.

Just to share my vision: I think the best way to solve it would be to move jacoco plugin configuration out of MavenModuleFactory/GradleModuleFactory to a new jacoco module that would contains both "basic" jacoco slug, and the jacoco-check-min-coverage slug.
That way configuration would be factorized in this JacocoModuleFactory, and jacoco-check-min-coverage could easily drop the existing plugin and re-add it with the amended configuration.
WDYT?

**Comment by renanfranca** [comment]
> @renanfranca : I saw that you assigned this issue to yourself.
> 
> Just to share my vision: I think the best way to solve it would be to move jacoco plugin configuration out of MavenModuleFactory/GradleModuleFactory to a new jacoco module that would contains both "basic" jacoco slug, and the jacoco-check-min-coverage slug. That way configuration would be factorized in this JacocoModuleFactory, and jacoco-check-min-coverage could easily drop the existing plugin and re-add it with the amended configuration. WDYT?

@murdos : Yes, I am already working on it 😃. Thank you for sharing your vision, I agree and it makes sense. I am thinking of setup `jacoco-basic` feature as a pre-requisite for the `sonar-qube-java` feature. WDYT?

**Comment by murdos** [comment]
@renanfranca : I thought a bit more about it, and we can even create a new feature `code-coverage-java` that would contain either `jacoco` or `jacoco-with-min-coverage-check`, so no need to remove and re-add the jacoco plugin, and have `sonar-qube-java` depends on the `jacoco` feature.
WDYT?

**Comment by renanfranca** [comment]
> @renanfranca : I thought a bit more about it, and we can even create a new feature `code-coverage-java` that would contain either `jacoco` or `jacoco-with-min-coverage-check`, so no need to remove and re-add the jacoco plugin, and have `sonar-qube-java` depends on the `jacoco` feature. WDYT?

The implementation will be clear and we can do that because it doesn't need a specific slug for maven or gradle, perfect!
