### ISSUE TITLE
Support java build profile in gradle

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#8627]
The `AddJavaBuildProfile` command is not implemented in `GradleCommandHandler`

- [x] https://github.com/jhipster/jhipster-lite/pull/9163
- [x] https://github.com/jhipster/jhipster-lite/issues/8628
- [x] https://github.com/jhipster/jhipster-lite/pull/9369
- [ ] https://github.com/jhipster/jhipster-lite/pull/9437

**Comment by renanfranca** [comment]
@murdos : I want to try to fix this issue, is it ok for you?

**Comment by murdos** [comment]
@renanfranca : sure :-)

**Comment by renanfranca** [comment]
@murdos : Please, let me know WDYT about the following solution proposal to implement the java build profile in gradle. This proposal only covers this part:

> [ ] Add build profile, with activation
 [ ] Add properties

I generated the `gradleapp` from `generate.sh` and implemented the changes over it published at this repository [gradleapp-profiles-sample](https://github.com/renanfranca/gradleapp-profiles-sample). Here is the PR with the changes [simulate local and linux profile module in gradle](https://github.com/renanfranca/gradleapp-profiles-sample/pull/1/files). **I ran the solution through sonar and it didn't point to any code smells.**

I am going to break down my suggestions here.

### First here is the build command

```java
return moduleBuilder(properties)
      .javaBuildProfiles()
        .addProfile("local")
          .activation("")
          .properties()
            .set(buildPropertyKey("spring.profiles.active"), buildPropertyValue("local"))
            .and()
          .and()
        .and()
        .addProfile("linux")
          .activation(
               """
               System.getProperty("os.name").lowercase().contains("linux")
               """)
          .properties()
            .set(buildPropertyKey("spring.profiles.active"), buildPropertyValue("linux"))
            .and()
          .and()
        .and()
```

### The gradle commands and the output:
```bash
./gradlew --info --rerun-tasks  ➝ spring.profiles.active = local

./gradlew -Pprofile=local --info --rerun-tasks  ➝ spring.profiles.active = local

./gradlew -Pprofile=linux --info --rerun-tasks  ➝ spring.profiles.active = linux
```

### The proposal code
Here is only the changed code from the build.gradle.kts (here is the PR at the gradleapp-profiles-sample [simulate local and linux profile module in gradle](https://github.com/renanfranca/gradleapp-profiles-sample/pull/1/files)):
```kts
tasks.build {
  dependsOn("processResources")
}

tasks.processResources {
  var profile = profile()
  filesMatching("**") {
    filter { line -> profilesProperties(profile, line) }
  }
  // jhipster-needle-gradle-process-resources
}

fun defaultProfile(): String {
  return "default"
}

fun profile(): String {
  var profile = project.findProperty("profile") as String? ?: defaultProfile()
  println("Selected Spring Boot profile: $profile")
  println("Os name: ${System.getProperty("os.name").lowercase()}")
  if (profile != defaultProfile()) {
    return profile
  }
  return profilesActivation()
}

fun profilesActivation(): String {
    return listOf(::localProfileActivation, ::linuxProfileActivation)
        .firstNotNullOfOrNull { it().takeIf { profile -> profile != defaultProfile() } }
        ?: defaultProfile()
}

fun localProfileActivation(): String = "local"

fun linuxProfileActivation(): String =
    if (System.getProperty("os.name").lowercase().contains("linux")) "linux" else defaultProfile()

fun profilesProperties(profile: String, line: String): String {
  return when (profile) {
    "local" -> localProfileProperties(profile, line)
    "linux" -> linuxProfileProperties(profile, line)
    else -> line
  }
}

fun localProfileProperties(profile: String, line: String): String {
  var lineReplaced: String = line
  lineReplaced = lineReplaced.replace("@spring.profiles.active@", profile)
  return lineReplaced
}

fun linuxProfileProperties(profile: String, line: String): String {
  var lineReplaced: String = line
  lineReplaced = lineReplaced.replace("@spring.profiles.active@", profile)
  return lineReplaced
}
// jhipster-needle-gradle-profiles
```

### Adittional information
I search a lot for a reference or a best practice guide. But there isn't an official way to implement profiles on gradle ([Gradle's Support for Maven POM Profiles](https://blog.gradle.org/maven-pom-profiles)). Actually, I didn't found a lot of material about Gradle during my previously fixed issues. That's makes me think that this support for Gradle here at jhlite is going to help a lot of people to understand and learn about Gradle.

Let me kno

**Comment by murdos** [comment]
@renanfranca : The only profile activation that is currently supported is activeByDefault (`true`/`false`):
```java
        .addProfile("local")
          .activation(buildProfileActivation().activeByDefault())
```
Don't try to handle activation depending on OS, this is a different feature, it's not even supported for maven in jhipster-lite yet ;-)

Then my vision was initially to try replicated what is done in generator-jhipster, with conventional plugins: https://github.com/jhipster/jhipster-sample-app-gradle/blob/main/gradle/profile_dev.gradle

It seems to be a bit different with kts, but this could look like [this](https://github.com/renanfranca/gradleapp-profiles-sample/pull/2/files), using [Precompiled script plugins](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins)

It's not yet working, but it is getting late here so I have to stop for now.
```shell
./gradlew build -x test --rerun-tasks -PlocalProfile=false && grep "active:" build/resources/main/config/application.yml 
    active: "local"
```

**Comment by renanfranca** [comment]
> Don't try to handle activation depending on OS, this is a different feature, it's not even supported for maven in jhipster-lite yet ;-)

Thank you very much for taking a close look (later at 🌙). I really appreciate it. I am going to follow your approach by setting different files it is less complicated for sure 👏 i will keep you inform of the progress 👍

**Comment by renanfranca** [comment]
> It's not yet working, but it is getting late here so I have to stop for now.
> 
> ```shell
> ./gradlew build -x test --rerun-tasks -PlocalProfile=false && grep "active:" build/resources/main/config/application.yml 
>     active: "local"
> ```

@murdos : I tried your code and it works. It changes the spring profile to local. I used the command without the `active: "local"` at the end:
```shell
 ./gradlew build -x test --rerun-tasks -PlocalProfile=false && grep "active:" build/resources/main/config/application.yml 
```

I took my time to learn the Precompiled script plugins and I have a slightly different version from yours. Please, when you have the time, take a look [Implement profiles activations with precompiled script plugin](https://github.com/renanfranca/gradleapp-profiles-sample/pull/3/files)

**Comment by murdos** [comment]
Re-opening this there's still work to do on the subject.

**Comment by renanfranca** [comment]
> [ ] Support dependencies (and dependencies management) in a build profile

Moving on 🖖

**Comment by renanfranca** [comment]
@murdos : I implement [here](https://github.com/renanfranca/gradleapp-profiles-sample/pull/4/files#diff-e9572f3c4daf14df2eb25464e3c4fdac66dd4058d57eb2540f14810e18217b28), [the workaround](https://github.com/gradle/gradle/issues/15383#issuecomment-1940357260) to use libs from `libs.versions.toml` at profiles dependencies. There are some modified files, but the most important are `buildSrc/settings.gradle.kts` and `buildSrc/src/main/kotlin/profile-local.gradle.kts`. I ran the command to start spring boot ` ./gradlew -x test --rerun-tasks -Pprofile=local --info` and everything went well. **WDYT?** 😃

**Comment by murdos** [comment]
@renanfranca : nice workaround! The final syntax is quite similar to normal syntax, so let's use that :)

**Comment by renanfranca** [comment]
> @renanfranca : nice workaround! The final syntax is quite similar to normal syntax, so let's use that :)

I am glad you liked it! I will work on it tomorrow 🙌

**Comment by renanfranca** [comment]
> [ ] Support gradle plugins in a build profile

@murdos : I implemented [here](https://github.com/renanfranca/gradleapp-profiles-sample/pull/5/files) by following the gradle docs [Applying external plugins](https://docs.gradle.org/current/userguide/implementing_gradle_plugins_precompiled.html#sec:applying_external_plugins) an example moving the git-properties plugin configuration from the main `build.gradle.kts` to `buildSrc/src/main/kotlin/profile-local.gradle.kts`. **WDYT?**

**Comment by murdos** [comment]
@renanfranca : I guess we don't really have choice, we have to do it the only way it'll work 😅
It means that for grade plugins in a build profile the module API will require the plugin dependency id (group + artifact), since we can't deduce it from plugin id.
Anyway great investigation!

**Comment by renanfranca** [comment]
>  Support gradle plugins in a build profile

I am already working on it. I am struggling a bit with the refactoring 😁

**Comment by murdos** [comment]
> I am already working on it. I am struggling a bit with the refactoring 😁

Hang in there! Don't hesitate to push a first PR with just the refactoring part, if it can simplify the process and the review.

**Comment by renanfranca** [comment]
> Hang in there! Don't hesitate to push a first PR with just the refactoring part, if it can simplify the process and the review.

Thanks my friend! I am going to push tomorrow and I am going to point out what I think could be better but I didn't find a better way 👍

**Comment by renanfranca** [comment]
@murdos: Thank you very much for always being available and providing excellent reviews, as well as collaborating effectively to find solutions! Let's keep going on the Gradle track 😁🖖

**Comment by pascalgrimaud** [comment]
I'm adding another bounty for you @murdos as you spent a lot of time to review

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/197506. Thanks 😄 ✌

**Comment by pascalgrimaud** [comment]
@renanfranca : approved

**Comment by murdos** [comment]
@pascalgrimaud bounty claimed: https://opencollective.com/generator-jhipster/expenses/203260

**Comment by pascalgrimaud** [comment]
@murdos : approved
