### ISSUE TITLE
Spring Boot Database: Cassandra

### ISSUE THREAD

**Issue by matthieuRioual** [jhipster/jhipster-lite#877]
Like generator-jhipster is currently doing, the goal of this issue would be to help users to add configuration for cassandra into their application.

**Comment by pascalgrimaud** [comment]
Adding a bounty, as Datastax is our sponsor and it should not be hard to have and maintain this option

**Comment by pascalgrimaud** [comment]
Increasing the bounty to motivate people as it's a good feature to have, and for our sponsor

**Comment by murdos** [comment]
FYI I've started to work on implementing this feature

**Comment by pascalgrimaud** [comment]
Thanks @murdos 
It's an important feature as Datastax is one of our sponsor. And after some years, Cassandra support in generator-jhipster doesn't require too much maintenance so it won't be hard to maintain here

**Comment by Yourgene** [comment]
> FYI I've started to work on implementing this feature

Hi I just noticed you started working on the issue before me... I though you were the author of the closed issue, so you weren't working on it anymore.

I'm really sorry about that. 

If you wrote code, do you want to maybe team up and improve/discuss on your work and mine ?

**Comment by murdos** [comment]
> > FYI I've started to work on implementing this feature
> 
> Hi I just noticed you started working on the issue before me... I though you were the author of the closed issue, so you weren't working on it anymore.
> 
> I'm really sorry about that. 
> 
> If you wrote code, do you want to maybe team up and improve/discuss on your work and mine ?

Don't worry, my work was not really advanced.
And meanwhile I started working on gradle support, so I'm not bored 🙂

**Comment by Yourgene** [comment]
Phew, I’m happy to hear that it’s alright :)

On 13 Jan 2023, at 18:33, Aurélien Mino ***@***.***> wrote:



FYI I've started to work on implementing this feature

Hi I just noticed you started working on the issue before me... I though you were the author of the closed issue, so you weren't working on it anymore.

I'm really sorry about that.

If you wrote code, do you want to maybe team up and improve/discuss on your work and mine ?

Don't worry, my work was not really advanced.
And meanwhile I started working on gradle support, so I'm not bored 🙂

**Comment by pascalgrimaud** [comment]
@Yourgene : don't forget to claim your bounty here as this 1st one is closed.
For the cassandra migration, I opened a new ticket
