### ISSUE TITLE
jhipster-lite-sample-app without maven wrapper

### ISSUE THREAD

**Issue by DanielFran** [jhipster/jhipster-lite#8892]
Since jhlite 1.3.0, the maven wrapper has been removed.

See: https://github.com/jhipster/jhipster-lite-sample-app/commit/2d7b322c7b56d5800f51d31304849f814e199855

**Comment by pascalgrimaud** [comment]
thanks @DanielFran 
Indeed, we need to update this: https://github.com/jhipster/jhipster-lite-sample-app/blob/main/generate.sh#L62
