### ISSUE TITLE
Handle different frontend build output directory for maven and gradle

### ISSUE THREAD

**Issue by renanfranca** [jhipster/jhipster-lite#8963]
Today the output directory is fixed to the `target` folder. When generating a gradle project the output folder should be `build`.

It will be challenging because you can apply a frontend module without choosing the `java-build-tool`, so the generator can't automatically detect the correct output directory based on `pom.xml` or `build.gradle.kts` existence.

Vue configuration which needs to be fixed `vitest.config.mts`:
```mts
 test: {
    reporters: ['verbose', 'vitest-sonar-reporter'],
    outputFile: {
      'vitest-sonar-reporter': 'target/test-results/TESTS-results-sonar.xml',
    },
```
```mts
      provider: 'istanbul',
      reportsDirectory: 'target/test-results/',
      reporter: ['html', 'json-summary', 'text', 'text-summary', 'lcov', 'clover'],
```

`vite.config.mts`:
```mts
  build: {
    outDir: '../../../target/classes/static',
  },
```

Needed by:
- https://github.com/jhipster/jhipster-lite/pull/8867#issuecomment-1947650464

**Comment by murdos** [comment]
@renanfranca : Could I work on this issue? I've my own idea that I would like to experiment.
My intent is to enrich `JHipsterModuleContext` in `JHipsterModulesApplyer` with additional properties in function of the detected build tool, such as `project.build.directory`, so it could be use in templates.  `project.build.directory` would be valued to `target` for maven (and probably also if no java build tool is found), and to `build` for gradle.

**Comment by renanfranca** [comment]
> @renanfranca : Could I work on this issue? I've my own idea that I would like to experiment.
> My intent is to enrich `JHipsterModuleContext` in `JHipsterModulesApplyer` with additional properties in function of the detected build tool, such as `project.build.directory`, so it could be use in templates.  `project.build.directory` would be valued to `target` for maven (and probably also if no java build tool is found), and to `build` for gradle.
> 
> **Update**: #9029 is a step in that direction

@murdos : Sure, go for it! I over think about some approaches too and I will be happy to review the code when you finish it. I agree to be target folder if didn't detect any build tool.

**Comment by murdos** [comment]
@pascalgrimaud Bounty claimed: https://opencollective.com/generator-jhipster/expenses/203259

**Comment by pascalgrimaud** [comment]
@murdos : approved
