### ISSUE TITLE
Gradle: handle dependencies exclusion

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#9052]
Example use case: `spring-boot-undertow` jhlite module needs to exclude dependency `spring-boot-starter-tomcat`.
Currently the generated app with `spring-boot-undertow` starts with tomcat :(

**Comment by murdos** [comment]
@pascalgrimaud : bounty claimed https://opencollective.com/generator-jhipster/expenses/199151

**Comment by pascalgrimaud** [comment]
@murdos : approved
