### ISSUE TITLE
Module: renovate

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#9060]
It might be nice to have a module to configure [renovate](https://github.com/renovatebot/renovate) for a jhipster-lite generated project, with e.g. docker-compose dependencies update for content in `src/main/docker` (as done in #9059) and good default settings.

**Comment by swarajsaaj** [comment]
Can I pick this up, if no one is working on it?
And if I understand correctly, this has to be done for all dependencies in generated projects and not just docker images?

**Comment by murdos** [comment]
:+1: Exact, it's for handling all dependencies, not just docker.
