### ISSUE TITLE
Spring Boot Database: Add User changelogs with MariaDB and liquibase

### ISSUE THREAD

**Issue by seraphinandrieux** [jhipster/jhipster-lite#916]
Same as Postgresql or Mysql, the point is to add an user context linked to MariaDB and liquibase.

**Comment by seraphinandrieux** [comment]
@pascalgrimaud , could you assign to me this ticket please ?

**Comment by pascalgrimaud** [comment]
sure @seraphinandrieux : done
thanks a lot :)
