### ISSUE TITLE
Spring Boot Database: Add User sql scripts with MariaDB and Flyway

### ISSUE THREAD

**Issue by seraphinandrieux** [jhipster/jhipster-lite#917]
Similar to #916. Instead of using liquibase, here use flyaway.

**Comment by pascalgrimaud** [comment]
I'll assign it to you @seraphinandrieux when you start it :D

**Comment by seraphinandrieux** [comment]
> I'll assign it to you @seraphinandrieux when you start it :D

for sure :)

**Comment by seraphinandrieux** [comment]
Hey again @pascalgrimaud ,
Could you assign to me this ticket, I'm working on it

**Comment by pascalgrimaud** [comment]
done! Thanks @seraphinandrieux

**Comment by pascalgrimaud** [comment]
Adding a bounty for the work done for this ticket + https://github.com/jhipster/jhipster-lite/issues/916
