### ISSUE TITLE
Spring Security without the WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#920]
Following these links:
- https://twitter.com/mraible/status/1499752697406361601
- https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter

Todo here, 2 PRs:
- update Spring Security, related to JWT
- update Spring Security, related to OAuth2

**Comment by pascalgrimaud** [comment]
@Bolo89 : I think it's done, right? Can we close it?

**Comment by Bolo89** [comment]
Yes it can be closed
