### ISSUE TITLE
History: API to list history

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#935]
Simply read the history file and send it
I think it can be used in front when displaying button

**Comment by seraphinandrieux** [comment]
@pascalgrimaud Is it possible to work on it ?
Thanks :)

**Comment by Franceq34** [comment]
I see this ticket was merged and closed, I tested it it works fine congrats @seraphinandrieux :) May I create a ticket to retrieve in the generator ? @pascalgrimaud

**Comment by pascalgrimaud** [comment]
@Franceq34 : yes you can. First, we can build the secondary in a common context, to retrieve the history. Then later, we'll see how we can use it
