### ISSUE TITLE
Gradle: ability to declare resources filtering in a generic way

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#9405]
Needed to support gradle in the `spring-boot-local-profile` module.

With maven, this is indirectly declared by declaring and configuring the `maven-resources-plugin`.
But with gradle it can't be done by declaring a plugin.
Maybe for gradle we should support declaring a free configuration block. Not perfect, if multiple modules need to declare resources filtering, but it might be enough in the first instance

**Comment by renanfranca** [comment]
I was thinking about that, too. I agree with you,  I think implementing a needle to resource filtering is too much now.
