### ISSUE TITLE
Migration ESLint 9.0.0

### ISSUE THREAD

**Issue by qmonmert** [jhipster/jhipster-lite#9476]
https://eslint.org/docs/latest/use/configure/migration-guide

Waiting 
- [x] https://github.com/typescript-eslint/typescript-eslint/issues/8211

Fix https://github.com/jhipster/jhipster-lite/pull/9481

**Comment by Gnuk** [comment]
Is-it fot the generator itself ?
 If it's for this I can do this.

**Comment by qmonmert** [comment]
@Gnuk yes this ticket is for the generator
