### ISSUE TITLE
NPM warning about core-js

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#9489]
![image](https://github.com/jhipster/jhipster-lite/assets/9156882/f2025888-8b48-4608-9cda-9ffed5249fc2)

```
➜ npm ci
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
```

I don't know if it could be fixed easily

**Comment by murdos** [comment]
This is a transitive dependency of `babel`. 
Maybe we should just wait for Babel 8 (currently in alpha) that will use core-js 3.

**Comment by pascalgrimaud** [comment]
Yes, but I created this ticket because it's a warning I saw since months
Unless I'm wrong it's related to pug-lint, which seems not to be maintained anymore

**Comment by qmonmert** [comment]
thanks @pascalgrimaud :) https://opencollective.com/generator-jhipster/expenses/198215

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
