### ISSUE TITLE
Alternative page for Landscape

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#9491]
Landscape is designed for a modular approach

After some discussion with @jdubois  and @murdos too, we think it could be interesting to have a page for beginners. The page could simply look like the one here: https://start.jhipster.tech/generate-application

It will probably help the users to try JHLite quicker

What do you think?

TO-DO:

- [x] https://github.com/jhipster/jhipster-lite/issues/10379
- [x] https://github.com/jhipster/jhipster-lite/issues/10317
- [x] https://github.com/jhipster/jhipster-lite/issues/10239

**Comment by murdos** [comment]
I was thinking more about this idea this morning, and if the Landscape page could be loaded with a list of preselected modules (and configured properties), we could use preset configuration, and consider this new page as preset builder.

**Comment by swarajsaaj** [comment]
@murdos the presets concept is similar to https://github.com/jhipster/jhipster-lite/issues/2907?

**Comment by murdos** [comment]
@swarajsaaj : yes, there's some overlap. Template and preset are the same idea. 
Replay is another use case, but it could be solved by transforming an history file to a template/preset.

**Comment by renanfranca** [comment]
I assigned myself to this issue because I would like to have a full-stack experience in jhipster-lite by implementing a new feature 😄

**Comment by renanfranca** [comment]
Here is a demo of using the preset configurations 😃💙:


https://github.com/user-attachments/assets/8ef6389f-a363-42a4-b78d-88e9bf0f5389

**Comment by renanfranca** [comment]
A demo video of the merged preset configuration feature 💙😃

https://github.com/user-attachments/assets/261ad08f-1439-49fd-b967-8827d9564691

**Comment by atomfrede** [comment]
Pretty cool! Nice work!

**Comment by renanfranca** [comment]
> Pretty cool! Nice work!

Thank you! I am glad you like it 😊

**Comment by pascalgrimaud** [comment]
Can it be closed @renanfranca ?
