### ISSUE TITLE
Weekly releases

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#9495]
Question for you @murdos @renanfranca @qmonmert

From today, I'll try to do a regular release, maybe a weekly release.
What's the best day to do it? I think it should be Friday morning.
I think it's important specially for dependencies update. I don't care if there are no new features

What do you think?

**Comment by qmonmert** [comment]
Friday morning: good for me 👍

**Comment by murdos** [comment]
Weekly is maybe a bit too frequent, how about every 2 weeks?

**Comment by qmonmert** [comment]
If there is a big release (ex: Angular), waiting two weeks is too long I think

**Comment by renanfranca** [comment]
Friday morning works well for me. 👍

Currently, I haven't had the chance to use the jhipster-lite project in my work, so whether the releases are weekly or bi-weekly is fine with me. I'll go along with whatever you all decide. 😁✌️

I'm in favor of regular releases; it's always great to see the work being published! 😀

**Comment by pascalgrimaud** [comment]
So, I'll try to do a new release every Friday morning. It means the next will be tomorrow

But, following @murdos's opinion, if there are too few changes (according to the draft release note), I'll postpone until the next Friday

**Comment by pascalgrimaud** [comment]
New release done today, v1.7.0: https://twitter.com/pascalgrimaud/status/1781411089508434213
