### ISSUE TITLE
Front: add java & springboot

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#950]
- following this https://github.com/jhipster/jhipster-lite/pull/941

It could be cool to add the following buttons + apis:
- java base
- spring boot
- spring boot mvc tomcat

**Comment by Franceq34** [comment]
working on it :office_worker:

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/jhipster-lite/pull/953
