### ISSUE TITLE
Front: add Cypress

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#956]
We should add Cypress to test the front part.
The first step would be:
- add all dependencies and configuration
- add tests
- launch Cypress in CI -> I can take care of this part

**Comment by Franceq34** [comment]
WIP :construction: :warning:

**Comment by pascalgrimaud** [comment]
The CI part is done. I'm letting your play with additional tests, related to the Generator

**Comment by Franceq34** [comment]
working on it :construction:

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/jhipster-lite/pull/969
