### ISSUE TITLE
Add a small documentation for ApprovalTests

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#9658]
Following #9607 : a documentation should be generated with a few examples, as done for [Property-based Testing](https://github.com/jhipster/jhipster-lite/blob/3266169af076475fb0b00a6e0330128371414407/src/main/resources/generator/server/javatool/pbt/property-based-testing.md):
- simple example
- example with a parametrized junit test
- example of use of [combinations](https://github.com/approvals/ApprovalTests.Java/blob/master/approvaltests/docs/tutorials/GettingStarted.md#generate-combinations-of-parameter-values)

**Comment by Harsh4902** [comment]
@murdos I want to work on this issue. How can I proceed further?

**Comment by murdos** [comment]
@Harsh4902: you should read the https://github.com/approvals/ApprovalTests.java documentation in order to get familiar with it, and then add a markdown documentation to the `approval-tests` module, as done in the `jwik` module.

**Comment by Harsh4902** [comment]
@murdos can you please review this PR?
