### ISSUE TITLE
New API in ModuleBuilder to declare entries in gitignore

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#9716]
Modules in custom-jhlite might need to add new content to `.gitignore`.

And current generated `.gitignore` contains content for all the things that jhlite is able to generate, it would be better for each module to declare things, so you get a file that fits what you have in your generated project.
A few examples : 
- `.svelte-kit/` -> only in svelte client
- `okta.sh`, `auth0.sh` -> only in you generate oauth2 with okta
- `.angular/` -> for angular client
- gradle wrapper
- maven wrapper
- ...

**Comment by murdos** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/208287

**Comment by pascalgrimaud** [comment]
@murdos : approved
