### ISSUE TITLE
Add missing gradle frontend server plugin

### ISSUE THREAD

**Issue by renanfranca** [jhipster/jhipster-lite#9743]
**Prerequisites**

- [x] #9744
- [x] https://github.com/jhipster/jhipster-lite/issues/9788
- [x] https://github.com/jhipster/jhipster-lite/issues/9813
- [x]  https://github.com/jhipster/jhipster-lite/issues/9830

[This sample](https://github.com/renanfranca/sample-frontend-gradle/pull/2/files) implemented the following features which is going to be handle by this issue:

- install the npm inside the `build` folder
- `npm install`
- `npm run build` from the `package.json`
- `npm run test` from the `package.json`
- add the frontend build project inside the .jar

To test the sample:

1. `./gradlew clean build --no-daemon --info` (will generate the .jar at `build/libs` folder)
2. `java -jar build/libs/jhipster-sample-application-0.0.1-SNAPSHOT.jar` (access the frontend at http://localhost:8080)
3. `docker compose -f src/main/docker/sonar.yml up -d` and `./gradlew clean build sonar --info` (all frontend tests will be at sonar with 100% coverage)

Sharing what I learned after a long time dedicated:
- Angular doesn't work with the Maven front-end plugin or with Gradle **edit: when run the generated .jar.**. [This was fixed at this issue](https://github.com/jhipster/jhipster-lite/issues/9830)
- Vue works with the Maven front-end plugin; it adds the `target/classes/static` folder with Vue files directly to the .jar without extra configuration.
- Vue on Gradle doesn't automatically add the static folder to the .jar. [You need to explicitly define this in `build.gradle.kts`, and also make sure that `npm run build` runs before the `tasks.bootJar` task](https://github.com/renanfranca/sample-frontend-gradle/pull/2/files#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06R103-R108), which is responsible for generating the .jar.

**Comment by renanfranca** [comment]
@murdos and @atomfrede: please let me know WDYT ;)

**Comment by atomfrede** [comment]
I will try to do a proper review later today. Thanks for putting the efforts into this 👍

**Comment by atomfrede** [comment]
@renanfranca Looks quite fine from what I can tell. For the node/npm tasks you might consider defining proper inputs and outputs to make caching (both local or via develocity) possible

**Comment by renanfranca** [comment]
Thank you for the feedback 😊 

> For the node/npm tasks you might consider defining proper inputs and outputs to make caching (both local or via develocity) possible

Can you detail which inputs and outputs (local/develocity)?

**Comment by renanfranca** [comment]
> * Angular doesn't work with the Maven front-end plugin or with Gradle **edit: when run the generated .jar.** **I didn't try react**

I tried gradle with vue and react as frontend and they are working with the implementation at draft pull request #9825 

I tried angular and it isn't working. I have to look into it.

**Comment by renanfranca** [comment]
I am in the process of removing `gradleapp` from `generator.sh` and replacing it with `fullapp` using the Gradle build tool. To see the steps I need to take to accomplish this, please [check out this pull request](https://github.com/renanfranca/fullapp-gradle/pull/1/files).

**Comment by pascalgrimaud** [comment]
You can claim the bounty of this ticket @renanfranca , in addition of the specific ones in each PRs , as it was a huge work to improve gradle support

Thanks so much for your work

**Comment by renanfranca** [comment]
> You can claim the bounty of this ticket @renanfranca , in addition of the specific ones in each PRs , as it was a huge work to improve gradle support
> 
> Thanks so much for your work

Thank you very much for the support and recognition. The quality of the code will continue to be my priority 😃✌️

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/204898. Thanks 😄 💙

**Comment by pascalgrimaud** [comment]
@renanfranca : approved
