### ISSUE TITLE
Front: add project name, package and port to front generator

### ISSUE THREAD

**Issue by Franceq34** [jhipster/jhipster-lite#984]
- rename bounded context generator to springboot
- add generator object to API and update form
"generator-jhipster": {
    "baseName": "beer",
    "projectName": "Beer Project",
    "packageName": "tech.jhipster.beer",
    "serverPort": 8080
  }

**Comment by Franceq34** [comment]
$100 bounty claimed => https://opencollective.com/generator-jhipster/expenses/74248

**Comment by pascalgrimaud** [comment]
@Franceq34 : approved
