### ISSUE TITLE
CSS to choose

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#990]
Need to be discussed first.

The final app should have less than 5 pages I think:
- account for login, register, forgot password (only for the Cloud version)
- Spring Boot generator
- maybe one day Quarkus generator
- Micronaut generator
- etc

Several options here:
- build our own CSS, and embedded in the app -> most simplest
- use an existing CSS (but we won't use all elements, so maybe it's overkill?)
  - bootstrap
  - material
  - etc

**Comment by Franceq34** [comment]
I'm open to discuss about it. 
My thoughts is that we shouldnt use bootstrap or materialize as they are too complex for our small needs. However, Tailwind could be great. 
I would like to mention @nonomoho and @seraphinandrieux here 🎨

**Comment by seraphinandrieux** [comment]
@Franceq34 I'm glad to see you have thought to me for this subject ^^
On my side, i'm not an expert at all about CSS subjects. I only had the opportunity to use a custom Pattern Library.
However I agree on the idea to go to the simplest option for now.
Maybe Later we will have to refactoring this part...

**Comment by pascalgrimaud** [comment]
After thinking about this, it took too much time to start from scratch.
So the idea would be to use an existing CSS.

I tried [quasar](https://quasar.dev/) and I'm really happy with this, so I think we should go in this direction

**Comment by pascalgrimaud** [comment]
It was hard to write unit tests with Quasar, so the current choice is to choose simple bootstrap. We use it since several years with generator-jhipster, it's simple, it works well.
So I'm fine to use it

**Comment by atomfrede** [comment]
I used tailwind and like it very much, but I guess bootstrap is the best choice as it is used widely troughout the industry and can be custimized very well if desired for the use case.

**Comment by pascalgrimaud** [comment]
yes we choose bootstrap
I'm waiting @sabrinapayet to submit some pull requests to improve this part
Then, we'll be able to add more button/api to generate all the features

**Comment by pascalgrimaud** [comment]
I think it was done!
Thanks @sabrinapayet for your work!

**Comment by sabrinapayet** [comment]
Bug bounty claim : https://opencollective.com/generator-jhipster/expenses/73694

**Comment by pascalgrimaud** [comment]
@sabrinapayet : approved
