### ISSUE TITLE
Develocity: fix warnings

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#9933]
See the current `pom.xml` :

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/b747c3ae-c544-41b9-9e82-c83d6d88be76)

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/59c4e19c-3d61-4adc-bd72-53eb96e7d7c0)

cc @atomfrede

**Comment by murdos** [comment]
@pascalgrimaud : I don't have the issue. Have you tried to allow IntelliJ to import the xsd from the `xsi:schemaLocation` (Alt+Enter on the xsd url in red)?

**Comment by pascalgrimaud** [comment]
thanks @murdos, manually download external resource, fix the issue with IntelliJ
